= Antora의 작동 방식

Antora의 사이트 생성기는 문서 사이트 생성의 모든 측면을 처리합니다. 콘텐츠를 가져오고 집계하는 것부터 변환하고 정리하는 것, 그리고 생성된 사이트의 파일을 게시하는 것까지 모두 포함됩니다. 이 페이지에서는 그 과정을 자세히 설명합니다.

기본 파이프라인은 가능한 한 빨리 시작할 수 있도록 의견이 반영되어 있습니다. 그러나 Antora는 모듈식의 개방형 아키텍처를 특징으로 한다는 점을 이해하세요. 이는 필요에 따라 검증기와 같은 사용자 정의 Antora 구성 요소를 파이프라인의 전략적 지점에 삽입하여 특수한 사용 사례를 수용할 수 있음을 의미합니다. 이 페이지는 Antora의 핵심 내장 구성 요소와 기능에 초점을 맞춥니다.

== 기본 생성기 파이프라인의 단계

이 섹션에 나열된 단계는 사이트 생성기가 수행하는 작업을 설명합니다. 특정 작업은 비동기적으로 실행되므로 아래 단계 중 일부는 다른 순서로 발생하거나 동시에 발생할 수 있습니다. 예를 들어, 네트워크 사용을 최적화하기 위해 콘텐츠가 집계되는 동안 UI가 가져와지고 로드됩니다.

__플레이북 구축__::
+
사이트를 생성할 준비가 되면 Antora에 플레이북 파일을 전달하고 실행하라고 지시합니다.
+
플레이북 파일은 YAML, JSON 또는 TOML로 작성할 수 있는 간단한 구성 파일입니다. 사용할 콘텐츠, 콘텐츠 처리 방법, 사이트 생성 방법 및 출력을 게시할 위치와 같은 정보와 설정이 포함되어 있습니다.
+
Antora는 플레이북 파일을 읽고 그로부터 플레이북을 구축한 다음, 이를 사용하여 파이프라인을 구동합니다.

__콘텐츠 저장소 로드__::
+
플레이북에 나열된 콘텐츠 소스를 사용하여 Antora는 지정된 git 저장소 또는 로컬 콘텐츠 폴더를 로드하여 콘텐츠 파일을 스캔할 준비를 합니다.
+
각 원격 URL에 대해 Antora는 내장된 git 클라이언트를 사용하여 원격 git 저장소를 로컬 캐시로 복제합니다. 저장소가 이미 복제되어 있다면 Antora는 구성된 경우 업데이트를 가져옵니다.
+
마지막으로 Antora는 지정된 저장소에서 사용할 참조(브랜치, 태그 및 시작 경로)를 결정합니다.

__콘텐츠 소스 루트 찾기__::
콘텐츠 소스 루트에서 시작하여 Antora는 antora.yml이라는 구성 요소 버전 설명자 파일을 찾을 때 파일 그룹을 구성 요소 버전의 일부로 식별합니다. 이러한 소스 파일은 단일 저장소에 저장되거나 저장소의 루트 또는 하위 경로에 저장되거나 여러 저장소에 분산될 수 있습니다.

__입력 파일을 가상 파일 객체로 변환__::
Antora는 각 콘텐츠 소스 루트 하위 트리에서 모든 파일(텍스트, 이미지, 샘플 및 기타 지원 자료)을 수집합니다. 그런 다음 각 입력 파일의 가상 파일을 생성합니다.

__파일을 구성 요소 버전 버킷에 할당__::
+
Antora는 구성 요소 버전 설명자(antora.yml) 파일을 읽습니다.
+
구성 요소 버전 설명자는 그 아래의 파일을 지정된 구성 요소 이름 및 버전, 즉 구성 요소 버전과 연결합니다. 이를 통해 파일을 저장소에서 분리할 수 있으며 Antora의 URL에 구애받지 않는 교차 참조가 가능해집니다.
+
Antora는 설명자 정보와 기타 소스 메타데이터를 가상 파일에 할당합니다. 그런 다음 할당된 구성 요소 버전 데이터를 기반으로 각 파일을 가상 컬렉션으로 분류합니다.
+
구성 요소 버전은 일반적으로 프로젝트, 라이브러리, 서비스 또는 교육 과정에 대한 문서의 개별적이고 고유한 버전을 나타냅니다.

__추가 메타데이터 계산__::
플레이북의 사이트 속성과 이전 단계에서 파일에 할당된 정보를 사용하여 Antora는 각 파일에 모듈, 패밀리, 패밀리 상대 경로 및 기타 메타데이터 값을 추가합니다. 또한 게시 가능한 각 파일에 대한 출력 경로(디스크) 및 게시 경로(URL) 정보를 계산합니다.

__파일을 콘텐츠 카탈로그로 구성__::
Antora는 집계된 파일을 쿼리하고 전송할 수 있는 콘텐츠 카탈로그로 추가 분류합니다.

__AsciiDoc 파일을 삽입 가능한 HTML로 변환__::
콘텐츠 카탈로그의 페이지 패밀리에 있는 AsciiDoc 파일은 Asciidoctor.js를 사용하여 삽입 가능한 HTML로 변환됩니다.

__탐색 파일 변환__::
Antora는 콘텐츠 카탈로그에서 탐색 파일을 검색하고 그 내용을 지정된 계층 구조로 구성된 탐색 항목(탐색 메뉴 내의 탐색 트리)으로 변환한 다음 탐색 모델을 반환합니다.

__UI 번들 찾기 및 가져오기__::
Antora는 플레이북에 나열된 URL을 사용하여 UI 번들을 찾아 가져옵니다. UI 번들은 로컬에 캐시되거나 원격일 수 있습니다.

__UI 파일을 가상 파일 객체로 변환__::
Antora는 번들에서 UI 파일을 추출하고 파일의 내용과 경로 정보를 포함하는 각 파일에 대한 가상 파일 객체를 생성합니다.

__UI 파일 분류__::
Antora는 UI 설명자 파일(ui.yml)을 사용하여 정적 UI 파일을 식별하고 파일 유형을 정적으로 설정합니다. 다른 모든 파일의 유형은 위치(자산, 레이아웃, 헬퍼, 부분)에 따라 설정됩니다.

__UI 파일 출력 경로 계산__::
게시 가능한 각 UI 파일(정적 또는 자산 유형)에 대해 Antora는 출력 경로를 계산합니다.

UI 파일을 UI 카탈로그로 구성::
가상 UI 파일은 전송 가능한 컬렉션으로 분류됩니다.

__변환된 AsciiDoc 콘텐츠를 페이지 템플릿으로 감싸기__::
+
Antora는 각 페이지가 요청하는 페이지 템플릿을 결정합니다. 식별된 UI 템플릿에 페이지의 삽입 가능한 HTML, 사이트 메타데이터, 페이지, 버전 및 제품 선택기의 컨텍스트 데이터(구성 요소, 버전) 및 메뉴와 탐색 경로를 위한 탐색 모델 정보를 채웁니다.
+
페이지 템플릿을 사용하여 페이지를 생성하면 사이트 소유자가 페이지 구성을 완전히 제어할 수 있으며, 따라서 UI를 완전히 제어할 수 있습니다.

__사이트맵 생성__::
Antora는 내부 보고서로 사용하거나 사이트와 함께 게시할 수 있는 사이트맵을 생성합니다. 이 사이트맵은 구성 요소 이름별로 분할됩니다(사이트맵 인덱스 사용). 사이트맵 인덱스는 각 구성 요소 이름의 사이트맵에 링크되며, 여기서 개별 페이지의 URL을 찾을 수 있습니다.

__사이트 게시__::
+
Antora는 생성된 페이지를 기본 또는 사용자 지정 위치에 씁니다. 사이트는 내장 및 사용자 정의 대상 공급자를 사용하여 여러 프로토콜을 통해 여러 위치에 여러 형식으로 게시될 수 있습니다.

기본 사이트 생성기를 사용자 정의 생성기로 대체할 수 있습니다. 먼저 generateSite(args, env) 서명을 가진 함수를 내보내는 라이브러리나 스크립트를 만들어야 합니다. 해당 스크립트 내에서 Antora의 핵심 구성 요소를 자유롭게 가져와 자신만의 파이프라인을 재조립할 수 있습니다. 그런 다음 Antora CLI의 --generator 옵션에 라이브러리나 스크립트 이름을 전달하여 파이프라인을 활성화합니다.