= Antora 문서

[discrete.tagline]
=== 기술 작가를 위한 정적 사이트 생성기

이 사이트는 Antora의 기술 문서를 호스팅합니다. Antora를 사용하면 기술 작가가 쉽게 문서를 만들고 웹에 게시할 수 있습니다. 기술 작가로서 여러분은 Antora의 콘텐츠 마크업 언어인 AsciiDoc으로 콘텐츠를 작성하는 데 집중할 수 있습니다. 이러한 파일을 표준 프로젝트 구조로 구성하고 하나 이상의 콘텐츠 (git) 저장소에 저장합니다. Antora는 거기에서 콘텐츠를 가져와 웹사이트로 변환합니다. 그게 전부입니다!

== 코드로 문서 관리

Antora를 사용하면 코드로 문서를 관리할 수 있습니다. 즉, 문서 작성 프로세스는 성공적인 소프트웨어 제작에 사용되는 동일한 관행의 이점을 얻을 수 있습니다.
이러한 관행에는 다음이 포함됩니다:

- 버전 관리 시스템에 콘텐츠 저장.
- 콘텐츠, 구성 및 프레젠테이션 분리.
- 컴파일, 검증, 확인 및 게시를 위한 자동화 활용.
- 공유 자료 재사용 (DRY).

Antora는 이러한 관행을 문서화 워크플로에 통합하는 데 도움이 됩니다. 그 결과 문서를 훨씬 쉽게 관리, 유지 관리 및 향상시킬 수 있습니다.

== 시작하기

Antora를 처음 접하는 경우 Antora가 어떻게 도움이 될 수 있는지 알고 싶을 것입니다. 기본 개념에 익숙해지면 Antora 빠른 시작 가이드를 사용하여 Antora를 사용해 볼 수 있습니다.

새 문서 프로젝트를 설정하거나 기존 프로젝트를 Antora로 마이그레이션할 준비가 되었다면 Antora에서 예상하는 프로젝트 구조로 문서 파일을 구성하는 것부터 시작하세요. 그런 다음 Antora에 사이트에 사용할 문서 및 UI를 찾을 위치를 알려주는 플레이북을 만들어야 합니다.

이미 문서 구성 요소가 설정되어 있고 첫 번째 사이트를 만들 준비가 되었다면 Antora의 시스템 요구 사항을 충족하는지 확인한 후 Antora를 설치하고 마지막으로 antora 명령을 사용하여 사이트를 생성하세요.

AsciiDoc 구문을 사용하여 문서 페이지를 만드는 방법을 배우고 싶다면 IntelliJ AsciiDoc 플러그인이 작성자의 가장 친한 친구가 될 수 있습니다. AsciiDoc 콘텐츠 작성 및 미리 보기를 지원할 뿐만 아니라 Antora 구성 및 리소스 참조를 생성하고 검증하기 위한 최신 도구도 제공합니다.

사이트 생성기 파이프라인의 세부 사항을 더 자세히 알아보려면 Antora의 작동 방식을 확인하세요.

Antora로 문서 사이트를 만드는 것이 즐겁고 보람 있기를 바랍니다. 즐거운 글쓰기 되세요!
