== 민첩하고 안전함

*변경 사항이 발생할 때마다 CMS 거인과 씨름하는 대신 안전하고 민첩한 정적 사이트의 조립을 자동화합니다.*

어떤 변경에 대해서도 몇 초 만에 사이트를 자동으로 재구축하고 배포합니다. 배포된 CMS 애플리케이션에 보안 구멍을 패치해야 하는 걱정은 하지 마세요. 모든 페이지는 JAMstack 스타일로 정적입니다. 사이트를 다른 도메인으로 마이그레이션해야 하나요? 사이트를 재구축하고 새 호스트에서 다시 시작하기만 하면 됩니다. Antora는 단어의 가장 진실된 의미에서 정적인 사이트를 생성합니다. 사이트는 모든 웹 서버, 모든 도메인 또는 하위 도메인, 하위 폴더 내부 및 로컬 파일 시스템에서도 실행할 수 있습니다.

*사이트를 다른 웹 속성과 원활하게 맞추도록 조정합니다.*

어떤 사이트도 고립되어 있지 않습니다. 사이트는 일관된 브랜드와 사용자 경험을 유지하기 위해 다른 사이트와 잘 어울려야 합니다. Antora에서 생성한 정적 사이트는 이 역할에 적합합니다. 페이지 템플릿과 자동화된 프로세스의 도움으로 문서 페이지를 기존 사이트에 통합하여 단일 통합 사이트의 일부인 것처럼 보이게 할 수 있습니다.

== 이미 만들어진 협업 워크플로우 활용

*git 기반 CI 워크플로우를 사용하여 문서 변경, 기여 및 이니셔티브를 관리합니다.*

개발이 이루어지는 곳으로 가십시오. GitHub, GitLab, Bitbucket 또는 다른 코드 호스팅 서비스 중 어떤 것이든 이러한 플랫폼을 활용하여 코드로 문서를 개발할 수 있습니다. git 기반 CI 워크플로우는 협업 및 검토 도구를 무료로 제공할 뿐만 아니라 팀 간 협업을 장려합니다. 그 결과 문서는 소프트웨어 개발 프로세스의 일부가 됩니다. 그리고 그것은 더 많은 사람들이 문서 개선 노력을 지원할 준비가 되어 있다는 것을 의미합니다.

*기존 개발 인프라를 활용하여 팀과 권한을 관리합니다.*

소프트웨어 제품에는 이미 잘 정의된 팀, 권한 구조 및 기여자 커뮤니티가 있을 가능성이 높습니다. 동일한 조직을 사용하거나 이를 기반으로 문서 팀을 관리할 수 있습니다. 이러한 플랫폼은 활동을 모니터링하거나 특정 작업을 수행할 수 있는 액세스 권한을 부여하는 등 문서에 대한 관리 및 관리 인터페이스 역할을 할 수 있습니다.

== 간단한 플레이북에서 사이트 생성

*만들고 싶은 것을 설명하면 Antora가 거기에서 가져갑니다.*

Antora는 작가를 위해 먼저 만들어졌습니다. 작가는 쓰고 싶어하지 소프트웨어 재구성을 만지작거리고 싶어하지 않습니다. 바로 여기에서 Antora의 플레이북이 등장합니다. 플레이북은 생성하려는 사이트를 간결하게 설명하는 방법입니다. 이 설명은 a) 콘텐츠를 가져올 위치, b) 페이지에 적용할 UI, c) 게시할 위치로 요약됩니다. 이것이 Antora가 작업을 수행하기 위해 알아야 할 전부입니다. 추가 사용자 정의를 찾고 있는 경우에만 더 깊이 파고들 필요가 있습니다.

*오프라인 우선.*

Antora를 사용하여 생성된 사이트는 완전히 오프라인으로 볼 수 있습니다. 사이트의 모든 참조는 자체 포함되어 있으므로(즉, 상대적) 웹 서버를 실행하여 사이트를 볼 필요가 없습니다. 생성된 HTML 파일 중 하나를 브라우저에서 열기만 하면 UI에서 모든 페이지로 이동할 수 있습니다. 리디렉션은 기본적으로 오프라인에서도 작동합니다. 웹 서버를 사용할 수 있는 경우 추가 구성을 전달하여 Antora에게 해당 기능을 활용하도록 지시할 수 있습니다.

== 여러 리포지토리의 콘텐츠를 한데 모으기

*단일 빌드를 사용하여 리포지토리 경계와 브랜치에 걸쳐 있는 문서를 집계합니다.*

대부분의 사이트 생성기는 단일 리포지토리의 단일 브랜치로 제한됩니다. 반면에 Antora는 git을 말하는 방법을 알고 있습니다. 내장된 git 클라이언트를 사용하여 사이트에 필요한 모든 콘텐츠를 수집합니다. 그런 다음 파일을 구성 요소 버전으로 분리하여 파일을 정렬합니다. 이를 통해 조직에 가장 적합한 방식으로 문서를 저장할 수 있습니다. 콘텐츠를 코드와 함께 보관하든 별도의 리포지토리를 사용하든 상관없습니다. Antora는 모든 이질적인 프로젝트와 리포지토리를 수집하여 통합된 사이트를 만들 수 있습니다.

*콘텐츠를 선택하여 사이트를 수작업으로 제작합니다.*

사이트에 모든 것을 포함하고 싶지 않을 때가 있습니다. 때로는 제품이나 버전의 축소된 선택을 포함하는 "마이크로사이트"만 구축하고 싶을 때가 있습니다. 아니면 현재 작업 중인 제품의 문서를 미리 보기만 하면 될 수도 있습니다. 플레이북을 사용하면 어떤 소스에서 가져올지 조정하기만 하면 동일한 콘텐츠 소스에서 사이트의 여러 변형을 생성할 수 있습니다.

== 모든 버전 문서화

*각 제품 버전을 하나의 사이트의 일부로 구축합니다.*

소프트웨어가 버전 관리되기 때문에 소프트웨어에 대한 문서도 버전 관리가 필요합니다. 그렇지 않으면 사용자는 자신이 읽고 있는 문서가 소프트웨어의 어떤 버전을 다루는지 알 수 없습니다. 혼란이 뒤따릅니다. 소프트웨어와 마찬가지로 브랜치와 태그를 사용하여 문서의 버전을 관리할 수 있습니다. 이 콘텐츠는 소프트웨어 자체와 함께 저장할 수도 있습니다. Antora는 기꺼이 이 모든 콘텐츠를 수집하고 사용자가 단일 사이트에서 각 버전의 문서에 액세스할 수 있도록 구성합니다.

*다른 제품 버전을 탐색하거나 버전 간 페이지 사이를 탐색합니다.*

여러 버전의 문서를 사용할 수 있으므로 사용자는 해당 문서로 이동할 방법이 필요합니다. Antora는 문서 구성 요소 및 버전의 카탈로그를 제공하며 이는 메뉴로 독자에게 제공됩니다. 독자는 메뉴를 스캔하고 필요한 문서 버전으로 바로 이동할 수 있습니다. 또한 각 페이지는 버전 시퀀스의 일부로 자체 식별할 수 있으므로 사용자가 페이지의 이전 또는 최신 버전의 콘텐츠를 빠르게 방문할 수 있습니다.

== AsciiDoc: 최소 마크업, 최대 기능

*기술 문서에 특화된 직관적인 구문을 사용하여 가볍지만 포괄적으로 문서화합니다.*

문서를 작성할 때 마지막으로 방해받고 싶은 것은 마크업 구문입니다. 최상의 콘텐츠를 만들려면 작성 중인 내용을 볼 수 있어야 하지만 여전히 다양한 콘텐츠 유형을 적절하게 표현할 수 있어야 합니다. 바로 그것이 AsciiDoc이 제공하는 것입니다. 줄 지향적이고 왼쪽 정렬된 구문은 탐색하기 쉽고 의미론적 구조를 구축하기에 충분한 메타데이터를 적용할 수 있는 공간을 남깁니다. AsciiDoc은 문서 작성자의 가장 친한 친구입니다.

*재사용 가능한 속성, 포함 및 구문 확장을 사용하여 콘텐츠를 DRY로 유지합니다.*

이전에 입력한 내용을 입력할 때마다 효율성이 떨어지고 다른 내용을 도입할 위험이 있습니다. AsciiDoc은 반복하지 않도록 하는 여러 도구를 제공합니다. 속성을 사용하여 URL, 제품 이름 또는 정의를 여러 번 입력하지 않아도 됩니다. include를 사용하여 전체 단락, 섹션 및 기타 재사용 가능한 콘텐츠를 공통 파일로 추출할 수 있습니다. 그리고 이슈 트래커에 대한 참조와 같이 일반적으로 반복되는 패턴이나 방정식 및 차트와 같은 새로운 유형의 콘텐츠를 속기로 축소하기 위해 구문 확장을 도입할 수 있습니다.

*페이지는 모든 텍스트 편집기에서 편집할 수 있는 단순한 AsciiDoc 문서입니다.*

문서에서 페이지를 만드는 것은 AsciiDoc 문서를 만드는 것만큼 간단합니다. 문서는 텍스트 편집기에서 열어 미리 볼 수 있고 사이트의 컨텍스트에서 볼 수도 있습니다. Antora는 페이지에 암시적 ID를 할당하여 다른 페이지에서 참조할 수 있으며 해당 페이지의 암시적 ID를 사용하여 다른 페이지를 참조할 수 있습니다. 섹션 제목, 경고 블록 및 강조 표시된 소스 목록과 같은 기능은 적절하게 스타일이 지정됩니다.

== 소스 간 참조

*간결하고 쉽게 구성할 수 있는 소스 간 xref 시스템을 사용하여 페이지 및 기타 리소스 간의 참조를 만듭니다.*

생성된 파일 이름이나 URL에 의존하는 대신 소스 시스템의 대상 위치를 사용하여 페이지 및 기타 리소스 간의 참조를 만듭니다. 이렇게 하면 소스 파일의 위치만 고려하면 되고 처리 방식을 고려할 필요가 없기 때문에 참조에 대한 추론이 쉬워집니다. 즉, 소스 좌표계에 머무릅니다. 그리고 현재 소스 파일의 컨텍스트의 이점을 얻을 수 있으므로 현재 컨텍스트와 다른 대상의 특성만 지정하면 됩니다.

*소스 간 참조는 사이트를 파일 시스템 및 게시 환경에서 분리하는 데 필요한 정보를 제공합니다.*

리소스 ID를 사용하여 참조를 표현함으로써 Antora는 파일 시스템이나 게시 환경과 결합되지 않은 게시된 출력의 리소스에 대한 링크를 지능적으로 만들 수 있습니다. 즉, 생성된 사이트를 오프라인을 포함하여 어디에서나 볼 수 있습니다.

== 콘텐츠로서의 탐색

*AsciiDoc 목록을 사용하여 문서 탐색을 설명합니다.*

Antora를 사용하는 작성자는 탐색을 정의할 때 바로 집에 있는 것처럼 느낄 수 있습니다. 이유는? 페이지와 마찬가지로 탐색도 단순히 또 다른 AsciiDoc 문서이기 때문입니다. 그러나 자유 형식 콘텐츠 대신 탐색 파일에는 탐색 메뉴 사이드바에서 볼 수 있는 탐색 트리로 변환되는 목록 계층이 포함되어 있습니다. 또 다른 탐색 트리를 추가하려면 추가 목록을 추가하기만 하면 됩니다.

*기본 콘텐츠에 사용되는 것과 동일한 xref 시스템을 사용하여 탐색 링크를 만듭니다.*

그렇다면 탐색에서 페이지에 대한 링크를 어떻게 만들까요? 물론 xref를 사용합니다. 탐색 파일은 단순히 콘텐츠이기 때문에 페이지 간 링크를 만들기 위해 기본 콘텐츠에서 사용하는 것과 동일한 xref 시스템을 사용할 수 있습니다. 탐색 파일을 게시되지 않는 페이지로 생각하십시오. 그리고 파일이 콘텐츠와 함께 저장되기 때문에 xref는 컨텍스트에 맞을 수 있습니다. 즉, 현재 컨텍스트와 다른 대상의 특성만 지정하면 됩니다.

== 상호 교환 가능한 UI

*사이트의 사용자 인터페이스와 테마는 콘텐츠와 별개로 유지 관리됩니다.*

Antora의 주요 주제는 콘텐츠와 프레젠테이션의 분리입니다. 이것은 UI에서 두드러지게 나타납니다. Antora는 별도의 프로젝트로 저장되고 관리되는 사이트 UI와 인터페이스합니다. UI 모델을 UI에서 제공한 Handlebars 템플릿에 전달합니다. 그런 다음 템플릿은 모델에서 무엇을 표시할지 결정하여 UI에 페이지 레이아웃에 대한 완전한 제어 권한을 부여합니다. 템플릿은 또한 포함할 CSS와 JavaScript를 결정합니다.

*콘텐츠와 독립적으로 UI를 반복합니다*

UI와 콘텐츠가 별도로 유지 관리되기 때문에 서로 다른 릴리스 주기를 따를 수 있습니다. 그리고 아무도 발을 디디지 않습니다. UI에서 수행된 작업은 콘텐츠에서 수행된 작업을 방해하지 않습니다. Antora가 실행될 때 최신 콘텐츠와 최신 UI를 함께 융합합니다. 이것은 UI와 테마를 다른 것으로 쉽게 교체할 수 있음을 의미하며, 이는 재설계, A/B 테스트 또는 캠페인에 유용할 수 있습니다. 필요에 따라 UI와 테마를 조정할 수 있는 최대한의 자유가 있습니다.

== 페이지 리디렉션에 대한 기본 제공 지원

*대상 문서에 정보를 저장하는 투명한 방식으로 이전 페이지의 URL을 유지합니다.*

변화는 일어납니다. 그냥 그것을 처리할 준비가 되어 있어야 합니다. 문서 사이트에서 가장 자주 변경되는 사항 중 하나는 페이지 이름이 바뀌거나 재구성됨에 따라 변경되는 페이지의 URL입니다. Antora는 페이지 별칭을 선언하여 이전 페이지의 URL을 유지할 수 있는 방법을 제공합니다. Antora의 다른 기능과 마찬가지로 이 정보는 이 경우 대상 AsciiDoc 문서의 헤더에 콘텐츠와 함께 저장됩니다.

*리디렉션은 단순히 인바운드 xref인 별칭을 사용하여 설명됩니다. URL과 결합되지 않습니다.*

예상하셨겠지만 페이지 별칭은 소스 참조입니다. 이를 통해 Antora는 올바른 URL에서 리디렉션을 생성하는 것을 처리할 수 있습니다. 모든 호스팅 환경이 동일하지는 않기 때문에 리디렉션을 수행하는 기능도 동일하지 않습니다. Antora는 호스팅 환경에서 제공하는 리디렉션 기능에 적합한 구성을 생성하고, 다른 메커니즘이 지원되지 않는 경우 기존의 정적 바운스 페이지로 대체합니다.

== 여러 대상으로 사이트 게시

*로컬이든 원격이든 어디에서나 게시하세요.*

사이트는 게시되기 위해 만들어졌습니다. Antora는 그것을 도와줍니다. 대상이 로컬이든 원격이든 Antora는 내장 또는 사용자 정의 공급자를 사용하여 콘텐츠를 해당 위치로 스트리밍합니다. 그럼에도 불구하고 사이트가 게시되는 위치에 관계없이 사이트는 호스트 환경과 연결되지 않습니다. Antora는 원하는 만큼 많은 출력 스트림을 지원합니다. 로컬 디렉터리, 로컬 아카이브, 원격 SSH 서버의 디렉터리 또는 S3와 같은 웹 서비스 엔드포인트 또는 대상의 조합일 수 있습니다. Antora가 게시를 위해 파일을 필요한 위치로 보내는지 확신할 수 있습니다. 모두 단일 빌드에서 이루어집니다.

*파이프라인에 별도의 단계, 도구 또는 스크립트가 필요하지 않습니다.*

Antora의 파일 게시자는 파이프라인에서 한 단계를 줄여줍니다. 대부분의 사이트 생성기는 출력을 로컬 디렉터리에 작성한 다음 다시 돌아가 게시해야 합니다. Antora는 출력을 지정한 대상으로 직접 보냅니다. 그리고 사이트의 참조가 게시 환경과 연결되어 있지 않기 때문에 로컬 디렉터리에 게시하여 오프라인에서도 사이트를 미리 볼 수 있습니다.

== 합리적인 기본값. 개방형 아키텍처

*기본값으로 시작하세요.*

Antora는 즉시 사용할 수 있는 독단적인 사이트 생성기와 UI를 제공하므로 빠르게 시작하고 실행할 수 있습니다. antora CLI 명령을 사용하여 사이트 생성기와 인터페이스합니다. 이 명령은 직접 설치하거나 Docker 컨테이너를 사용하여 호출할 수 있습니다. 플레이북을 가리키기만 하면 Antora가 다중 구성 요소, 다중 버전 문서 사이트를 제공합니다. Antora와 함께 사용할 문서를 설정하거나 마이그레이션할 기회가 있으면 기본값에서 졸업하여 고급 요구 사항에 맞게 Antora를 조정할 수 있습니다.

*Antora를 맞춤 설정하세요.*

Antora는 개방형 아키텍처를 갖추고 있습니다. 그것이 무엇을 의미합니까? 즉, Antora에 새로운 트릭을 가르칠 수 있는 능력이 있다는 것을 의미합니다. 아마도 Antora의 카탈로그에 추가 콘텐츠를 통합해야 할 수도 있습니다. 아니면 중간에 사용자 지정 처리를 수행하고 싶을 수도 있습니다. 심지어 필요에 맞게 Antora를 재구성하기 위해 자체 동작을 도입할 수도 있습니다. 제공된 사이트 생성기가 적합하지 않을 때 Antora를 기반으로 사용할 수 있도록 설계되었습니다.
