= Antora 릴리스 일정

각 Antora 핵심 구성 요소의 주요 릴리스 라인은 일반적으로 일반 가용성(General Availability, GA) 상태에 진입한 후 1년 동안 지원됩니다.

[cols=6*]
|===
|릴리스 라인 |최신 릴리스 |상태 |GA |유지보수 |EOL

|Antora 3
|3.1.9
|활성
|2021/12/25
|미정
|미정

|Antora 2
|2.3.4
|EOL
|2018/12/25
|2022/01/25
|2022/02/25
|===

일반 가용성 (General Availability, GA):: 
릴리스 라인(예: Antora 2.x)은 초기 최종 주 버전(예: Antora 2.0.0)의 소프트웨어가 릴리스되어 다운로드할 수 있게 되는 날짜에 일반 가용성 상태에 진입합니다.

활성:: 
릴리스 라인이 적극적으로 개선되고 지원되고 있습니다.

유지보수:: 
릴리스 라인이 유지보수 기간에 진입하면 가장 최근의 부 버전만 중요 보안 패치 릴리스를 받게 됩니다. 릴리스 라인은 다음 주 릴리스 라인이 GA 상태가 된 후 30일 후에 이 단계를 시작합니다.

수명 종료 (EOL):: 
이 날짜 이후에는 릴리스 라인이 더 이상 지원을 받거나 릴리스되지 않습니다.

== 버전 정책

Antora는 시맨틱 버저닝 규칙을 따릅니다. 각 Antora 구성 요소 릴리스는 **주.부.패치** 버전으로 지정됩니다.

주 버전::
주 릴리스는 기능에 상당한 변경이 있거나 새로운 기능이 이전 버전과의 호환성을 깨뜨릴 때 발생합니다. 동일한 주 릴리스 라인 내의 릴리스는 API 호환성을 유지합니다.

부 버전::
부 릴리스는 새로운 기능, 기존 기능의 개선, 그리고 이전 버전과의 호환성을 유지하는 수정 사항을 추가합니다.

패치 버전::
패치 릴리스는 버그를 수정하고 이전 버전과의 호환성을 유지합니다. 주 릴리스 라인의 최신 부 릴리스만 패치를 받게 됩니다. 패치 릴리스는 수정의 긴급성에 따라 필요에 따라 이루어집니다.

프리릴리스::
주 및 부 릴리스에는 프리릴리스 버전(주.부.패치-알파.n | -베타.n | -rc.n)이 포함될 수 있습니다. 프리릴리스 버전은 'next'로 태그가 지정되어 npm 클라이언트가 안정 버전보다 프리릴리스를 선호하지 않도록 합니다. 릴리스 후보(rc)가 철저히 테스트되면 안정 릴리스가 게시됩니다.

== 로드맵

현재 예정된 개발 작업 목록은 Antora의 마일스톤과 이슈 트래커를 참조하세요. 마일스톤은 정보 제공 목적으로만 사용됩니다. 제안된 기능, 그 범위, 그리고 릴리스 일정은 추정치이며 확정된 약속이 아닙니다.