= 모듈 디렉터리 및 모듈

== modules 디렉터리란?

__modules__ 디렉터리는 구성 요소 버전 설명자 파일(__antora.yml__)이 위치한 곳이면 어디에나 필요합니다.

[source]
----
📒 repository <1>
  📄 antora.yml <2>
  📁 modules <3>
  📁 non-docs-directory <4>
----
<1> 콘텐츠 소스 루트 
<2> 필수 구성 요소 버전 설명자 파일 
<3> 필수 __modules__ 디렉터리 
<4> Antora는 __modules__ 디렉터리 외부에 있기 때문에 이 디렉터리의 파일을 처리하지 않습니다.

__antora.yml__을 제외하고 표준 디렉터리와 해당 파일은 __modules__ 디렉터리에 유효한 계층 구조로 있어야 합니다. __modules__ 디렉터리에는 필요한 만큼 많은 모듈 디렉터리가 포함될 수 있습니다.

__modules__ 디렉터리는 문서 소스 파일을 구성 파일, 스크립트, 애플리케이션 코드, 테스트 및 콘텐츠 소스 루트에 있는 기타 자료와 분리하여 유지합니다.

== module 디렉터리란?

모듈 디렉터리는 __modules__ 디렉터리에 저장해야 합니다. 모듈 디렉터리는 페이지, 재사용 가능한 텍스트 및 예제 코드 조각, 이미지 및 기타 콘텐츠의 소스 파일을 제품군 디렉터리에 저장합니다. 모듈 디렉터리에 저장된 소스 파일은 구성 요소 버전의 모듈 일부가 됩니다.

[source]
----
📒 repository
  📂 docs <1>
    📄 antora.yml
    📂 modules
      📂 named-module <2>
        📂 pages <3>
          📄 page-source-file.adoc <4>
      📄 nav.adoc <5>
----
<1> 콘텐츠 소스 루트 
<2> 명명된 모듈 디렉터리 
<3> pages 그룹 디렉터리 
<4> 페이지의 소스 파일 
<5> 탐색 파일

모듈 디렉터리에는 최소한 하나 이상의 소스 파일이 있는 제품군 디렉터리가 하나 이상 포함되어야 합니다. 모듈 디렉터리에는 0개 이상의 탐색 파일도 포함될 수 있습니다.
모듈 디렉터리에는 명명된 모듈 디렉터리와 ROOT 모듈 디렉터리의 두 가지 유형이 있습니다. 런타임에 Antora는 ROOT 및 명명된 모듈 디렉터리에 저장된 소스 파일을 수집하여 모듈에 할당합니다. 규칙에 따라 모듈 이름은 모듈 폴더의 이름에 해당합니다.

== 모듈이란?

모듈은 개념, 단계, 기능 또는 기타 프로젝트별 그룹화와 관련된 구성 요소 버전의 콘텐츠 모음입니다. 모듈은 게시된 사이트의 URL 세그먼트로 표시되지만 주로 작성자를 위한 구성 도구입니다. 모듈은 개별적으로 구성할 수 없습니다(즉, 자체 메타데이터가 없음).

**모듈 이름**과 모듈 폴더의 이름은 동일합니다. Antora는 모듈의 폴더 내에서 발견된 모든 파일에 모듈 이름을 할당합니다.