= 명명된 모듈 디렉터리

== 이름이 지정된 모듈 디렉터리란?

이름이 지정된 모듈 디렉터리는 __modules__ 디렉터리에 위치한 선택적인 모듈 디렉터리입니다. 필요한 만큼 이름이 지정된 모듈 디렉터리를 만들 수 있습니다.

.예제 1. 이름이 지정된 모듈 디렉터리
[source]
----
📒 repository
  📂 docs <1>
    📄 antora.yml <2>
    📂 modules <3>
      📂 bears <4>
        📂 pages <5>
          📄 page-source-file.adoc <6>
        📄 nav.adoc <7>
      📂 get-started <8>
        📂 pages
          📄 page-source-file.adoc
----
<1> 콘텐츠 소스 루트
<2> 필수 __antora.yml__ 파일
<3> 필수 __modules__ 디렉터리
<4> __bears__라는 이름의 모듈 디렉터리
<5> __pages__ 패밀리 디렉터리
<6> 페이지를 위한 소스 파일
<7> 내비게이션 파일
<8> __get-started__라는 이름의 모듈 디렉터리

이름이 지정된 모듈 디렉터리는 적어도 하나 이상의 소스 파일이 포함된 하나 이상의 패밀리 디렉터리를 포함해야 합니다. 이름이 지정된 모듈 디렉터리는 선택적으로 내비게이션 파일을 포함할 수도 있습니다.

Antora는 모듈의 디렉터리 이름을 사용하여 모듈의 이름을 만듭니다. 모듈 이름은 소스 간 참조에 사용되며 모듈에 속한 게시 가능한 리소스의 URL 세그먼트로 사용됩니다. 따라서 모듈 디렉터리의 이름은:

- 콘텐츠 작성자에게 접근 가능해야 합니다
- AsciiDoc 매크로 및 지시문에서 허용되지 않는 문자를 포함할 수 없습니다
- 웹 서버 이식성, 검색 엔진 최적화 또는 사이트 검색 솔루션의 모범 사례를 저해하는 문자를 포함하지 않아야 합니다
- 사이트의 접근성 요구사항을 충족해야 합니다

위에 나열된 이유로 인해 이름이 지정된 모듈 디렉터리의 이름을 신중하게 고려하는 것이 중요합니다. 금지된 문자와 권장되는 방식에 대해 알아보려면 모듈 디렉터리 이름에 대한 권장 사항을 참조하세요.

== 이름이 지정된 모듈이란?

각 이름이 지정된 모듈 디렉터리의 소스 파일은 컴포넌트 버전의 이름이 지정된 모듈의 일부가 됩니다. 모듈의 이름은 모듈 디렉터리의 이름과 일치합니다. 예를 들어, 예제 1에 표시된 __get-started__ 모듈 디렉터리에 저장된 소스 파일은 get-started 모듈에 할당됩니다.
