= 페이지(Pages) 디렉터리 및 파일

== Pages 패밀리 디렉터리

모듈 디렉터리에는 __pages__라는 이름의 패밀리 디렉터리가 포함될 수 있습니다. __pages__ 디렉터리에는 하위 디렉터리가 포함될 수 있습니다. Antora는 실행 시 페이지 파일에 사전 설정된 동작을 적용하므로 __pages__ 디렉터리와 하위 디렉터리에는 파일 확장자가 __.adoc__인 AsciiDoc 소스 파일만 저장해야 합니다.

[source]
----
📂 modules
  📂 named-module <1>
    📂 pages <2>
      📄 page-source-file.adoc <3>
      📂 subdirectory-of-pages <4>
        📄 page-source-file.adoc
  📂 ROOT <5>
    📂 pages <6>
      📄 page-source-file.adoc
    📄 nav.adoc
----

<1> 이름이 지정된 모듈 디렉터리.
<2> __pages__ 패밀리 디렉터리. __pages__에 저장된 소스 파일은 페이지로 분류됩니다.
<3> AsciiDoc 구문으로 마크업되고 유효한 __.adoc__ 파일 확장자로 저장된 페이지 파일.
<4> __pages__의 하위 디렉터리. __pages__ 디렉터리의 하위 디렉터리에 저장된 소스 파일은 페이지로 분류됩니다.
<5> __ROOT__ 모듈 디렉터리.
<6> __pages__ 패밀리 디렉터리.

__pages__ 디렉터리는 선택 사항입니다. 즉, 모듈에 페이지 파일이 없으면 모듈에 __pages__ 디렉터리를 만들지 마세요. __pages__ 디렉터리를 설정하는 경우 __pages__ 디렉터리 또는 __pages__의 하위 디렉터리에는 최소한 하나의 AsciiDoc 소스 파일이 포함되어야 합니다.

== 페이지 파일

Antora는 __pages__ 디렉터리에 저장된 소스 파일을 페이지로 분류합니다. 페이지는 제목이 있는 개별 문서로 구성되며, AsciiDoc 구문을 사용하여 마크업되고 ___.adoc___ 파일 확장자로 저장됩니다. 페이지의 리소스 ID를 사용하여 사이트의 다른 페이지, 리소스 또는 내비게이션 파일에서 페이지를 상호 참조하거나 사이트의 다른 페이지 또는 리소스에 페이지를 포함할 수 있습니다.

페이지 파일은 숨겨지거나 게시되지 않는 것으로 표시되지 않는 한 게시 가능한 리소스입니다. 즉, 페이지가 다른 리소스 또는 내비게이션 파일에서 참조되지 않더라도 Antora는 각 페이지를 자동으로 HTML로 변환하고 사이트의 개별 페이지로 게시합니다. Antora는 페이지의 URL을 빌드할 때 __pages__ 상대 디렉터리 경로(있는 경우), 페이지의 파일 이름 및 지정된 HTML 확장자 스타일을 사용합니다.
