= 파셜(Partials) 디렉터리 및 파일

== Partials 패밀리 디렉터리

모듈 디렉터리에는 __partials__라는 이름의 패밀리 디렉터리가 포함될 수 있습니다.

[source]
----
📂 modules
  📂 ROOT <1>
    📁 images
    📁 pages
    📂 partials <2>
      📄 partial-source-file.adoc <3>
    📄 nav.adoc
  📂 named-module <4>
    📁 pages
    📂 partials <5>
      📄 partial-source-file.adoc
      📂 subdirectory-of-partials <6>
        📄 partial-source-file.adoc
----

<1> ROOT 모듈 디렉터리. 
<2> __partials__ 패밀리 디렉터리. Antora는 __partials__ 디렉터리에 저장된 소스 파일을 __partials__로 분류합니다. 
<3> AsciiDoc 구문으로 마크업되고 __.adoc__ 파일 확장자로 저장된 __partial__ 파일.
<4> 이름이 지정된 모듈 디렉터리. 
<5> __partials__ 패밀리 디렉터리. 
<6> __partials__의 하위 디렉터리. __partials__ 디렉터리의 하위 디렉터리에 저장된 소스 파일은 __partials__로 분류됩니다. 

__partials__ 디렉터리는 선택 사항입니다. Antora는 사이트를 생성할 때 __partials__ 디렉터리에 저장된 소스 파일에 사전 설정된 동작을 적용합니다.

== Partial 파일

Antora는 __partials__ 디렉터리에 저장된 소스 파일을 partial 파일 또는 줄여서 partials로 분류합니다. Partials는 일반적으로 공통 설명이나 용어와 같은 콘텐츠 스니펫을 포함하는 AsciiDoc 파일로, 하나 이상의 페이지나 partials에 삽입됩니다. 그러나 Antora는 partials가 AsciiDoc 파일일 것을 요구하지 않습니다.

새 partial 파일을 저장할 때는 다음 파일 이름 요구 사항과 권장 사항을 염두에 두세요:

- AsciiDoc include 지시문은 공백이 포함된 값을 허용하지 않으므로 partial의 파일 이름에는 **공백이 포함될 수 없습니다**.
- **파일 이름에는 대문자가 권장되지 않습니다**. 일부 파일 시스템은 대소문자를 구분하지 않습니다. 따라서 작성자가 사용하는 파일 시스템에 따라 파일 충돌이 발생할 수 있습니다.
- AsciiDoc 파일인 경우 __.adoc__ 확장자로 partial 파일을 저장하고, 그렇지 않으면 파일 유형에 유효한 파일 확장자를 사용하세요. 특정 파일 유형에 확장자가 없는 것이 일반적인 관행인 경우에만 partial을 파일 확장자 없이 저장해야 합니다. partial 파일을 저장할 때 올바른 파일 확장자를 사용하지 않으면 일부 Antora 확장을 적용하거나 향후 기능으로 업그레이드하는 기능이 제한될 수 있습니다.

partial에는 파일 확장자가 필요하지 않습니다. 파일 확장자가 없는 경우 숨김 파일로 처리되는 게시 가능한 리소스와 달리 Antora는 파일 확장자가 없는 partial을 콘텐츠 카탈로그에 로드하고 참조를 위해 partial에 리소스 ID를 할당합니다.

Antora는 partial 파일을 개별 사이트 페이지로 게시하지 않습니다. partial의 콘텐츠를 게시하려면 페이지 또는 결국 페이지에 포함되는 리소스의 include 지시문에서 partial을 참조해야 합니다.

IMPORTANT: 파일 유형에 파일 확장자가 없는 것이 일반적인 경우를 제외하고는 partial 소스 파일을 유효한 파일 확장자로 저장하는 것이 좋습니다.

== 더 알아보기

- Partials
- Include a Partial