= 권장하는 모듈 디렉터리 이름

모듈 디렉터리를 만들 때는 팀이 그 안에 저장된 파일을 어떻게 사용할 것인지, 그리고 그 이름이 사이트의 URL에 어떤 영향을 미칠 것인지 고려해야 합니다.

== 모듈 폴더 이름 선택

Antora는 모듈 폴더의 이름에서 모듈의 이름을 할당합니다. 모듈 이름은 페이지, 이미지, 첨부 파일, 예제 및 부분의 리소스 ID에서 모듈 좌표로 사용됩니다. 또한 해당 모듈에 할당된 게시 가능한 리소스의 URL에도 사용됩니다(__ROOT__ 모듈 제외).

모듈 폴더 이름을 선택할 때는 다음 요구 사항과 권장 사항을 염두에 두세요:

- 이름이 지정된 모듈 디렉터리는 **공백이나 슬래시(/)를 포함할 수 없습니다**. 이러한 문자는 AsciiDoc 상호 참조, 이미지 매크로 또는 포함 지시문의 대상에서 허용되지 않습니다.
- 가능하다면 **대문자, 밑줄(_) 및 URL에 권장되지 않는 기타 문자를 사용하지 마세요**. 이러한 문자는 웹 서버 이식성을 제한하고 사이트 검색 결과를 저하시키며 방문자 접근성 문제를 일으킬 수 있습니다.
- 모듈 이름이 link와 같은 내장 매크로의 이름으로 끝나는 경우, 해당 이름의 일부분은 xref 매크로에서 사용할 때 이스케이프 처리해야 할 수 있습니다. 예를 들어, elink는 AsciiDoc 파서가 link 매크로를 보지 못하도록 e\link로 작성해야 합니다.
- 팀이 모듈 간에 자주 리소스를 참조하는 경우, 리소스 ID에 모듈의 이름을 입력해야 하므로 **폴더 이름, 즉 모듈 이름을 너무 길거나 기억하기 어렵게 만들지 마세요**. 좋은 모듈 이름은 짧고 설명적입니다.

예제 1은 세 개의 이름이 지정된 모듈 디렉터리가 있는 표준 디렉터리 세트를 보여줍니다.

.예제 1. 세 개의 이름이 지정된 모듈 디렉터리
[source]
----
📒 repository
  📂 docs
  📄 antora.yml
  📂 modules
    📂 gear <1>
      📂 images
        📄 image-source-file.ext
    📂 la-garita <2>
      📂 pages
        📄 page-source-file.adoc
    📂 ROOT <3>
      📂 pages
        📄 page-source-file.adoc
      📄 nav.adoc
    📂 sdk <4>
      📂 examples
        📄 example-source-file.ext
      📂 pages
        📄 page-source-file.adoc
      📄 nav.adoc
----
<1> __gear__라는 이름의 모듈 디렉터리
<2> __la-garita__라는 이름의 모듈 디렉터리
<3> __ROOT__ 모듈 디렉터리
<4> __sdk__라는 이름의 모듈 디렉터리

Antora는 예제 1의 이름이 지정된 모듈 디렉터리에서 gear, la-garita 및 sdk라는 모듈 이름을 계산할 것입니다.
