= 저장소 및 콘텐츠 소스 루트

Antora는 git 리포지토리의 분기, 태그 및 작업 트리에 있는 디렉터리에서 콘텐츠 소스 파일을 수집합니다. 이러한 소스 파일은 Antora가 콘텐츠 소스 루트 내에서 해당 파일을 찾을 수 있는 경우에만 올바르게 검색 및 처리됩니다.

== git 리포지토리 및 콘텐츠 소스

사이트 콘텐츠가 포함된 소스 파일은 하나 이상의 git 리포지토리에 저장됩니다. 이러한 리포지토리는 원격, 로컬 또는 둘의 조합일 수 있습니다. 플레이북 파일에서 다음과 같은 여러 매개변수(예: url, branches, tags 및 start paths)를 입력합니다:

. Antora가 콘텐츠 소스 리포지토리를 찾아 연결할 수 있도록 하고,
. git 리포지토리 내에서 하나 이상의 콘텐츠 소스 루트로 해석되는 위치 기준을 Antora에 제공합니다.

리포지토리가 로컬인 경우 기본적으로 Antora는 현재 분기가 콘텐츠 소스에 정의된 분기 중 하나와 일치하면 해당 리포지토리의 작업 트리를 사용하려고 시도합니다. 이 동작은 구성 가능합니다.

Antora는 로컬 디렉터리가 git 리포지토리여야 합니다. 즉, 로컬 디렉터리가 git 작업 트리입니다. git 리포지토리 자체는 비어 있을 수 있습니다. 즉, 작동하려면 파일을 커밋할 필요가 없습니다. 로컬 디렉터리가 아직 git 리포지토리가 아닌 경우 다음 명령을 실행하여 git 리포지토리로 만들 수 있습니다:

[source,console]
----
$ git init . && git commit --allow-empty -m init
----

사이트의 플레이북을 구성하기 전에 리포지토리에서 콘텐츠 소스 루트를 설정할 위치를 결정해야 합니다.

== 콘텐츠 소스 루트란?

**콘텐츠 소스 루트**는 Antora가 콘텐츠 소스 파일을 찾기 시작하는 리포지토리의 분기 또는 태그(즉, 참조)에 있는 위치입니다. 콘텐츠 소스 루트를 Antora가 쇼핑하는 상점의 입구로 생각하세요. 콘텐츠 소스 루트에서 Antora는 구성 요소 버전 버킷을 식별하는 __antora.yml__ 파일을 찾은 다음 해당 버킷에 추가할 표준 디렉터리 세트로 구성된 소스 파일 모음을 검색합니다.

리포지토리에는 많은 콘텐츠 소스 루트가 있을 수 있습니다. 분기 또는 태그당 하나의 콘텐츠 소스 루트가 있을 수 있습니다. 또는 여러 시작 경로를 사용하여 정의된 분기 또는 태그당 여러 콘텐츠 소스 루트가 있을 수 있습니다. 둘의 조합을 가질 수도 있습니다. 콘텐츠 소스 루트를 저장하는 위치는 사용자에게 달려 있습니다.