= ROOT 모듈 디렉터리

== ROOT 모듈 디렉터리란?

__ROOT__ 디렉터리는 선택적인 모듈 디렉터리입니다. __ROOT__ 모듈 디렉터리는 __modules__ 디렉터리에 위치하며, 이름은 모두 대문자로 작성되어야 합니다. __ROOT__ 디렉터리는 하나 이상의 패밀리 디렉터리에 콘텐츠 소스 파일을 저장합니다.

[source]
----
📒 repository
  📂 docs <1>
    📄 antora.yml <2>
    📂 modules <3>
      📂 ROOT <4>
        📂 pages <5>
          📄 index.adoc <6>
          📄 another-page.adoc <7>
        📄 nav.adoc <8> 
----
<1> 콘텐츠 소스
<2> 필수 __antora.yml__ 파일
<3> 필수 __modules__ 디렉터리
<4> __ROOT__ 모듈 디렉터리
<5> __pages__ 그룹 디렉터리
<6> 기본 컴포넌트 버전 시작 페이지를 위한 소스 파일
<7> ROOT 모듈의 다른 페이지를 위한 소스 파일
<8> 내비게이션 파일

__ROOT__ 모듈 디렉터리가 존재하는 경우, 적어도 하나 이상의 소스 파일이 포함된 하나 이상의 패밀리 디렉터리를 포함해야 합니다. 선택적으로 내비게이션 파일을 포함할 수도 있습니다.

__ROOT__ 디렉터리에 저장된 소스 파일은 컴포넌트 버전의 __ROOT__ 모듈의 일부가 됩니다. __ROOT__ 모듈 디렉터리를 생성하는 것이 좋습니다. 왜냐하면 Antora는 __ROOT__ 모듈의 게시 가능한 리소스에 특별한 사전 설정 동작을 적용하기 때문입니다. 예를 들어, __pages__ 디렉터리의 __index.adoc__ 소스 파일은 컴포넌트 버전의 기본 시작 페이지가 됩니다. HTML 웹 호스팅 용어에 익숙한 사람들은 이를 컴포넌트 버전의 인덱스 페이지로 인식할 것입니다.

작은 문서 프로젝트는 __ROOT__ 모듈 디렉터리만으로도 충분할 수 있습니다. 그러나 프로젝트가 커짐에 따라 더 많은 모듈 디렉터리를 쉽게 추가하고 소스 파일을 점진적으로 재구성할 수 있습니다. 지금은 추가 구조가 과한 것처럼 보일 수 있지만, 장기적으로는 콘텐츠가 성장할 수 있는 공간을 제공한 것에 대해 기뻐할 것입니다.

== ROOT 모듈이란?

__ROOT__ 디렉터리에 저장된 소스 파일은 컴포넌트 버전의 __ROOT__라는 이름의 모듈의 일부가 됩니다. __ROOT__ 모듈의 페이지는 컴포넌트 버전의 최상위 페이지가 됩니다. 즉, 다른 모듈과 달리 __ROOT__ 모듈의 이름은 생성된 사이트에서 사용되지 않습니다.

"ROOT"라는 이름을 빈 모듈 이름(즉, 모듈 세그먼트 없음)의 별칭으로 생각할 수 있습니다. 이 특별한 값을 사용하면 모든 모듈이 형제가 될 수 있습니다.

__ROOT__ 모듈 디렉터리에 저장하는 파일을 신중하게 고려하는 것이 중요합니다. 이름이 지정된 모듈 디렉터리의 파일과 충돌할 가능성이 있기 때문입니다. 일반적으로 __ROOT__ 모듈은 이러한 이유로 토픽 폴더를 사용하지 않습니다.

== ROOT 모듈 이름은 어디에 사용되나요?

다른 모듈이나 컴포넌트 버전에서 __ROOT__ 모듈에 속한 콘텐츠를 참조할 때, 페이지, 첨부 파일, 이미지, 예제 및 부분에 대한 리소스 ID에 모듈 이름 __ROOT__를 지정합니다. ROOT는 지정될 때 항상 대문자로 작성됩니다.

Antora는 __ROOT__ 모듈의 페이지를 최상위 컴포넌트 버전 페이지로 간주하므로, 모듈 이름 __ROOT__는 페이지 URL의 모듈 세그먼트에 표시되지 않습니다.
