= 표준 파일 및 폴더 세트

Antora는 콘텐츠 소스 루트에서 찾을 것으로 예상되는 일련의 계층적 파일 및 폴더에 따라 콘텐츠 소스 파일을 수집하고 처리합니다. 이 페이지에서는 이 계층 구조, 사용되는 예약된 폴더 및 파일 이름, 그리고 수집되거나 무시되는 파일에 대한 규칙을 소개합니다.

== 계층 구조 및 예약된 이름

콘텐츠 소스 루트에서 시작하는 파일 및 폴더 세트, 예약된 파일 및 폴더 이름, 그리고 해당 계층 구조(총칭하여 Antora의 **표준 파일 및 폴더 세트**라고 함)는 Antora가 수집할 파일, 각 파일의 역할, 각 파일을 분류하는 방법 및 무시할 파일을 결정하는 데 도움이 됩니다. 예제 1은 표준 파일 및 폴더 세트를 구성하는 모든 필수 및 선택적 파일과 폴더가 사용되는 경우 Antora가 예상하는 계층 구조를 보여줍니다.

NOTE: 다음 예제에서 📒 **repository**는 git 저장소의 분기와 같은 단일 참조의 파일 트리 루트를 나타냅니다.

.예제 1. 저장소 루트에 있는 표준 파일 및 폴더 세트의 모든 필수 및 선택적 파일 및 폴더
[source]
----
📒 repository <1>
  📄 antora.yml <2>
  📂 modules <3>
    📂 ROOT <4>
      📁 attachments <5>
      📁 examples <6>
      📁 images <7>
      📁 pages <8>
      📁 partials <9>
      📄 nav.adoc <10>
    📂 named-module <11>
      📁 pages 
      📄 nav.adoc <12>
  📁 packages <13>
----
<1> 저장소 루트이자 콘텐츠 소스 루트입니다. 기본적으로 Antora는 사이트의 플레이북에서 콘텐츠 소스에 start_path 또는 start_paths 키가 값으로 할당되지 않는 한 콘텐츠 소스 루트가 저장소의 루트에 있다고 가정합니다.
<2> __antora.yml__이라는 이름의 구성 요소 버전 설명자 파일(예약된 파일 이름)은 각 콘텐츠 소스 루트에 필요합니다. __antora.yml__ 파일은 __modules__라는 폴더의 내용을 수집하고 처리해야 함을 Antora에 나타냅니다.
<3> __modules__라는 이름의 필수 폴더(예약된 폴더 이름). __modules__ 폴더는 콘텐츠 소스 루트의 __antora.yml__ 파일과 동일한 계층 수준에 있어야 합니다. 즉, __antora.yml__ 파일과 _modules_ 폴더는 형제입니다. __modules__ 폴더에는 최소한 __ROOT__ 모듈 폴더 또는 명명된 모듈 폴더 중 하나가 포함되어야 합니다.
<4> 선택적 _ROOT_ 모듈 폴더. Antora는 _ROOT_ 모듈 폴더의 게시 가능한 리소스에 특별한 동작을 적용합니다. _ROOT_ 는 예약된 폴더 이름이며 모두 대문자여야 합니다. 모듈 폴더에는 하나 이상의 패밀리 폴더가 포함되어야 합니다.
<5> 선택적 _attachments_ 패밀리 폴더(예약된 폴더 이름).
<6> 선택적 _examples_ 패밀리 폴더(예약된 폴더 이름).
<7> 선택적 _images_ 패밀리 폴더(예약된 폴더 이름).
<8> 선택적 _pages_ 패밀리 폴더(예약된 폴더 이름).
<9> 선택적 _partials_ 패밀리 폴더(예약된 폴더 이름).
<10> __nav.adoc__이라는 이름의 선택적 탐색 파일.
<11> 선택적 명명된 모듈 폴더. 필요한 만큼 많은 명명된 모듈 폴더를 만들 수 있습니다. 모듈 폴더에는 하나 이상의 패밀리 폴더가 포함되어야 합니다.
<12> __nav.adoc__이라는 이름의 선택적 탐색 파일.
<13> Antora는 _modules_ 폴더 외부에 있기 때문에 이 폴더의 파일을 처리하지 않습니다.

예제 1에서 콘텐츠 소스 루트는 저장소의 루트에 있습니다. 그러나 콘텐츠 소스 루트가 반드시 저장소의 루트에 있을 필요는 없습니다. 예제 2에서 콘텐츠 소스 루트는 저장소의 폴더에 있습니다.

.예제 2. 저장소의 폴더에 있는 표준 파일 및 폴더 세트의 모든 필수 및 선택적 파일 및 폴더
[source]
----
📒 repository <1>
  📁 config <2>
    📂 docs <3>
      📄 antora.yml
        📂 modules
          📂 ROOT
            📁 attachments
            📁 examples
            📁 images
            📁 pages
            📁 partials
            📄 nav.adoc
          📂 named-module
            📁 pages
        📁 notes <4>
      📄 README.adoc <5>
----
<1> 저장소 루트
<2> Antora는 사이트의 플레이북에 콘텐츠 소스 루트로 지정되지 않았기 때문에 이 폴더를 무시합니다(이 예제의 목적상).
<3> 사이트의 플레이북에서 start_path 또는 start_paths 키를 사용하여 지정된 콘텐츠 소스 루트(이 예제의 목적상).
<4> Antora는 __modules__ 폴더 외부에 있기 때문에 이 폴더의 파일을 처리하지 않습니다.
<5> Antora는 콘텐츠 소스 루트에 없기 때문에 이 파일을 무시합니다. 

TIP: 기본적으로 Antora는 저장소 루트와 콘텐츠 소스 루트가 동일하다고 가정합니다. 콘텐츠 소스 루트가 저장소의 폴더 내에 있는 저장소를 구조화한 경우 사이트의 플레이북에서 start_path 또는 start_paths 키를 사용하여 폴더 경로를 지정해야 합니다.

예제 1과 예제 2에 표시된 많은 폴더는 선택 사항입니다. 필요한 경우 하나의 모듈 폴더(ROOT 또는 명명된 모듈 폴더일 수 있음)만 설정하면 됩니다. 또한 소스 파일의 유형과 목적에 가장 적합한 제품군 폴더만 모듈 폴더에 설정하면 됩니다. 예를 들어 모듈 폴더에 저장된 페이지에 이미지를 삽입하지 않는 경우 images 폴더를 생성할 필요가 없습니다.

다음 섹션에서는 Antora의 유효한 표준 파일 및 폴더 세트의 최소 요구 사항을 충족하는 두 가지 콘텐츠 소스 예제를 볼 수 있습니다.

== 최소 요구 사항

콘텐츠 소스 루트에서 Antora는 다음을 찾아야 합니다:

- 콘텐츠 소스 루트에 있는 __antora.yml__ 파일
- __antora.yml__ 파일과 동일한 계층 수준에 있는 __modules__ 폴더
- __modules__ 폴더에 하나 이상의 모듈 폴더
- 하나 이상의 소스 파일이 포함된 모듈 폴더의 하나 이상의 제품군 폴더

최소 요구 사항을 충족하는 표준 파일 및 폴더 세트를 보여주는 두 가지 예를 살펴보겠습니다. 예제 3의 폴더 및 파일 세트는 콘텐츠 소스 루트에 필요한 __antora.yml__과 __modules__ 폴더가 포함되어 있기 때문에 유효합니다. __modules__ 폴더에는 이 경우 특수 __ROOT__ 모듈 폴더인 하나의 모듈 폴더가 포함되어 있습니다. 차례로 __ROOT__ 모듈 폴더에는 하나의 소스 파일을 포함하는 제품군 폴더가 포함되어 있습니다.

.예제 3. ROOT 모듈 폴더가 포함된 유효한 표준 파일 및 폴더 세트
[source]
----
📒 repository <1>
  📄 antora.yml <2>
  📂 modules <3>
    📂 ROOT <4>
      📂 pages <5>
        📄 page-source-file.adoc <6>
----
<1> 이 예제에서 콘텐츠 소스 루트는 저장소의 루트에 있습니다.
<2> 유효한 파일 이름 __antora.yml__을 가진 구성 요소 버전 설명자 파일.
<3> __modules__ 폴더.
<4> __ROOT__ 모듈 폴더.
<5> __pages__ 제품군 폴더.
<6> 페이지의 소스 파일. 

예제 4에서 콘텐츠 소스 루트는 __ops-training__ 폴더에 있습니다.

.예제 4. 명명된 모듈 폴더가 포함된 유효한 표준 파일 및 폴더 세트
[source]
----
📒 repository
  📂 courses
    📂 ops-training <1>
      📄 antora.yml <2>
      📂 modules <3>
        📂 rz-interface <4>
          📂 images <5>
            📄 image-source-file.ext <6>
----
<1> 콘텐츠 소스 루트.
<2> 유효한 파일 이름 __antora.yml__을 가진 구성 요소 버전 설명자 파일.
<3> __modules__ 폴더.
<4> __rz-interface__라는 이름의 모듈 폴더.
<5> __images__ 제품군 폴더.
<6> 이미지의 소스 파일.

예제 4의 표준 폴더 및 파일 세트도 유효합니다.

== 숨겨진 파일 및 게시되지 않은 파일

**숨겨진 파일**은 Antora의 표준 폴더 계층 구조에 저장된 파일 중 점(.)으로 시작하는 파일입니다. __examples__ 폴더 또는 __partials__ 폴더에 저장되지 않는 한 파일 확장자가 없는 파일도 숨겨집니다. 숨겨진 파일은 Antora의 콘텐츠 카탈로그에 추가되지 않으므로 리소스 ID가 할당되지 않고 참조할 수 없으며 게시되지 않습니다.

.예제 5. 숨겨진 파일이 포함된 표준 폴더 세트
[source]
----
📒 repository
  📄 antora.yml
  📂 modules
    📂 ROOT
      📂 examples
        📄 .hidden-example-file.ext <1>
        📄 example-file <2>
      📂 pages
        📄 .hidden-page-file.adoc <3>
        📄 hidden-page-file <4>
----
<1> 파일 이름이 점(.)으로 시작하기 때문에 Antora는 이 예제 파일을 콘텐츠 카탈로그에 로드하지 않습니다. 
<2> __examples__ 폴더에 저장된 파일에는 파일 확장자가 필요하지 않으므로 Antora는 이 예제 파일을 콘텐츠 카탈로그에 로드합니다. 
<3> 파일 이름이 점(.)으로 시작하기 때문에 Antora는 이 페이지 파일을 콘텐츠 카탈로그에 로드하거나 게시하지 않습니다. 
<4> 파일 확장자가 없고 페이지 파일에는 파일 확장자가 있어야 하므로 Antora는 이 페이지 파일을 콘텐츠 카탈로그에 로드하거나 게시하지 않습니다.

IMPORTANT: Dockerfile과 같이 파일 확장자가 없는 것이 일반적인 파일 유형을 제외하고는 예제 및 부분 소스 파일을 유효한 파일 확장자로 저장하는 것이 좋습니다. 부분 및 예제 파일을 파일 확장자와 함께 저장하지 않으면 부분 또는 예제 파일에 추가 동작을 적용하는 Antora 또는 Asciidoctor 확장을 사용하지 못할 수 있습니다.

**게시되지 않은 파일**은 Antora의 표준 폴더 계층 구조에 저장된 파일 중 밑줄(_)로 시작하는 파일입니다. 게시되지 않은 파일은 콘텐츠 카탈로그에 추가되고 리소스 ID(해당하는 경우)가 할당되며 참조할 수 있습니다. 그러나 게시 가능한 제품군(즉, pages, images 또는 attachments)의 폴더에 저장되어 있더라도 게시되지 않은 파일은 자동으로 게시되지 않습니다.

.예제 6. 게시되지 않은 파일이 포함된 표준 폴더 세트
[source]
----
📒 repository
  📄 antora.yml
  📂 modules
    📂 ROOT
      📂 images
        📄 _unpublished-image-file.ext <1>
      📂 pages
        📄 _unpublished-page-file.adoc <2>
----
<1> 밑줄(_)로 시작하는 파일 이름을 가진 이미지 파일은 콘텐츠 카탈로그에 로드되고 이미지 매크로로 참조할 수 있습니다. 그러나 게시 가능한 제품군의 폴더에 저장되어 있더라도 이미지는 자동으로 게시되지 않습니다.
<2> 밑줄(_)로 시작하는 파일 이름을 가진 페이지 파일은 콘텐츠 카탈로그에 로드되고 include 지시문으로 참조할 수 있습니다. 그러나 게시 가능한 제품군의 폴더에 저장되어 있더라도 자체 페이지로 게시되지 않으므로 xref 매크로로 참조할 수 없습니다.