= Antora의 AsciiDoc 속성

AsciiDoc 프로세서와 마찬가지로 Antora는 AsciiDoc 문서 속성(이하 **속성**)을 사용하여 페이지 안팎으로 정보를 순환시킵니다. 이러한 속성은 처리 설정을 토글하거나 구성하고, 출력의 동작과 스타일을 제어하고, 소스에서 UI 템플릿으로 메타데이터를 전달하고, 페이지에 대한 정보를 콘텐츠로 전달하는 등 다양한 용도로 사용됩니다.

일반적으로 속성에는 내장 속성과 사용자 정의 속성의 두 가지 종류가 있습니다. 속성은 페이지 속성인 것과 그렇지 않은 것으로도 구분할 수 있습니다. 이 페이지에서는 이러한 속성 범주를 소개하고 속성을 정의하고 사용하는 방법에 대해 자세히 알아보기 위해 추가 페이지를 참조합니다.

== 내장 속성

**내장 속성**은 페이지로 정보를 전달하거나 작성자가 동작을 토글하거나 구성할 수 있는 방법을 제공하는 AsciiDoc 문서 속성입니다. 일부 내장 속성은 읽기 전용이고 다른 속성은 수정할 수 있습니다.

내장 속성에는 예약된 이름이 있으며 특수하고 사전 정의된 목적을 제공합니다. 예를 들어 idseparator 속성은 자동 생성된 섹션 ID의 단어 구분자를 제어하는 데 사용됩니다. 내장 속성의 목적은 제한되어 있지만 모든 AsciiDoc 속성과 마찬가지로 속성 참조(예: \{idseparator})를 사용하여 해당 값을 페이지에 표시할 수 있습니다.

수정 가능한 많은 내장 속성에는 허용되는 값 집합이 제한되어 있습니다. 각 값은 사전 정의된 동작이나 경계 조건을 나타냅니다. 예를 들어 ``xrefstyle`` 속성은 basic, short 또는 full의 사전 정의된 값을 사용하여 내부 xref의 링크된 텍스트 스타일을 제어합니다. ``max-include-depth`` 속성은 include가 중첩될 수 있는 깊이를 지정합니다.

AsciiDoc 프로세서는 수많은 내장 속성을 정의합니다. Antora는 Antora 환경에 특화된 추가 내장 속성을 도입합니다. 이러한 속성의 목적은 Antora와 함께 작동하도록 AsciiDoc 프로세서를 구성하는 것입니다. 대부분의 경우 이러한 속성에는 ``page-`` 접두사가 붙어 있어 고유한 페이지 속성이 됩니다.

Antora에서 정의한 읽기 전용 속성 목록은 Intrinsic attributes를 참조하세요. AsciiDoc에서 정의된 모든 내장 속성 목록은 AsciiDoc Document Attributes Reference를 참조하세요(단, 이 중 모든 속성이 Antora 환경에서 관련이 있는 것은 아닙니다).

== 사용자 정의 속성

**사용자 정의 속성**은 작성자가 정의한 AsciiDoc 문서 속성입니다. AsciiDoc에서 URL이나 제품 이름과 같은 재사용 가능한 콘텐츠를 저장하기 위해 사용자 정의 속성을 사용하는 것에 익숙할 수 있습니다. 그런 다음 속성 참조를 사용하여 페이지 내에서(또는 정의된 위치에 따라 페이지 전체에서) 사용자 정의 속성의 값을 사용할 수 있습니다. Antora의 사용자 정의 속성도 동일한 방식으로 작동합니다.

Define a custom AsciiDoc attribute 및 Define a custom page attribute를 참조하여 사용자 정의 속성을 정의하는 방법을 알아보세요.

== 페이지 속성

속성 이름이 ``page-``로 시작할 때 흥미로운 점이 있습니다. 이 특별한 지정을 통해 속성은 페이지 속성이 됩니다.

AsciiDoc 문서에서 페이지 속성은 다른 AsciiDoc 속성과 동일합니다. 예를 들어 내장 페이지 속성 ``{page-version}``을 사용하여 현재 페이지의 컴포넌트를 참조할 수 있습니다. 또는 page-edition이라는 사용자 정의 페이지 속성을 정의하고 ``\{page-edition}``을 사용하여 페이지에서 이를 참조할 수 있습니다. 이 컨텍스트에서 page- 접두사는 중요하지 않습니다.

이 특별한 지정이 적용되는 곳은 페이지의 내용에 UI 템플릿이 적용될 때입니다. 페이지 속성은 페이지의 UI 모델로 승격되어 UI 템플릿(예: __layouts/default.hbs__) 내에서 ``page.attributes.<name>`` 표현식을 사용하여 액세스할 수 있습니다. 실제로 페이지 속성을 사용하면 작성자가 페이지의 헤더 또는 구성 파일(예: Antora 플레이북)에서 속성을 사용하여 정의한 메타데이터를 전달할 수 있으므로 해당 정보를 AsciiDoc 문서 외부에서 사용할 수 있습니다. 심지어 UI 템플릿에서 현재 페이지가 아닌 다른 페이지의 페이지 속성에 액세스하는 것도 가능합니다. page- 접두사가 붙지 않은 속성은 이러한 방식으로 액세스할 수 없습니다(UI 도우미를 사용하여 모든 속성에 액세스하는 것은 여전히 가능합니다).

페이지 속성은 주로 사용자 정의 속성이지만 Antora는 Antora 관련 기능을 제어하거나 현재 페이지에 대한 정보를 얻기 위해 몇 가지 내장 페이지 속성을 정의합니다. 페이지 속성에 대해 자세히 알아보고 페이지 속성을 정의하고 사용하는 방법은 Page Attributes 을 참조하세요.
