= Page 링크 생성

== xref 매크로에 올바른 리소스 ID 좌표 할당하기

이 페이지에서는 다음과 같은 경우에 xref 매크로에 올바른 리소스 ID 좌표를 할당하는 방법을 배웁니다:

* [*] 대상 페이지와 현재 페이지가 동일한 컴포넌트 버전과 모듈에 속하는 경우
* [*] 대상 페이지가 pages 디렉토리의 루트에 저장된 경우
* [*] 대상 페이지가 pages 디렉토리의 하위 디렉토리에 저장된 경우
* [*] 대상 페이지와 현재 페이지가 pages 디렉토리의 동일한 하위 디렉토리에 저장된 경우
* [*] 대상 페이지와 현재 페이지가 서로 다른 모듈에 속하는 경우
* [*] 대상 페이지와 현재 페이지가 서로 다른 컴포넌트 버전에 속하는 경우
* [*] 대상 페이지와 현재 페이지가 동일한 컴포넌트 버전에 속하지 않고, 페이지 링크가 항상 대상 페이지의 최신 버전을 사용해야 하는 경우
* [*] 대상 페이지와 현재 페이지가 동일한 컴포넌트에 속하지만, 대상 페이지가 다른 버전에 속하는 경우

[NOTE]
====
Antora 리소스 ID, 좌표 또는 xref 매크로 사용 방법에 익숙하지 않은 경우 다음을 참조하세요:

- Resources and Resource IDs
- Resource ID Coordinates
- Xref Macros and Page Links
====

== 모듈 내 페이지 링크

생성하는 대부분의 상호 참조는 컴포넌트 버전의 동일한 모듈에 속하는 페이지 간에 이루어질 것입니다. 현재 페이지와 대상 페이지가 동일한 컴포넌트 버전과 모듈에 속할 때 AsciiDoc xref 매크로는 대상 페이지의 리소스 ID에서 파일 좌표만 필요로 합니다.

TIP: **대상 페이지**는 현재 페이지에서 참조하는 페이지 소스 파일입니다. 대상 페이지는 현재 페이지의 내용에서 xref 매크로에 리소스 ID를 할당하여 참조됩니다. **현재 페이지**는 대상 페이지를 참조하는 xref 매크로를 포함하는 페이지 소스 파일입니다.

예제 1은 현재 페이지의 xref 매크로에 할당된 대상 페이지의 파일 좌표를 보여줍니다.

.예제 1. current-page.adoc
[source,asciidoc]
----
xref:file-coordinate-of-target-page.adoc[optional link text] <1>

xref:file-coordinate-of-target-page.adoc#fragment[optional link text] <2>
----
<1> xref 매크로를 설정하는 방법에 대한 단계별 지침은 Make a link with the xref macro를 참조하세요.
<2> 대상 페이지의 요소 ID를 나타내는 선택적 프래그먼트는 대상 페이지의 파일 좌표 뒤에 할당할 수 있습니다.

대상 페이지의 파일 좌표는 항상 pages 패밀리 디렉토리의 루트에서 계산됩니다. 즉, 대상 페이지의 파일 좌표 구조는 대상 페이지가 pages 패밀리 디렉토리의 루트에 저장되는지 아니면 pages 디렉토리의 하위 디렉토리에 저장되는지에 따라 달라집니다.

.예제 2. 대상 페이지의 파일 좌표 구조
[source,asciidoc]
----
xref:target-page-filename.adoc[optional link text] <1>

xref:path/to/target-page-filename.adoc[optional link text] <2>

xref:./target-page-filename.adoc[optional link text] <3>
----
<1> __pages__ 디렉토리의 루트에 저장된 대상 페이지의 파일 좌표
<2> 대상 페이지가 __pages__ 디렉토리의 하위 디렉토리에 저장되어 있지만 현재 페이지는 동일한 하위 디렉토리에 저장되지 않은 경우의 대상 페이지의 파일 좌표
<3> 대상 페이지와 현재 페이지가 __pages__ 디렉토리의 동일한 하위 디렉토리에 저장된 경우의 대상 페이지의 파일 좌표

다음 섹션에서는 파일 좌표 구조의 예를 제공합니다.

=== pages 디렉토리 루트의 파일 좌표

대상 페이지가 __pages__ 패밀리 디렉토리의 루트에 저장되면 파일 좌표는 대상 페이지의 파일 이름과 파일 확장자입니다.

.예제 3. 대상 페이지가 pages 디렉토리의 루트에 저장된 경우의 파일 좌표
[source,asciidoc]
----
xref:target-page-filename.adoc[optional link text]
----

예제 4에 나열된 페이지 중 일부를 이 섹션의 예제에 대한 기준으로 사용해 보겠습니다.

.예제 4. colorado 5.2에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml <1>
📂 modules
  📂 la-garita <2> 
    📂 pages <3>
      📄 ridge.adoc
      📄 willow-creek.adoc
  📂 ROOT <4>
    📂 pages <5>
      📄 index.adoc
      📄 ranges.adoc
----
<1> 컴포넌트 버전을 __colorado 5.2__로 정의합니다.
<2> __la-garita__라는 이름의 모듈을 정의합니다.
<3> 후속 파일을 페이지로 정의합니다.
<4> __ROOT__ 모듈을 정의합니다.
<5> 후속 파일을 페이지로 정의합니다.

위의 예제 4에 표시된 __la-garita__ 모듈에 속하는 두 페이지를 사용하여 __ridge.adoc__에서 __willow-creek.adoc__를 참조해 보겠습니다. 즉, __willow-creek.adoc__ 소스 파일이 대상 페이지이고 __ridge.adoc__가 현재 페이지입니다. 예제 5는 __willow-creek.adoc__ 페이지에 연결되는 __ridge.adoc__ 페이지의 xref 매크로를 보여줍니다.

.예제 5. ridge.adoc (현재 페이지)
[source,asciidoc]
----
The xref:willow-creek.adoc[trailhead] is north of town.
----

__willow-creek.adoc__ 페이지의 파일 좌표는 __pages__ 디렉토리의 루트에 저장되어 있기 때문에 파일 이름과 파일 확장자인 __willow-creek.adoc__로만 구성됩니다. 대상 페이지의 파일 좌표는 항상 pages 패밀리 디렉토리의 루트에서 계산됩니다.

__index.adoc__ 페이지(현재 페이지)에서 __ranges.adoc__ 페이지(대상 페이지)를 참조하는 예제 6에 표시된 또 다른 xref 매크로를 살펴보겠습니다.

.예제 6. index.adoc (현재 페이지)
[source,asciidoc]
----
The Rocky Mountains consists of xref:ranges.adoc[numerous mountain ranges].
----

두 페이지 모두 __ROOT__ 모듈과__ colorado 5.2__ 컴포넌트 버전에 속하기 때문에 xref 매크로에는 대상 페이지의 파일 좌표만 지정하면 됩니다. __ranges.adoc__의 파일 좌표는 __pages__ 디렉토리의 루트에 저장되어 있기 때문에 __ranges.adoc__입니다. 대상 페이지가 pages 디렉토리의 하위 디렉토리에 저장된 경우의 파일 좌표 예제는  File coordinate with pages-relative directory path를 참조하세요.

=== 페이지 상대 디렉토리 경로가 있는 파일 좌표

현재 페이지가 대상 페이지와 동일한 하위 디렉토리에 저장되지 않은 경우 대상 페이지의 파일 좌표에는 대상 페이지의 페이지 상대 디렉토리 경로가 필요합니다. 두 페이지가 동일한 하위 디렉토리에 저장된 경우 File coordinate with relative path token을 참조하세요.

.예제 7. 대상 페이지가 pages 디렉토리의 하위 디렉토리에 저장된 경우의 파일 좌표
[source,asciidoc]
----
xref:path/to/target-page-filename.adoc[optional link text]
----

__ranges.adoc__에서 __faq.adoc__를 참조해 보겠습니다. 예제 8에서 볼 수 있듯이 두 페이지 모두 __colorado 5.2__ 컴포넌트 버전의 __ROOT__ 모듈에 속합니다.

.예제 8. colorado 5.2에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml <1>
📂 modules
  📂 ROOT <2>
    📂 pages <3>
      📄 index.adoc
      📄 ranges.adoc
      📂 terms <4> 
        📄 faq.adoc
        📄 signs.adoc
----
<1> 컴포넌트 버전을 __colorado 5.2__로 정의합니다.
<2> __ROOT__ 모듈을 정의합니다.
<3> 후속 소스 파일을 페이지로 정의합니다.
<4> 페이지의 소스 파일이 포함된 __pages__의 하위 디렉토리

예제 9의 xref 매크로는 __ranges.adoc__ 페이지(현재 페이지)에서 __faq.adoc__ 페이지(대상 페이지)로 연결합니다.

.예제 9. ranges.adoc (현재 페이지)
[source,asciidoc]
----
See the xref:terms/faq.adoc[].
----

예제 9에서 볼 수 있듯이 __faq.adoc__의 파일 좌표는 ``terms/faq.adoc``입니다. xref 매크로에 할당된 파일 좌표는 __faq.adoc__이 __terms__ 하위 디렉토리에 저장되어 있기 때문에 대상 페이지의 페이지 상대 디렉토리 경로와 파일 이름 및 파일 확장자로 구성됩니다. 현재 페이지와 대상 페이지가 동일한 하위 디렉토리에 저장된 경우 페이지 상대 디렉토리 경로 대신 상대 경로 토큰 ./를 사용할 수 있습니다.

=== 상대 경로 토큰이 있는 파일 좌표

대상 페이지와 현재 페이지가 __pages__ 디렉토리의 동일한 하위 디렉토리에 저장된 경우 대상 페이지의 파일 좌표에서 페이지 상대 디렉토리 경로를 상대 경로 토큰 ``./``로 대체할 수 있습니다.

.예제 10. 대상 페이지와 현재 페이지가 동일한 하위 디렉토리에 저장된 경우의 파일 좌표
[source,asciidoc]
----
xref:./target-page-filename.adoc[optional link text]
----

__signs.adoc__에서 __faq.adoc__를 참조해 보겠습니다. 예제 11은 두 파일 모두 __pages__ 디렉토리의 __terms__ 하위 디렉토리에 저장되어 있으며, 두 파일 모두 동일한 모듈과 컴포넌트 버전에 속함을 보여줍니다.

.예제 11. colorado 5.2에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml
📂 modules
  📂 ROOT <1>
    📂 pages <2> 
      📄 index.adoc
      📂 terms <3>
        📄 faq.adoc
        📄 signs.adoc
----
<1> ROOT 모듈을 정의합니다.
<2> 후속 소스 파일을 페이지로 정의합니다.
<3> 페이지의 소스 파일이 포함된 __pages__의 하위 디렉토리

대상 페이지와 현재 페이지가 __pages__ 디렉토리의 동일한 하위 디렉토리에 저장된 경우 상대 경로 토큰 ``./``를 사용하여 대상 페이지의 파일 좌표를 줄일 수 있습니다. 예제 10의 xref 매크로는 __signs.adoc__ 페이지(현재 페이지)에서 __faq.adoc__ 페이지(대상 페이지)로 연결됩니다.

.예제 12. signs.adoc (현재 페이지)
[source,asciidoc]
----
See the xref:./faq.adoc[].
----

예제 12에서 볼 수 있듯이 __signs.adoc__에서 참조될 때 __faq.adoc__의 파일 좌표는 ``./faq.adoc``입니다. 두 페이지 모두 __terms__ 하위 디렉토리에 저장되므로 대상 페이지의 파일 좌표에서 페이지 상대 디렉토리 경로를 ``./`` 토큰으로 대체합니다.

== 모듈 간 페이지 링크

대상 페이지와 현재 페이지가 동일한 모듈에 속하지 않는 경우 xref 매크로에 대상 페이지의 모듈 좌표와 파일 좌표를 지정해야 합니다.

.예제 13. xref 매크로에 할당된 대상 페이지의 모듈 및 파일 좌표
[source,asciidoc]
----
xref:module:file-coordinate-of-target-page.adoc[optional link text] <1>
----
<1> 대상 페이지와 현재 페이지가 동일한 컴포넌트 버전에 속하지만 동일한 모듈에 속하지 않을 때 xref 매크로에 대상 페이지의 모듈 및 파일 좌표를 할당합니다.

예제 14에 표시된 __colorado 5.2__ 컴포넌트 버전의 두 페이지를 사용하여 __willow-creek.adoc__에서 __ranges.adoc__를 참조해 보겠습니다.

.예제 14. colorado 5.2에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml <1> 
📂 modules
  📂 la-garita <2>
    📂 pages
      📄 willow-creek.adoc
  📂 ROOT <3>
    📂 pages
      📄 index.adoc
      📄 ranges.adoc
----
<1> 컴포넌트 버전을 __colorado 5.2__로 정의합니다.
<2> __la-garita__라는 이름의 모듈을 정의합니다.
<3> __ROOT__ 모듈을 정의합니다.

__willow-creek.adoc__ 페이지는 __la-garita__ 모듈에 속하지만 __ranges.adoc__은 __ROOT__ 모듈에 속합니다. 예제 15의 xref 매크로는 __willow-creek.adoc__ 페이지(현재 페이지)에서 __ranges.adoc__(대상 페이지)로 연결됩니다.

.예제 15. willow-creek.adoc (현재 페이지)
[source,asciidoc]
----
Only xref:ROOT:ranges.adoc[one pass is open] in the winter.
----

예제 15에서 볼 수 있듯이 대상 페이지의 모듈 좌표는 ``ROOT``이고 파일 좌표는 ``ranges.adoc``입니다.

== 컴포넌트 버전 간 페이지 링크

대상 페이지와 현재 페이지가 서로 다른 문서 컴포넌트에 속하는 경우 xref 매크로에 최소한 대상 페이지의 컴포넌트, 모듈 및 파일 좌표를 지정해야 합니다. 대부분의 경우 버전 좌표도 지정합니다.

.예제 16. xref 매크로에 할당된 버전, 컴포넌트, 모듈 및 파일 좌표
[source,asciidoc]
----
xref:version@component:module:file-coordinate-of-target-page.adoc[optional link text] <1>

xref:component:module:file-coordinate-of-target-page.adoc[optional link text] <2>
----
<1> 대상 페이지와 현재 페이지가 동일한 컴포넌트 버전에 속하지 않을 때 xref 매크로에 대상 페이지의 버전, 컴포넌트, 모듈 및 파일 좌표를 할당합니다.
<2> 버전 좌표가 지정되지 않은 경우 Antora는 런타임에 대상 페이지의 컴포넌트 최신 버전을 사용하여 리소스 ID를 완성합니다. 이 동작은 대상 페이지와 현재 페이지가 서로 다른 문서 컴포넌트에 속하는 경우에만 적용됩니다.

__index.adoc__에서 __elevation.adoc__를 참조해 보겠습니다. __index.adoc__ 페이지는 컴포넌트 버전 __colorado 5.2__(예제 17)에 속합니다. __elevation.adoc__ 페이지는 컴포넌트 버전 __wyoming 1.0__(예제 18)에 속합니다.

.예제 17. colorado 5.2에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml <1>
📂 modules
  📂 la-garita
    📂 pages
      📄 willow-creek.adoc
  📂 ROOT
    📂 pages
      📄 index.adoc
      📄 ranges.adoc
----
<1> 컴포넌트 버전을 __colorado 5.2__로 정의합니다.

.예제 18. wyoming 1.0에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml <1>
📂 modules
  📂 sierra-madre
    📂 pages
      📄 elevation.adoc
      📄 wilderness-areas.adoc
----
<1> 컴포넌트 버전을 __wyoming 1.0__으로 정의합니다.

예제 19에서 xref 매크로는 __index.adoc__(현재 페이지)에서 __elevation.adoc__ 페이지(대상 페이지)로 연결합니다.

.예제 19. index.adoc (현재 페이지)
[source,asciidoc]
----
Do you know xref:1.0@wyoming:sierra-madre:elevation.adoc[how elevation is measured]?
----

대상 페이지가 __wyoming 1.0__ 컴포넌트 버전에 속하는 반면 현재 페이지는 __colorado 5.2__에 속하기 때문에 xref 매크로에 할당된 리소스 ID는 대상 페이지의 버전, 컴포넌트, 모듈 및 파일 좌표를 지정합니다. 예제 19에서 볼 수 있듯이 대상 페이지의 버전 좌표는 1.0, 컴포넌트 좌표는 __wyoming__, 모듈 좌표는 __sierra-madre__, 파일 좌표는 __elevation.adoc__입니다.

예제 20에서는 __elevation.adoc__ 페이지에서 __ranges.adoc__ 페이지를 참조합니다. 대상 페이지인 __ranges.adoc__은 __colorado 5.2__의 __ROOT__ 모듈에 속하는 반면 현재 페이지는 __wyoming 1.0__에 속합니다.

.예제 20. elevation.adoc (현재 페이지)
[source,asciidoc]
----
xref:5.2@colorado::ranges.adoc[]
----

예제 20에서 모듈 좌표 ``ROOT``가 리소스 ID에서 누락된 것으로 보인다는 점을 주목하십시오. 리소스 ID에 컴포넌트 좌표가 지정되고 대상 페이지가 ROOT 모듈에 속하는 경우 모듈 좌표 ``ROOT``를 명시적으로 지정할 필요가 없습니다. 그러나 모듈 좌표 뒤에 오는 콜론(``:``)은 여전히 입력해야 합니다. 파일 좌표 ``ranges.adoc`` 바로 앞에 이 :가 있는 것을 볼 수 있습니다. 이 단축 표기법은 컴포넌트 좌표가 지정되고 대상 페이지의 모듈 좌표가 ``ROOT``인 경우에만 작동합니다. 모듈 좌표가 필요한 다른 모든 경우에는 모듈의 이름을 지정해야 합니다.

=== 페이지의 최신 버전으로 링크

TIP: 이 동작은 대상 페이지와 현재 페이지가 서로 다른 문서 컴포넌트에 속하는 경우에만 적용됩니다!

xref 매크로에 할당된 리소스 ID에 버전이 지정되지 않고 대상 페이지와 현재 페이지가 동일한 컴포넌트에 속하지 않는 경우 Antora는 런타임에 대상 페이지의 컴포넌트 최신 버전의 버전 좌표를 사용하여 리소스 ID를 완성합니다.

__willow-creek.adoc__ 페이지(현재 페이지)에서 __elevation.adoc__ 페이지(대상 페이지)를 참조해 보겠습니다. __elevation.adoc__은 컴포넌트 버전 __wyoming 1.0__(예제 21)에 속합니다. __willow-creek.adoc__은 컴포넌트 버전 __colorado 5.2__(예제 22)에 속합니다.

.예제 21. wyoming 1.0에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml <1>
📂 modules
  📂 sierra-madre
    📂 pages
      📄 elevation.adoc
      📄 wilderness-areas.adoc
----
<1> 컴포넌트 버전을 __wyoming 1.0__으로 정의합니다.

.예제 22. colorado 5.2에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml <1>
📂 modules
  📂 la-garita
    📂 pages
      📄 willow-creek.adoc
----
<1> 컴포넌트 버전을 colorado 5.2로 정의합니다.

예제 23의 xref 매크로를 항상 __elevation.adoc__ 페이지의 최신 버전에 연결하려면 대상 페이지의 리소스 ID에 버전 좌표를 지정하지 마십시오.

.예제 23. willow-creek.adoc (현재 페이지)
[source,asciidoc]
----
xref:wyoming:sierra-madre:elevation.adoc[How are peaks measured]? <1>
----
<1> 매크로 접두사 xref: 바로 뒤에 대상 페이지의 컴포넌트 좌표로 시작하는 리소스 ID를 할당합니다.

Antora가 실행되면 버전 정렬 규칙과 최신 버전 기준에 따라 __wyoming 1.0__을 __wyoming__ 컴포넌트의 최신 버전으로 식별합니다. 예제 23에 버전 좌표가 지정되지 않았기 때문에 Antora는 최신 __wyoming__ 컴포넌트의 버전 좌표(1.0)를 사용하여 xref 매크로에 할당된 리소스 ID를 완성합니다. 이 동작은 대상 페이지와 현재 페이지가 서로 다른 컴포넌트에 속하는 경우에만 적용된다는 점을 기억하십시오.

몇 달 후, 예제 24에 표시된 새로운 컴포넌트 버전 __wyoming 1.5__를 사이트에 추가해 보겠습니다.

.예제 24. wyoming 1.5에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml <1>
📂 modules
  📂 sierra-madre
    📂 pages
      📄 elevation.adoc
      📄 wilderness-areas.adoc
----
<1> 컴포넌트 버전을 wyoming 1.5로 정의합니다.

다음에 사이트가 생성될 때 Antora는 __wyoming 1.5__(__wyoming 1.0__이 아님)가 __wyoming__ 컴포넌트의 최신 버전임을 결정합니다.

.예제 25. willow-creek.adoc (현재 페이지)
[source,asciidoc]
----
xref:wyoming:sierra-madre:elevation.adoc[How are peaks measured]?
----

Antora가 이제 __wyoming 1.5__를 __wyoming__ 컴포넌트의 최신 버전으로 식별하기 때문에 런타임에 최신 __wyoming__ 컴포넌트의 버전 좌표(1.5)를 사용하여 예제 25의 대상 페이지의 리소스 ID를 완성합니다.

WARNING: 버전 좌표가 지정되지 않고 대상 페이지와 현재 페이지가 서로 다른 컴포넌트에 속하는 경우에만 최신 버전으로 링크하는 이 동작이 적용됩니다. 리소스 ID에 버전 및 컴포넌트 좌표가 지정되지 않은 경우 Antora는 대상 페이지가 현재 페이지와 동일한 컴포넌트 버전에 속한다고 가정하고 현재 페이지의 버전 및 컴포넌트 좌표를 사용하여 대상 페이지의 리소스 ID를 완성합니다.

== 컴포넌트의 버전 간 페이지 링크

현재 페이지와 대상 페이지가 동일한 컴포넌트에 속하지만 대상 페이지가 컴포넌트의 다른 버전에 속하는 경우 버전, 모듈(현재 페이지의 모듈과 다른 경우) 및 파일 좌표를 지정합니다.

.예제 26. current-page.adoc
[source,asciidoc]
----
xref:version@module:file-coordinate-of-target-page.adoc[optional link text] <1>

xref:version@file-coordinate-of-target-page.adoc[optional link text] <2>
----
<1> 대상 페이지가 현재 페이지와 동일한 버전 및 모듈에 속하지 않을 때 xref 매크로에 대상 페이지의 버전, 모듈 및 파일 좌표를 할당합니다.
<2> 대상 페이지가 현재 페이지와 동일한 버전에 속하지 않을 때 xref 매크로에 대상 페이지의 버전 및 파일 좌표를 할당합니다.

__colorado 5.2__(예제 27)와 __colorado 6.0__(예제 28)에 속하는 페이지를 이 섹션의 예제에 대한 기준으로 사용해 보겠습니다.

.예제 27. colorado 5.2에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml <1>
📂 modules
  📂 get-started
    📂 pages
      📄 tour.adoc
  📂 la-garita
    📂 pages
      📄 willow-creek.adoc
----
<1> 컴포넌트 버전을 __colorado 5.2__로 정의합니다.

.예제 28. colorado 6.0에 할당된 디렉토리 및 파일
[source]
----
📄 antora.yml <1>
📂 modules
  📂 la-garita
    📂 pages
      📄 willow-creek.adoc
----
<1> 컴포넌트 버전을 __colorado 6.0__으로 정의합니다.

예제 27의 __colorado 5.2__ 컴포넌트 버전에는 __get-started__ 모듈에 속하는 __tour.adoc__ 페이지가 있습니다. 그러나 예제 28에 표시된 __colorado 6.0__에는 그러한 모듈이나 페이지가 없습니다. __colorado 6.0__ 컴포넌트 버전에 속하는 __willow-creek.adoc__ 페이지(현재 페이지)에서 __tour.adoc__(대상 페이지)를 참조해 보겠습니다. 예제 29에서 xref 매크로에 할당된 리소스 ID는 대상 페이지가 현재 페이지와 다른 버전 및 모듈에 속하기 때문에 대상 페이지의 버전, 모듈 및 파일 좌표를 지정합니다.

.예제 29. willow-creek.adoc (현재 페이지) in colorado 6.0
[source,asciidoc]
----
Last year's xref:5.2@get-started:tour.adoc[excursions] were riveting!
----

예제 29에서 볼 수 있듯이 대상 페이지의 버전 좌표는 5.2, 모듈 좌표는 ``get-started``, 파일 좌표는 ``tour.adoc``입니다.
