= 속성 정의 및 수정

읽기 전용인 특정 내재적 속성을 제외하고 AsciiDoc 문서 속성(이하 **속성**)은 CLI, 플레이북, 컴포넌트 디스크립터 또는 속성 항목을 사용한 페이지의 헤더에서 정의할 수 있습니다. 수정자를 사용하여 특정 속성에 대한 우선 순위가 변경되지 않는 한 우선 순위는 해당 순서(높음에서 낮음)와 일치합니다. 이러한 다양한 범위를 통해 필요한 세분성 수준에서 속성을 정의하고 다른 환경이나 상황에 맞게 해당 값을 재정의할 수 있습니다.

이 페이지에서는 속성 항목을 사용하여 페이지 수준에서 속성을 정의하고 수정하는 방법을 설명합니다. 또는 CLI, 플레이북 또는 컴포넌트 디스크립터를 사용하여 이러한 속성을 더 높은 수준에서 설정할 수 있습니다. 속성을 정의하거나 수정한 결과는 동일합니다(즉, 프로세서는 속성이 정의되는 방식을 신경 쓰지 않습니다).

== 속성 항목이란?

속성 항목은 페이지의 속성을 정의하고 해당하는 경우 값을 할당하는 주요 메커니즘입니다. 속성 항목을 AsciiDoc의 전역 변수 할당과 같다고 생각할 수 있습니다.

속성 항목은 **이름**과 **값**의 두 부분으로 구성됩니다. 각 속성 항목은 페이지 헤더의 고유한 행에 입력해야 합니다. 속성 항목은 여는 콜론(:)으로 시작하고, 그 뒤에 속성의 이름이 바로 오고, 그 다음에 닫는 콜론(:)이 옵니다. 이렇게 하면 속성이 활성화되거나 **설정**되므로 페이지에서 사용할 수 있습니다.

[source,asciidoc]
----
= Page Title
:name-of-an-attribute: <1>
----
<1> 속성의 이름 바로 앞에는 여는 콜론(:)이, 바로 뒤에는 닫는 콜론(:)이 옵니다.

많은 경우 속성 항목에서 이름 뒤에 정보를 입력하여 속성에 명시적으로 값을 할당합니다. 값은 닫는 콜론(:)에서 최소한 하나의 공백으로 떨어져 있어야 합니다.

[source,asciidoc]
----
= Page Title
:name-of-an-attribute: value of the attribute <1>
----
<1> 명시적으로 할당된 값은 닫는 콜론(:)에서 최소한 하나의 공백으로 떨어져 있습니다. 값 끝에서 kbd:[Enter]를 누릅니다.

일부 내장 AsciiDoc 속성은 부울 속성이거나 기본값을 가지고 있기 때문에 속성 항목에서 명시적으로 값을 할당할 필요가 없습니다.

[source,asciidoc]
----
= Page Title
:name-of-an-attribute: <1>
----
<1> 속성에 명시적으로 값을 할당하지 않으려면 닫는 콜론(:) 뒤에 kbd:[Enter]를 누릅니다.

내장 부울 속성의 값은 허용되는 유일한 값이 빈 문자열이기 때문에 항상 비어 있습니다. 다른 내장 속성에는 기본값이 있을 수 있습니다. 내장 속성을 설정하고 해당 값을 비워 두면 Antora는 처리 시점에 기본값(있는 경우)을 속성에 할당합니다.

== 내장 속성 설정

``sectanchors``라는 AsciiDoc 속성을 활성화해 보겠습니다. 속성은 페이지 헤더의 속성 항목에 이름을 입력하여 설정됩니다.

.내장 속성 설정
[source,asciidoc]
----
= Page Title
:sectanchors: <1>
----
<1> 속성은 페이지 헤더에서 이름(sectanchors) 바로 앞에 여는 콜론(:)을, 바로 뒤에 닫는 콜론(:)을 붙여 설정됩니다.

sectanchors를 설정하면 각 섹션 제목의 왼쪽에 앵커가 추가됩니다. sectanchors는 부울 속성이므로 해당 값은 빈 문자열입니다.

== 내장 속성에 값 할당

다음 예제에서는 내장 AsciiDoc 속성에 값을 할당해 보겠습니다. ``xrefstyle`` 속성에는 ``short``, ``full``, ``basic``의 세 가지 내장 값을 사용할 수 있습니다.

[source,asciidoc]
----
= Page Title
:xrefstyle: short <1>
----
<1> 페이지 헤더에서 ``xrefstyle``을 설정하고 ``short`` 값을 할당합니다. 명시적 값은 닫는 콜론(``:``)에서 최소한 하나의 공백으로 떨어져 있어야 합니다.

``xrefstyle``에 ``short`` 값이 할당되면 참조에 링크 텍스트가 지정되지 않은 경우 앵커가 있는 블록에 대한 페이지 내 참조에 블록의 레이블과 번호(예: Listing 1)가 표시됩니다.

CAUTION: 일부 내장 AsciiDoc 속성은 Antora 환경에서 적용되지 않습니다. 이러한 속성에는 ``data-uri``, ``allow-uri-read``, ``docinfo``, ``linkcss``, ``noheader``, ``nofooter``, ``webfonts`` 및 ``outfilesuffix``가 포함됩니다. 이러한 속성을 설정하면 효과가 없거나 Antora가 오작동할 수 있습니다. ``imagesdir``와 같은 다른 속성은 Antora에 의해 자동으로 설정되며 재정의할 수 없습니다.

== 사용자 정의 속성 정의

사용자 정의 속성은 자주 사용되는 텍스트와 URL을 저장하는 경우가 많습니다. 그런 다음 페이지 전체에서 단순히 이름을 입력하여(텍스트나 URL을 반복해서 입력하는 대신) 참조됩니다. 참조되기 전에 사용자 정의 속성에는 사용자 정의 이름이 있어야 하며 값이 할당되어야 합니다.

속성의 이름은 다음 조건을 충족해야 합니다:

- 길이가 최소 한 문자여야 합니다.
- 단어 문자(A-Z, a-z, 0-9 또는 _)로 시작해야 합니다.
- 단어 문자와 하이픈만 포함해야 합니다. 즉, 이름에는 점(.)이나 공백이 포함될 수 없습니다.

속성 이름에는 대문자를 사용할 수 있지만 저장되기 전에 이름이 자동으로 소문자로 변환됩니다. 이름에는 소문자만 사용하고 숫자로 시작하지 않는 것이 모범 사례입니다.

속성 값은 다음과 같을 수 있습니다:

- 모든 인라인 콘텐츠일 수 있습니다.
- 명시적 줄 연속(+)이 사용되는 경우에만 줄 바꿈을 포함할 수 있습니다.

예제 2에서는 속성 항목을 사용하여 사용자 정의 속성의 이름과 값을 정의합니다.

.예제 2. 속성 항목을 사용하여 사용자 정의 속성 정의
[source,asciidoc]
----
= Page Title
:url-repo: https://gitlab.com/antora/demo/docs-site
----

이제 속성의 이름을 중괄호(``\{attribute-name}``) 안에 입력하여 페이지 전체에서 필요할 때마다 참조할 수 있습니다. Create an attribute for a URL에서 복잡한 URL을 대체하는 데 사용되는 또 다른 사용자 정의 속성 예제를 볼 수 있습니다.

== 속성 미설정

내장 및 사용자 정의 속성은 속성 항목에서 이름 앞이나 뒤에 느낌표 기호(!)를 추가하여 미설정, 즉 해제할 수 있습니다.

[source,asciidoc]
----
= Page Title
:!sectanchors:
:table-caption!:
----
미설정되면 속성의 동작과 값을 더 이상 페이지에서 사용할 수 없습니다.

== 우선 순위 규칙

속성은 사이트의 플레이북 파일에서 선언하여 전체 사이트 범위로 지정할 수 있습니다. 컴포넌트 디스크립터 파일(즉, __antora.yml__)에서 선언하여 단일 컴포넌트 버전에 속성을 적용할 수 있습니다. 플레이북이나 컴포넌트 디스크립터에서 하드 설정되거나 하드 미설정된 속성은 페이지에 정의된 속성보다 우선합니다. 이 우선 순위는 우선 순위 수정자를 사용하여 반전될 수 있습니다.

내재적 속성은 수정할 수 없으므로 읽기 전용으로 간주됩니다.

자세한 내용은 site attributes 및 component version attributes에 대한 우선 순위 규칙을 참조하세요.
