= Page 속성

특정 AsciiDoc 문서 속성은 Antora 페이지에 메타데이터를 제공하거나(UI 템플릿에서 사용하기 위해) Antora가 페이지를 처리하는 방식을 제어합니다. 우리는 이를 **페이지 속성**이라고 부릅니다. 페이지 속성에는 세 가지 유형이 있습니다: 사용자 정의, 미리 정의된 속성 및 내재적 속성입니다. 이 페이지에서는 각 유형의 페이지 속성의 목적, 정의 방법 및 UI 모델을 사용하여 UI 템플릿에서 액세스하는 방법을 설명합니다.

== 목적과 구조

페이지 속성은 메타데이터가 Antora 자체, UI 템플릿, 사용자 또는 검색 인덱스를 위한 것이든 메타데이터를 제공하는 것과 관련이 있습니다. 페이지 속성을 정의하면 페이지에 대한 추가 정보를 저장할 수 있으며, 이 정보는 사이트 전체에서 액세스하고 사용할 수 있습니다.

페이지 속성은 일반적으로 문서 헤더의 속성 항목을 사용하여 다른 AsciiDoc 문서 속성과 동일한 방식으로 정의됩니다. 페이지 속성이 다른 점은 속성의 이름이 ``page-``(예: ``page-category``)로 시작해야 한다는 것입니다. ``page-`` 접두사가 있으면 Antora가 이를 페이지 속성으로 식별할 수 있습니다.

CAUTION: ``page-`` 접두사를 추가해야 하는지 궁금하다면 UI 템플릿에서 속성에 액세스해야 하는지 자문해 보세요. 대답이 예인 경우 접두사가 필요합니다. 그렇지 않으면 접두사가 필요하지 않습니다.

두 개의 페이지 속성을 정의하는 페이지의 예입니다:

[source,asciidoc]
----
= Page Title
:page-category: DevOps
:page-edition: Enterprise

Main content.
----

``page-`` 접두사는 Antora와 작성자에게 어떤 속성이 페이지의 메타데이터를 구성하는지에 대한 힌트를 제공하기 위한 것입니다. ``page-`` 접두사를 표준화함으로써 Antora는 AsciiDoc 또는 AsciiDoc 프로세서에 정의된 수많은 내장 및 내재적 속성에서 페이지 속성을 분리할 수 있습니다. 접두사는 페이지 또는 사이트 내에서 재사용 가능한 콘텐츠를 저장하는 데 사용되는 내부 속성(사용자 정의 콘텐츠 속성이라고도 함)에서도 페이지 속성을 분리합니다.

== 사용자 정의 페이지 속성 정의

페이지 속성을 정의하려면 페이지 헤더에 속성 항목을 추가하고 이름을 ``page-``로 시작합니다. 속성 항목을 헤더에 정의하는 것이 중요합니다. 그렇지 않으면 페이지 속성을 찾을 수 없습니다.

페이지 속성을 정의하는 속성 항목의 예입니다:

[source,asciidoc]
----
= Page Title
:page-name-goes-here: value goes here
----

이 페이지 속성의 이름은 ``name-goes-here``(``page-`` 접두사와 사용자 정의 이름 name-goes-here)입니다. 해당 값은 ``value goes here``입니다.

페이지 속성의 이름은 문서 속성의 명명 규칙을 준수해야 합니다. 값은 비워 두거나 문자열 값일 수 있습니다. 값이 비어 있지 않으면 닫는 콜론(:)에서 최소한 하나의 공백으로 떨어져 있어야 합니다.

TIP: 페이지 속성은 특별한 AsciiDoc 문서 속성이기 때문에 Antora 플레이북의 사이트 전체 또는 컴포넌트 버전 디스크립터의 컴포넌트 버전별로 정의할 수도 있습니다.

=== '페이지 속성이 아닌 속성' 승격

기존 문서 속성의 정보를 페이지 속성으로 사용할 수 있게 하려면 해당 속성을 페이지 속성으로 승격해야 합니다. 속성 참조를 사용하여 문서 속성을 페이지 속성으로 승격할 수 있습니다.

예를 들어, 페이지 또는 사이트에 ``product-name`` 속성이 정의되어 있다고 가정해 보겠습니다. 다음 속성 항목을 사용하여 이를 페이지 속성으로 승격할 수 있습니다:

[source,asciidoc]
----
= Page Title
:product-name: Name of My Product
:page-product-name: {product-name}
----

속성 참조는 즉시 해석되므로 ``page-product-name``이라는 페이지 속성이 이제 ``product-name``이라는 문서 속성과 동일한 값을 공유합니다.

== 미리 정의된 페이지 속성 구성

일부 페이지 속성은 Antora에서 특별한 취급을 받습니다. 이러한 페이지 속성에는 예약된 이름이 있지만 페이지에 대한 정보를 Antora에 전달하기 위해 사용자 정의 값을 허용합니다. 예로는 ``page-aliases``, ``page-layout`` 및 ``page-partial``이 있습니다.

``page-aliases`` 속성을 사용하면 현재 페이지에 대한 대체 리소스 ID를 구성할 수 있습니다. 예를 들어, 페이지의 이전 이름을 가져오려면 다음과 같이 사용합니다:

[source,asciidoc]
----
= Page Title
:page-aliases: old-page-name.adoc
----

사용자 정의 페이지 속성과 달리 ``page-aliases`` 속성은 값이 특정 구문(즉, 쉼표로 구분된 리소스 ID 목록)을 준수해야 합니다. 페이지 별칭을 참조하여 ``page-aliases`` 속성 및 이름이 변경되거나 이동되거나 삭제된 페이지에 대한 참조를 유지하는 데 사용할 수 있는 방법에 대해 알아보세요.

``page-layout`` 속성을 사용하면 현재 페이지에 적용할 UI 템플릿을 지정할 수 있습니다. 예를 들어, 현재 페이지에 홈 레이아웃을 적용하려면 다음과 같이 사용합니다:

[source,asciidoc]
----
= Home Page
:page-layout: home
----

page layout을 참조하여 ``page-layout`` 속성 및 페이지에 적용되는 UI 레이아웃을 정의하는 데 사용할 수 있는 방법에 대해 알아보세요.

유사한 종류의 기능을 구성할 수 있도록 향후 추가 미리 정의된 페이지 속성이 추가될 수 있습니다.

== UI 템플릿에서 페이지 속성 액세스

페이지 속성의 주요 역할 중 하나는 UI 모델을 통해 페이지에 대한 메타데이터를 UI 템플릿에 전달하는 것입니다. 그런 다음 UI 템플릿은 게시된 페이지(즉, HTML)의 메타데이터 채우기부터 UI에서 동작 토글 또는 구성에 이르기까지 다양한 방식으로 페이지 속성이 제공하는 정보를 사용할 수 있습니다.

예를 들어 보겠습니다. 기본 UI에서는 ``toclevels``(즉, 정의된 경우 ``page-toclevels``)이라는 페이지 속성을 사용하여 사이드바 TOC의 깊이를 구성할 수 있습니다.

이 속성을 플레이북(또는 컴포넌트 디스크립터)에서 전역적으로 설정할 수 있습니다.

[source,yaml]
----
asciidoc:
  attributes:
    page-toclevels: 3@
----

후행 @를 추가하면 페이지 헤더에서 속성을 계속 재정의할 수 있습니다. 예를 들면:

[source,asciidoc]
----
= Page Title
:page-toclevels: 2
----

페이지 속성은 UI 모델의 ``page.attributes`` 속성을 통해 액세스할 수 있습니다. 이 속성의 값은 속성 맵입니다.

UI 템플릿에서 ``page-toclevels`` 속성의 값에 액세스하려면 다음을 사용합니다:

[source,hbs]
----
{{page.attributes.toclevels}}
----

그럼 ``page-`` 접두사는 어디에 있나요?

페이지 속성이 UI 모델로 승격되면 ``page-`` 접두사가 이름에서 삭제됩니다. 그래서 우리는 종종 페이지 속성을 짧은 이름(예: toclevels)으로 참조합니다. ``page-`` 접두사는 속성을 페이지 속성으로 식별하는 네임스페이스 역할을 합니다. 따라서 ``page-toclevels``라는 페이지 속성은 UI 모델에서 ``toclevels``(예: ``page.attributes.toclevels``)가 됩니다.

기본 UI가 페이지 속성을 사용하여 페이지네이션을 제어하는 방법을 보여주는 또 다른 예를 살펴보겠습니다. 이 속성은 플레이북이나 컴포넌트 디스크립터에서 전역적으로 설정하는 경우가 많습니다. 그러나 이번에는 페이지에서 속성을 끌 수 없도록 속성을 하드 설정합니다.

[source,yaml]
----
asciidoc:
  attributes:
    page-pagination: ''
----

이제 footer-scripts.hbs 부분 템플릿에서 이 속성이 설정되었는지 확인하고 설정된 경우 페이지네이션 컨트롤을 포함할 수 있습니다.

[source,hbs]
----
{{#unless (eq page.attributes.pagination undefined)}}
<nav class="pagination">
...
</nav>
{{/unless}}
----

값이 truthy인지 확인하는 대신 undefined와 같지 않은지 확인합니다. JavaScript에서 빈 값은 falsy이므로 더 구체적인 조건 선언이 필요합니다. 절 안에서 템플릿은 속성에 next 또는 prev 값이 있는지 확인할 수 있으며, 이는 반대 방향을 끄는 것을 의미합니다.

속성 이름의 ``page-`` 접두사는 UI 모델로 승격시키는 것입니다. 다른 모든 문서 속성은 여전히 UI 모델에서 액세스할 수 있지만 쉽게 액세스할 수는 없습니다. 다음은 UI 모델에서 페이지 속성이 아닌 속성을 참조하는 방법의 예입니다:

[source,hbs]
----
{{#with (resolvePage page.relativeSrcPath model=false)}}
{{./asciidoc.attributes.policy-number}}
{{/with}}
----

``page.relativeSrcPath`` 값을 내장 ``resolvePage`` 도우미에 전달하면 현재 페이지로 해석됩니다. ``model=false`` 옵션은 도우미에게 해석된 페이지의 UI 모델 대신 가상 파일을 반환하도록 지시합니다. 거기서 모든 AsciiDoc 속성은 중첩된 ``asciidoc.attributes`` 속성을 통해 액세스할 수 있습니다.

== 내재적 페이지 속성

Antora는 런타임에 현재 페이지에 대한 기존 메타데이터에서 파생된 여러 읽기 전용 내재적 페이지 속성을 자동으로 설정합니다. 예를 들어, 현재 컴포넌트의 이름은 ``page-component-name`` 속성에서 읽을 수 있습니다.

이러한 속성은 페이지 또는 탐색 파일이 로드(즉, 구문 분석)될 때 정의됩니다. 컴포넌트 디스크립터의 속성이 해석될 때는 아직 할당되지 않으므로 컴포넌트 디스크립터에는 표시되지 않습니다.

내재적 페이지 속성은 Intrinsic Attributes에 나열되어 있습니다. 이러한 속성은 **읽기 전용**이므로 페이지 헤더에서 해당 값을 재정의하면 안 됩니다.