= 표준 Pages 설정

표준 페이지에는 헤더와 본문의 두 부분이 있습니다.

== 페이지 헤더

페이지 헤더는 파일의 첫 번째 줄에서 시작하는 연속된 줄 집합입니다. 헤더는 다음 요소를 캡슐화합니다:

- 필수 페이지 제목
- 페이지 설명 및 작성자 정보와 같은 선택적 메타데이터 속성
- xrefstyle 및 page-aliases와 같은 선택적 내장 속성
- 사용자가 정의한 속성 이름과 값을 가진 선택적 사용자 정의 속성

.페이지 헤더의 일반적인 요소
[source,asciidoc]
----
= Page Title <1>
:description: A description of the page stored in an HTML meta tag. <2>
:sectanchors: <3>
:url-repo: https://my-git-repo.com <4>
:page-tags: name of a tag, name of a tag <5>
----
<1> 파일의 첫 번째 줄에 입력된 필수 페이지 제목
<2> 선택적 내장 description 메타데이터 속성
<3> 선택적 내장 AsciiDoc 속성
<4> 선택적 사용자 정의 AsciiDoc 속성
<5> 선택적 사용자 정의 Antora page- 속성

페이지 제목은 단일 등호 기호로 시작하는 Atx 스타일(한 줄) 문서 제목을 사용하여 정의해야 합니다. Antora는 AsciiDoc에서 한때 지원되었던 레거시 Setext 스타일(두 줄) 문서 제목 구문을 인식하지 않습니다. Setext 스타일 구문을 사용하면 페이지의 xref가 해결되지 않고 AsciiDoc의 다른 기능을 사용할 수 없습니다.

내장 또는 사용자 정의 여부에 관계없이 속성 항목은 각각 자체 줄에 입력해야 합니다. 헤더에는 주석 줄도 포함될 수 있습니다.

페이지 헤더는 하나 이상의 빈 줄을 입력하면 끝납니다.

== 페이지 본문

페이지 헤더는 하나 이상의 빈 줄로 페이지 본문과 구분됩니다. 내용이 포함된 다음 줄은 페이지의 본문을 시작합니다.

[source,asciidoc]
----
= Page Title
:description: A description of the page stored in an HTML meta tag.
:sectanchors:
:url-repo: https://my-git-repo.com
:page-tags: name of a tag, name of a tag
<1>
This is the first line of the page body. <2>

== Section heading

This is a paragraph in a section.
----
<1> 이것은 섹션의 단락입니다.
<2> 빈 줄은 페이지 헤더를 끝냅니다. 빈 줄 다음에 내용이 있는 다음 줄은 페이지의 본문을 시작합니다. 페이지 본문의 첫 번째 줄은 섹션 제목, 단락, 표, include 지시문, 이미지 등과 같은 유효한 AsciiDoc 내용일 수 있습니다.

== 페이지 파일 이름

페이지는 __pages__ 패밀리 디렉터리에 저장됩니다. 페이지의 파일 이름은 URL을 계산하는 데 사용됩니다. 파일 이름이 점(.)으로 시작하거나 파일 확장자 없이 끝나면 Antora는 해당 파일을 무시합니다. 파일 이름이 밑줄(_)로 시작하면 콘텐츠 카탈로그에 추가되지만 Antora는 해당 파일을 게시하지 않습니다.

== 새 표준 페이지 만들기

. 선호하는 IDE 또는 일반 텍스트 편집기에서 새 파일을 엽니다.
. 파일의 첫 번째 줄에 페이지 제목을 입력합니다. 페이지 제목은 등호 기호(=) 하나, 공백 하나, 그리고 제목의 텍스트로 지정됩니다.
+
[source,asciidoc]
----
= The Title of My New Page
----

. 페이지 제목은 유일한 필수 헤더 요소입니다. 헤더 블록과 본문 블록을 하나의 빈 줄로 구분합니다. 내용을 작성합니다.
+
[source,asciidoc]
----
= The Title of My New Page

Welcome to my new page!
----

. pages 디렉터리에 .adoc 확장자로 파일을 저장합니다. 파일 저장 시 사용하는 이름은 페이지의 URL을 계산하는 데 사용됩니다.

표준 페이지를 만들었습니다! Antora를 실행하면 페이지가 HTML 페이지로 변환되어 사이트에 자동으로 게시됩니다.

이 예제에서 만든 페이지는 간단합니다. AsciiDoc를 사용하면 페이지의 헤더는 다양한 기능을 포괄할 수 있고 본문은 복잡한 내용을 처리할 수 있습니다.

[IMPORTANT]
====
**__기억해야 할 핵심 사항__**

페이지는:

- 모듈의 __pages__ 디렉터리에 저장됩니다.
- __.adoc__ 파일 확장자를 가집니다.
- URL 호환 문자만 포함하는 파일 이름을 가집니다.
- 모두 소문자인 파일 이름을 가집니다(선택 사항이지만 권장됨).
- 제목(즉, 문서 제목)이 있습니다.
- 유효한 AsciiDoc 구문을 사용하여 마크업됩니다.
====