= Xref 매크로 및 Page 링크

페이지 링크를 만들려면 다음을 알아야 합니다:

- AsciiDoc xref 매크로를 구조화하고 사용하는 방법
- AsciiDoc xref 매크로에 페이지의 리소스 ID를 할당하는 방법
- 링크할 페이지(대상 페이지)의 리소스 ID
- 링크가 표시될 페이지(현재 페이지)의 리소스 ID

== AsciiDoc xref 매크로

AsciiDoc xref 매크로는 리소스에서 게시 가능한 리소스로 소스 간 상호 참조를 만드는 데 사용됩니다. **상호 참조**(종종 **xref**로 줄여서 표기)라는 용어는 AsciiDoc xref 매크로를 사용하여 게시 가능한 리소스의 소스 파일을 참조하는 것을 의미합니다. xref 매크로는 게시 가능한 페이지, 첨부 파일 또는 때로는 이미지를 지정하는 Antora 리소스 ID를 값으로 받습니다. Antora가 실행되면 xref 매크로와 그 값은 대상 리소스의 게시된 URL에 대한 링크로 변환됩니다.

=== Xref 매크로 구조

그림 1은 xref 매크로의 구조를 보여줍니다.

.그림1. 페이지 참조를 위한 Xref 매크로 구조
image::xref-macro-with-resource-id-for-page.svg[페이지 참조를 위한 Xref 매크로 구조]

최소한 xref 매크로는 매크로의 접두사(pass:[xref:]), **대상 페이지**의 리소스 ID 및 대괄호 쌍([])으로 구성됩니다. 대상 페이지는 현재 페이지에서 참조하는 페이지 소스 파일입니다. 대상 페이지는 현재 페이지의 내용에서 xref 매크로에 리소스 ID를 할당하여 참조됩니다. **현재 페이지**는 대상 페이지를 참조하는 xref 매크로를 포함하는 페이지 소스 파일입니다. 그림 1에 표시된 xref 매크로의 각 부분은 아래에서 더 자세히 설명합니다.

pass:[xref:]::
xref 매크로는 매크로의 이름 xref와 단일 콜론(:)으로 시작합니다.

대상 페이지의 리소스 ID::
xref 매크로는 페이지의 리소스 ID를 값으로 받습니다. 값은 매크로 이름(xref:) 뒤의 콜론 바로 뒤에 입력됩니다. 현재 페이지와 관련하여 대상 페이지의 컴포넌트 버전 및 모듈에 따라 대상 페이지의 리소스 ID 좌표를 얼마나 많이 지정해야 하는지가 결정됩니다. 대상 리소스가 페이지일 때는 리소스 ID에 page$ 패밀리 좌표가 필요하지 않습니다. 또한 대상 페이지의 파일 좌표는 pages 패밀리 디렉토리에서 계산된다는 점을 기억하세요.

#fragment::
프래그먼트는 대상 페이지 내의 섹션, 블록 또는 인라인 위치에 연결되는 요소 ID입니다. 프래그먼트를 딥 링크라고도 합니다. 프래그먼트는 선택 사항입니다. 프래그먼트는 해시 기호(#)로 시작하며 대상 페이지의 리소스 ID 바로 뒤에 입력됩니다. 프래그먼트가 지정되면 대상 페이지의 참조 텍스트(기본값으로 할당되거나 reftext 속성을 사용하여 할당된)가 링크 텍스트로 사용되지 않습니다.

[link text]::
xref 매크로는 대상 페이지의 리소스 ID 끝 또는 프래그먼트가 지정된 경우 프래그먼트 끝에 대괄호([])로 완성됩니다. 이 대괄호 사이에 선택적 텍스트를 입력하거나 비워 둘 수 있습니다. Antora가 xref 매크로와 그 값을 링크로 변환할 때 대괄호 사이에 입력된 텍스트는 사이트에 게시될 때 현재 페이지에 표시됩니다. 매크로의 대괄호 사이에 링크 텍스트가 지정되지 않고 xref 매크로의 값에 프래그먼트가 포함되지 않은 경우 대상 페이지의 기본 참조 텍스트 또는 reftext 속성에 할당된 텍스트가 게시될 때 현재 페이지에 표시됩니다. 대상 페이지의 리소스 ID에 프래그먼트가 추가되고 대괄호 사이에 링크 텍스트가 입력되지 않으면 게시된 대상 페이지의 URL이 표시됩니다.

다음 섹션에서는 단계별로 상호 참조를 만드는 방법을 설명합니다.

== xref 매크로로 링크 만들기

현재 편집 중인 페이지(현재 페이지)에서 페이지(대상 페이지)로의 상호 참조를 만들기 위해 필요한 xref 매크로와 리소스 ID 좌표를 분석해 보겠습니다.

. IDE 또는 텍스트 편집기에서 상호 참조를 만들 페이지를 엽니다. 이 단계와 후속 단계에서는 __satellites.adoc__ 파일을 열었다고 가정해 보겠습니다. __satellites.adoc__는 현재 페이지입니다.
+
.예제 1. satellites.adoc (현재 페이지)
[source,asciidoc]
----
=== Console options

See the
----

. 현재 페이지에서 대상 페이지에 대한 링크를 표시할 내용 흐름의 위치를 선택합니다. xref 매크로의 이름 뒤에 콜론 하나를 입력합니다(xref:).
+
.예제 2. satellites.adoc (현재 페이지)
[source,asciidoc]
----
=== Console options

See the xref:
----

. xref 매크로에 대상 페이지의 리소스 ID를 할당합니다. 예제 3에서는 __modes.adoc__를 대상 페이지로 사용하고 현재 페이지인 __satellites.adoc__와 동일한 컴포넌트 버전과 모듈에 속한다고 가정해 보겠습니다. 따라서 대상 페이지의 파일 좌표만 지정하면 됩니다.
+
.예제 3. satellites.adoc (현재 페이지)
[source,asciidoc]
----
=== Console options

See the xref:modes.adoc
----
+
__modes.adoc__ 페이지의 파일 좌표는 __modes.adoc__입니다. 대상 페이지의 파일 좌표는 pages 디렉토리의 루트에 저장되므로 파일 이름과 파일 확장자로만 구성됩니다.
+
NOTE: __modes.adoc__의 리소스 ID에는 page$ 패밀리 좌표가 포함되지 않습니다. xref 매크로는 패밀리 좌표가 지정되지 않으면 page$라고 가정합니다.

. 대상 페이지의 리소스 ID 바로 뒤에 왼쪽 대괄호([)를 입력한 다음 오른쪽 대괄호(])를 입력하고 그 뒤에 후속 내용을 입력합니다.
+
.예제 4. satellites.adoc (현재 페이지)
[source,asciidoc]
----
=== Console options

See the xref:modes.adoc[] for more options.
----
+
대상 페이지의 참조 텍스트를 링크 텍스트로 사용하려고 하므로 매크로의 대괄호 사이에 어떤 텍스트도 입력하지 않았습니다. Antora가 xref 매크로와 대상 페이지의 리소스 ID를 변환할 때 대상 페이지의 기본 참조 텍스트 또는 reftext 속성에 할당된 텍스트로 링크 텍스트를 자동으로 채울 것입니다.

이것으로 끝입니다! AsciiDoc xref 매크로를 사용하여 현재 페이지(__satellites.adoc__)에서 대상 페이지(__modes.adoc__)로의 상호 참조를 만들었습니다.

== 더 알아보기

Create Page Links에서는 대상 페이지가 하위 디렉토리에 저장되어 있거나 다른 모듈, 컴포넌트 또는 버전에 속할 때 페이지에 대한 xref를 만드는 방법을 보여줍니다.

xref 매크로는 첨부 파일에 대한 링크도 만듭니다.
