= 도움 받기

Antora는 여러분이 문서를 작성하고 발행하는 데 도움을 주도록 설계되었습니다. 하지만 여러분의 피드백 없이는 이 목표를 완전히 실현할 수 없습니다! 아래 제공된 커뮤니케이션 채널을 사용하여 이슈를 보고하고, 질문하고, 아이디어를 공유하거나 이 프로젝트의 다른 측면에 대해 논의하는 것을 권장합니다.

== 채팅

프로젝트 채팅은 모든 Antora 사용자에게 권장되는 주요 의사소통 수단입니다. 이 정책은 프로젝트의 지속 가능성을 유지하는 데 도움이 됩니다.

도움을 요청하거나, 피드백을 공유하거나, 프로젝트 유지 관리자 및 커뮤니티 구성원들과 실시간으로 아이디어를 교환하고 싶다면 프로젝트 채팅에 참여해 주세요.

* link:https://chat.antora.org/[채팅 (Zulip)]

채팅은 주제별로 스트림으로 나뉘어 있습니다. 이러한 분할은 대화를 체계적으로 유지하고 팔로우할 주제를 필터링할 수 있게 해줍니다. 처음 참여할 때는 주제가 어디서 논의되고 있는지 익숙해지는 데 몇 분 정도 시간을 투자하세요.

IMPORTANT: Antora에 대한 도움을 요청하기 위해 유지 관리자에게 직접 메시지를 보내지 마세요. 프로젝트 유지 관리자는 1대1 지원을 제공하지 않습니다. 모든 지원은 공개 스트림에서 이루어져야 하며, 대부분 `#users` 스트림에서 이루어집니다. 직접 메시지는 개인적인 문제에 한해서만 사용해야 합니다.

새 주제를 시작하기 전에 필터 또는 검색 기능을 사용하여 기존 주제를 찾아보세요. 이미 진행된 토론에서 찾고 있는 정보를 발견할 수 있을 것입니다. 귀하의 게시물 주제와 일치하는 진행 중인(즉, 해결되지 않은) 토론을 찾으면 해당 토론에 자유롭게 참여하세요.

질문에 대한 답을 찾는 기존 주제를 찾을 수 없거나 이미 해결된 것으로 표시된 경우 새 주제를 시작할 수 있습니다. 새 주제를 만들기 전에 적절한 스트림을 선택해 주세요. 어디에 게시해야 할지 확실하지 않다면 `#users` 스트림에 새 주제를 만들면 필요한 경우 관리자가 재분류할 것입니다.

스트림을 선택한 후 "New Topic"을 클릭하고, 제목을 입력하고, 게시물을 작성한 다음 "Send"를 클릭하세요. "New Topic"을 클릭한 후에도 스트림을 선택할 수 있습니다.

프로젝트 채팅의 토론은 보관되며 공개됩니다. 로그가 무기한 저장된다는 보장은 없지만, 허용되는 한 오래 보관할 계획입니다.

프로젝트 채팅은 1대1 지원이 아닙니다. 공개 공간에 있다는 점을 기억하세요. 사용자들은 자발적으로 프로젝트 채팅에 참여합니다. 그들의 시간과 관심사를 존중해 주세요.

IMPORTANT: 메시지를 작성할 때 a) 해당 주제가 절대적으로 그 사람의 주의를 요구하거나 b) 그 사람이 이미 주제에 답변했고 당신과 상호 작용하고 있는 경우가 아니라면 @ 멘션을 사용하지 마세요. @ 멘션을 사용하여 질문에 주의를 끄는 것은 그 사람에게 예의 바르지 않으며 다른 참여자들에게도 공정하지 않습니다. 커뮤니티 전체에 메시지를 자유롭게 게시할 수 있습니다(@ 멘션 없이). 누군가 응답할 내용이 있다면 시간이 있을 때 응답할 것입니다. @_ 접두사를 사용하여 알림 없이 누군가를 언급할 수 있으며, 이는 허용되는 행동으로 간주됩니다.

== 이슈

이슈 트래커는 소프트웨어 변경 사항을 추적하고 릴리스를 계획하는 데 사용됩니다. 이슈 트래커는 지원 포털이 아닙니다. 대신, 이슈 트래커는 문제 보고(검증 가능한 버그, 회귀, 보안 취약점)와 새로운 기능 요청을 위해 예약되어 있습니다. 소프트웨어 변경이 필요하다고 확신하지 않는다면 대신 채팅에 게시해 주세요.

* link:https://gitlab.com/antora/antora/-/issues[이슈 트래커 (GitLab)]

소프트웨어에 대한 중요한 변경 사항이나 프로젝트에 대한 결정은 모두 이슈 트래커에 기록되어야 합니다.

== 트위터

Antora에 대한 경험을 공유하거나 홍보하고 싶다면 소셜 미디어에 게시하는 것을 권장합니다. 트위터에서 Antora에 대해 이야기할 때 프로젝트의 공식 계정을 언급할 수 있습니다:

* link:https://x.com/antoraproject[@antoraproject] — 트위터의 공식 Antora 계정.

또한 link:https://x.com/hashtag/antora?src=hash[#antora] 해시태그를 사용하여 프로젝트를 홍보하거나 다른 사람들의 이야기를 발견할 수 있습니다.

== 코드 및 콘텐츠 기여

유지 관리자들이 프로젝트를 개선하는 데 도움을 주고 싶다면 link:https://gitlab.com/antora/antora/blob/main/contributing.adoc[Antora 기여 가이드라인]을 확인해 보세요.