== 컴포넌트 버전에 탐색 파일 할당

다음 페이지에서 배울 수 있는 내용은 다음과 같습니다:

* [*] __antora.yml__ 파일에서 nav 키를 사용하여 탐색 파일을 등록하는 방법.
* [*] 등록 순서가 컴포넌트 버전의 페이지 메뉴에 미치는 영향.

=== nav 키

nav 키는 선택 사항입니다. 컴포넌트 버전의 __antora.yml__ 파일에 설정되며 탐색 파일 목록을 허용합니다. 각 값은 __antora.yml__을 기준으로 탐색 파일(예: __modules/module-directory/nav-file.adoc__)의 경로를 지정합니다.

.예제 1. 두 개의 탐색 파일을 등록하는 antora.yml
[source,yaml]
----
name: colorado
title: Colorado ∆
version: '5.6'
nav: <1>
- modules/get-started/nav.adoc <2>
- modules/ROOT/nav.adoc <3>
----
<1> nav 키는 별도의 행에 입력되어야 하며 바로 뒤에 콜론(:)이 와야 합니다.
<2> get-started 모듈 디렉터리에 있는 탐색 파일을 등록하는 값입니다.
<3> ROOT 모듈 디렉터리에 있는 탐색 파일을 등록하는 값입니다.

nav 아래에 나열된 각 값은 다음과 같이 구성되어야 합니다:

- 값을 들여쓰기하지 마세요.
- 각 값을 별도의 행에 입력하세요.
- 각 값을 하이픈(-)으로 시작한 다음 공백을 넣으세요.
- 공백 다음에 antora.yml 파일의 위치를 기준으로 개별 탐색 파일의 경로를 입력하세요.

탐색 파일은 nav 키에 할당되면 **등록됩니다**. 등록된 탐색 파일의 내용만 컴포넌트 버전의 페이지 메뉴로 조합되어 게시됩니다. 값의 순서는 탐색 파일의 내용이 사이트의 컴포넌트 버전 페이지 메뉴에 표시되는 순서를 결정합니다.

=== 더 알아보기

- Navigation Assembly
- Navigation Files and Lists
- Navigation File Locations
- Register Navigation Files