= Configure Component Versions - Assign Attributes to a Component Version

해당 컴포넌트 버전의 __antora.yml__ 파일에서 선언하여 컴포넌트 버전의 모든 페이지에 속성을 적용할 수 있습니다.

== 컴포넌트 버전 속성

컴포넌트 버전 디스크립터에 정의된 속성을 컴포넌트 버전 속성이라고 합니다. **컴포넌트 버전 속성**은 내장, 사용자 정의 및 페이지 속성일 수 있습니다. 이러한 속성은 속성 우선 순위 규칙에 따라 컴포넌트 버전의 모든 페이지에 적용되고 사용할 수 있습니다(설정되지 않은 경우 사용할 수 없음). 속성이 이전에 사이트의 플레이북에서 하드 설정 또는 하드 미설정된 경우 **컴포넌트 버전 디스크립터에서의 선언은 영향을 미치지 않습니다**.

[NOTE]
====
__**플레이북 파일 대 컴포넌트 버전 디스크립터 파일**__

속성은 플레이북 파일과 컴포넌트 버전 디스크립터 파일 모두에서 동일한 구조와 구문을 사용하여 선언됩니다.

플레이북은 사이트, 콘텐츠 소스 및 UI URL을 구성하는 곳입니다. 플레이북 파일에는 일반적으로 파일 이름에 playbook이라는 단어가 포함됩니다(예: __antora-playbook.yml__ 또는 __local-antora-playbook.yml__).

컴포넌트 버전 디스크립터는 컴포넌트 버전의 이름, 버전, 메타데이터, 속성 및 탐색 목록을 구성하는 곳입니다. 컴포넌트 버전 디스크립터의 파일 이름은 항상 __antora.yml__입니다.

확장 작성자의 경우. 컴포넌트 디스크립터에 AsciiDoc 속성이 정의되어 있지 않으면 컴포넌트 버전 객체의 asciidoc 속성은 사이트 전체 AsciiDoc 구성 객체(즉, siteAsciiDocConfig)를 참조합니다. 컴포넌트 버전 속성을 수정할 계획이라면 먼저 asciidoc 속성의 값이 사이트 전체 객체와 일치하는지(===) 확인하고 그렇다면 깊은 복사본을 만드세요.
====

== antora.yml에서 속성 설정

컴포넌트 버전 속성은 컴포넌트 버전의 antora.yml 파일에 설정됩니다. 먼저 asciidoc 및 attributes 키를 설정해야 합니다. 그런 다음 각 컴포넌트 버전 속성은 attributes 아래에 키-값 쌍으로 자체 행에 입력됩니다.

.예제 1. antora.yml에서 속성 선언
[source,yaml]
----
name: light
title: Data Light
version: '2.3'
asciidoc: <1>
  attributes: <2> 
    table-caption: Data Set <3> 
    hide-uri-scheme: '' <4>
    page-level: Advanced <5>
    page-category: Statistics; Cloud Infrastructure <6>
nav:
- modules/ROOT/nav.adoc
----
<1> 새 줄에 asciidoc을 입력하고 콜론(:)을 입력한 다음 kbd:[Enter] 키를 누릅니다.
<2> asciidoc 키 바로 아래 줄에 attributes 키를 중첩합니다. attributes를 입력하고 콜론(:)을 입력한 다음 kbd:[Enter] 키를 누릅니다.
<3> 각 컴포넌트 버전 속성은 attributes 키 아래에 중첩되고 자체 행에 정의됩니다. 속성의 이름을 입력하고 콜론(:)을 입력합니다. 콜론 뒤에 스페이스바를 한 번 누른 다음 속성의 값을 입력합니다.
<4> 명시적 값을 지정하지 않고 속성을 설정하려면 값 부분에 연속된 작은따옴표 두 개('')를 입력하여 빈 문자열을 할당합니다. 특정 내장 속성의 경우 빈 값은 속성에 따라 기본값과 동일하지만 속성에 따라 다릅니다. 이 경우 일반적으로 부울 값 true가 작동하지만 AsciiDoc의 속성 값은 문자열이므로 문자열 값 'true'로 강제 변환될 가능성이 있습니다.
<5> 사용자 정의 페이지 속성을 선언하려면 page-와 속성의 이름을 입력한 다음 콜론(:)을 입력합니다. 콜론 뒤에 스페이스바를 한 번 누른 다음 속성의 값을 입력합니다.
<6> 속성에 여러 개의 독립적인 값이 있는 경우 세미콜론(;)으로 각 값을 구분합니다.

설정된 컴포넌트 버전 속성은 컴포넌트 버전에 속한 모든 페이지에 적용되고 사용할 수 있습니다. page-level과 같은 사용자 정의 속성의 값은 속성 참조 구문(예: \{page-level})을 사용하여 페이지에 표시할 수 있습니다.

예제 1의 속성은 모두 **하드 설정**되어 있습니다. 하드 설정된 컴포넌트 버전 속성은 페이지에서 재정의할 수 없습니다. 기본적으로 속성에 속성을 미설정하기 위해 예약된 값(즉, false 또는 ~)이 할당되지 않고 수정자(즉, @)로 끝나지 않는 값이 할당되면 하드 설정됩니다. 페이지에서 컴포넌트 버전 속성을 수정하거나 미설정할 수 있도록 하려면 컴포넌트 버전 속성을 소프트 설정해야 합니다.

=== 소프트 설정 속성

소프트 설정된 컴포넌트 버전 속성은 페이지에서 재정의할 수 있습니다. 속성은 값 끝에 @ 수정자를 붙여 소프트 설정됩니다.

.예제 2. 속성에 소프트 설정 우선 순위 할당
[source,yaml]
----
asciidoc:
  attributes:
    table-caption: Data Set@ <1>
    hide-uri-scheme: '@' <2>
----
<1> 명시적 값이 할당된 속성을 소프트 설정하려면 값 끝에 @ 수정자를 붙입니다.
<2> 내장 속성의 기본값 또는 부울 속성의 경우 빈 문자열 값을 소프트 설정하고 할당하려면 여는 작은따옴표를 입력한 다음 @ 수정자를 입력하고 닫는 작은따옴표(')를 입력합니다.

예제 2의 컴포넌트 버전 속성은 소프트 설정되었으므로 페이지에서 해당 값을 수정하거나 미설정할 수 있습니다.

=== 다른 속성의 값 삽입

동일한 __antora.yml__ 파일의 앞부분에 설정된 모든 컴포넌트 버전 속성의 값 또는 모든 사이트 속성의 값은 AsciiDoc 속성 참조(예: \{site-title}, \{page-level})를 사용하여 컴포넌트 버전 속성의 값에 삽입할 수 있습니다.

.예제 3. 다른 컴포넌트 버전 속성의 값을 참조하는 컴포넌트 버전 속성
[source,yaml]
----
name: light
title: Data Light
version: '2.3'
asciidoc:
  attributes:
    table-caption: Data Set
    url-plugins: https://example.com/plugins
    url-data-plugin: {url-plugins}/data-light
nav:
- modules/ROOT/nav.adoc
----

컴포넌트 버전 속성은 페이지 속성의 값에서도 참조할 수 있습니다.

속성 값에서 속성 참조 대체를 방지하려면 참조 앞에 백슬래시를 삽입하세요(예: pass:[\{not-substituted}]). 이 경우 속성 참조는 대체되지 않고 백슬래시는 생략됩니다.

== antora.yml에서 속성 미설정

속성을 미설정할 수도 있습니다. 컴포넌트 버전 속성은 예약된 물결표 기호(~) 값이 할당될 때 하드 미설정됩니다. 각 속성은 attributes 키 아래에 키-값 쌍으로 자체 행에 입력됩니다.

.예제 4. 속성 하드 미설정
[source,yaml]
----
asciidoc:
  attributes:
    table-caption: ~ <1>
    hide-uri-scheme: ~ <2>
----
<1> 속성을 하드 미설정하려면 물결표 기호(~)를 할당합니다. 는 YAML에서 사이트 속성을 하드 미설정하는 예약된 값인 nil의 약어입니다.
<2> 부울 속성은 물결표 기호()가 할당될 때도 하드 미설정됩니다.

하드 미설정된 컴포넌트 버전 속성은 페이지에서 재정의할 수 없습니다. 컴포넌트 버전 속성이 하드 미설정되면 해당 동작이 해제되고 컴포넌트 버전의 페이지에서 사용할 수 없습니다.

=== 소프트 미설정 속성

소프트 미설정된 컴포넌트 버전 속성은 페이지에서 재정의할 수 있습니다. 속성은 예약된 값 false를 할당하여 소프트 미설정됩니다.

.예제 5. 속성에 소프트 미설정 우선 순위 할당
[source,yaml]
----
asciidoc:
  attributes:
    table-caption: false <1>
    hide-uri-scheme: false <2>
----
<1> 속성을 소프트 미설정하려면 false 값을 할당합니다.
<2> 부울 속성은 false가 할당될 때도 소프트 미설정됩니다.

예제 5의 속성은 소프트 미설정되었으므로 페이지에서 재설정할 수 있습니다.

== 우선 순위 규칙

Antora는 먼저 사이트 속성에 할당된 우선 순위를 고려합니다. __antora.yml__ 파일에 선언된 속성은 플레이북에서 동일한 속성이 하드 설정되거나 하드 미설정된 경우 해당 속성을 재정의할 수 없습니다. 컴포넌트 버전 속성은 사이트 속성이 소프트 설정되거나 미설정된 경우에만 사이트 속성을 재정의할 수 있습니다.

컴포넌트 버전 속성이 선언되면 페이지에서 각 속성을 사례별로 재설정하거나 미설정할 수 있는지 여부를 제어할 수 있습니다. 속성이 소프트 설정되거나 미설정되었거나 이전에 플레이북에 정의되지 않았다고 가정하면 하드 설정되거나 하드 미설정된 컴포넌트 버전 속성은 페이지에서 변경할 수 없습니다. 그러나 소프트 설정 및 미설정된 컴포넌트 버전 속성은 페이지에서 재정의할 수 있습니다.

. 끝에 @ 수정자가 없는 문자열 값(예: value 또는 '')을 사용하여 컴포넌트 버전 속성을 하드 설정하면 페이지에서 속성을 변경하거나 미설정할 수 없습니다.
. 끝에 @ 수정자가 있는 문자열 값(예: value@ 또는 '@')을 사용하여 컴포넌트 버전 속성을 소프트 설정하면 페이지에서 속성을 변경하거나 미설정할 수 있습니다.
. 물결표 기호(~)를 사용하여 컴포넌트 버전 속성을 하드 미설정하면 페이지에서 속성을 설정할 수 없습니다.
. false 값을 사용하여 컴포넌트 버전 속성을 소프트 미설정하면 페이지에서 속성을 설정할 수 있습니다.

컴포넌트 버전 속성이 사이트 속성 및 페이지 속성과 어떻게 상호 작용하는지 자세히 알아보려면  Assign Attributes to a Site 및 Antora의 AsciiDoc Attributes를 참조하세요.

== 내재적 컴포넌트 버전 속성

Antora는 컴포넌트 버전 디스크립터 파일의 대부분의 키에서 내재적 페이지 속성을 정의합니다. 예를 들어, Antora는 내장 속성 page-component-title을 설정하고 title 키로 지정된 값을 할당합니다. Antora가 자동으로 선언하는 페이지 속성의 전체 목록은 내재적 페이지 속성을 참조하세요.

Antora는 또한 기본적으로 sectanchors와 같은 일부 내장 AsciiDoc 속성을 설정합니다. 자세한 내용은 Site and configuration attributes를 참조하세요.

CAUTION: 일부 내장 AsciiDoc 속성은 Antora 환경에서 적용되지 않습니다. 이러한 속성에는 data-uri, allow-uri-read, docinfo, linkcss, noheader, nofooter, webfonts 및 outfilesuffix가 포함됩니다. 이러한 속성을 설정하면 효과가 없거나 Antora가 오작동할 수 있습니다. imagesdir와 같은 다른 속성은 Antora에 의해 자동으로 설정되며 재정의할 수 없습니다.
