= 제목 커스터마이징

title 키는 컴포넌트 버전(그리고 관련하여 컴포넌트)에 제목을 할당하는 데 사용됩니다. 제목은 일반적으로 제품, 프로젝트 또는 주제의 적절한 이름인 컴포넌트 버전의 공식적이고 사용자 대면적인 텍스트입니다. 제목은 기본 UI의 탐색 패널에서 버전을 정렬하는 데에도 사용됩니다.

제목은 페이지 및 리소스 ID 또는 페이지 URL의 컴포넌트 이름 세그먼트에 영향을 미치지 않습니다.

== title 키

title 키는 선택 사항입니다. 이 키는 컴포넌트 버전의 __antora.yml__ 파일에 설정됩니다. 값은 컴포넌트 버전 페이지 메뉴, 컴포넌트 버전 선택기 및 컴포넌트 버전 페이지의 첫 번째 브레드크럼 위치를 포함하여 컴포넌트 또는 컴포넌트 버전이 참조되는 곳마다 참조 UI에서 사용됩니다.

title은 컴포넌트 버전별로 설정되지만 거의 항상 컴포넌트의 모든 버전에서 동일해야 합니다. Antora는 최신 버전의 title을 컴포넌트의 제목으로 사용합니다. 브레드크럼 탐색과 같이 특정 버전을 볼 때는 해당 버전의 title이 표시됩니다. 버전 간에 title이 다르면 독자가 혼란스러울 수 있습니다. 새로운 버전에서 title을 변경해야 하고 이전 버전을 업데이트하지 않으려는 경우 UI 템플릿을 사용자 지정하여 항상 최신 버전의 title을 사용할 수 있습니다.

title이 설정되지 않은 경우 참조 UI는 대신 컴포넌트 이름(name 키의 값)을 사용합니다. name과 달리 title의 값에는 공백, 대문자 및 더 넓은 범위의 문자(예: SUSE Manager, APIkit)가 포함될 수 있습니다.

.antora.yml
[source,yaml]
---- 
name: colorado
title: Colorado ∆
version: '5.6'
----

이 키는 프로젝트 이름에 공백이나 Antora의 페이지 및 리소스 ID를 깨뜨리는 문자가 포함되어 있거나, 웹 서버 간 이식성을 방해하거나, URL에 권장되지 않는 경우에 유용합니다. 또한 프로젝트 이름이 변경되면 title 키의 값을 변경할 수 있지만 페이지 및 리소스 ID를 업데이트하거나 URL을 리디렉션할 필요가 없습니다.

== 컴포넌트 버전에 title 할당

이전에 컴포넌트 이름과 버전을 할당하는 방법을 배운 __antora.yml__ 예제를 확장해 보겠습니다. 프로젝트의 공식 이름은 Silver Leaf이고 팀은 이 이름을 UI에 표시하려고 합니다. name에는 공백이 포함될 수 없으므로 컴포넌트 버전의 __antora.yml__ 파일에 title을 설정해 보겠습니다.

. 선택한 텍스트 편집기 또는 IDE에서 컴포넌트 버전의 __antora.yml__ 파일을 엽니다.
+
.예제2. silver-leaf 7.1 컴포넌트 버전에 대한 antora.yml
[source,yaml]
----
name: silver-leaf
version: '7.1'
----

. 새 줄에 title을 입력하고 바로 뒤에 콜론(:)을 입력합니다.

. 콜론 뒤에 공백을 삽입한 다음 title에 할당하려는 값을 입력합니다.
+
[source,yaml]
----
name: silver-leaf
title: Silver Leaf
version: '7.1'
----

. 파일을 저장합니다.

이제 UI에는 컴포넌트 버전 페이지 메뉴, 컴포넌트 버전 선택기 및 페이지 브레드크럼에 Silver Leaf가 표시됩니다.
