= 표시 버전 커스터마이징

display_version 키는 버전 식별자가 대문자, 기호 또는 공백을 포함할 때 참조 UI에서 프레젠테이션 목적으로만 사용됩니다. 리소스 ID, 게시 가능한 리소스 URL의 버전 세그먼트 또는 컴포넌트 버전이 정렬되는 방식에는 영향을 미치지 않습니다.

== display_version 키

display_version 키는 선택 사항입니다. 컴포넌트 버전의 __antora.yml__ 파일에 설정되며 컴포넌트 버전 선택기와 페이지 버전 선택기를 포함하여 버전이 표시되는 곳마다 참조 UI에서 사용됩니다.

display_version이 설정되지 않은 경우 참조 UI는 version 키로 대체됩니다. version과 달리 display_version의 값에는 공백, 대문자 및 대부분의 문자(예: 3.0 Beta, RED WREN!, rawhide)가 포함될 수 있습니다.

.예제 1.antora.yml
[source,yaml]
----
name: colorado
title: Colorado ∆
version: '5.6'
display_version: '5.6 EOL' <1>
----
<1> 값이 숫자로 시작하면 작은따옴표(')로 묶습니다.

display_version 키는 버전에 Antora의 리소스 ID를 깨뜨리거나 웹 서버 간 이식성을 방해하며 URL에 권장되지 않는 공백이나 문자가 포함된 경우에 사용해야 합니다. display_version의 값이 게시 가능한 리소스 URL과 리소스 ID에 영향을 미치지 않기 때문에 컴포넌트 버전이 사전 릴리스, 버전이 없거나 보관된 경우에 유용합니다.

TIP: prerelease 키는 추가적인 UI 라우팅, 정렬 및 프레젠테이션 기능을 제공합니다. 두 키가 모두 설정된 경우 UI에 display_version 키의 값이 표시되지만, 사전 릴리스 식별자에서 생성된 계산된 사전 릴리스 버전이 정렬 및 라우팅에 사용됩니다.

Antora가 display_version 키를 사용하는 방법에 대해 자세히 알아보고 다른 버전 패싯(실제 버전, 사전 릴리스 버전 및 기호 버전)과 비교하려면 버전 패싯을 참조하세요.

== 컴포넌트 버전에 display_version 할당

이전에 컴포넌트 이름과 버전을 할당하는 방법을 배운 __antora.yml__ 예제를 확장해 보겠습니다. __Silver Leaf__ 프로젝트 팀은 버전 번호와 함께 버전 코드 이름을 UI에 표시하려고 합니다. version에는 공백이 포함될 수 없으므로 컴포넌트 버전의 __antora.yml__ 파일에 display_version을 설정해 보겠습니다.

. 선택한 텍스트 편집기 또는 IDE에서 컴포넌트 버전의 __antora.yml__ 파일을 엽니다.
+
.예제 2. silver-leaf 7.1 컴포넌트 버전에 대한 antora.yml
[source,yaml]
----
name: silver-leaf
title: Silver Leaf
version: '7.1'
----

. 새 줄에 display_version을 입력하고 바로 뒤에 콜론(:)을 입력합니다.

. 콜론 뒤에 공백을 삽입한 다음 display_version에 할당하려는 값을 입력합니다. 값이 숫자로 시작하므로 작은따옴표(')로 묶습니다.
+
[source,yaml]
----
name: silver-leaf
title: Silver Leaf
version: '7.1'
display_version: '7.1 Spiny'
----

. 파일을 저장합니다.

이제 UI에는 컴포넌트 버전 선택기와 페이지 버전 선택기에 __7.1 Spiny__가 표시됩니다.
