== 버전 없는 컴포넌트 정의

프로젝트나 프로세스를 문서화할 때 버전이 지정되지 않는 경우가 있습니다. 예를 들어, 호스팅되는 기술 서비스와 팀 핸드북은 현재 서비스나 프로세스가 어떻게 작동하는지를 나타내는 콘텐츠만 있으면 될 수 있습니다. 이때 물결표 ~라는 예약된 버전 값이 사용됩니다.

=== version 키에 ~ 할당

버전이 없는 컴포넌트 버전을 정의하려면 version 키에 물결표 ~를 할당하세요. ~는 동일한 효과를 가진 값 null의 약어입니다.

.예제 1. 버전이 없는 컴포넌트 버전에 대한 antora.yml
[source,yaml]
----
name: component-name
version: ~ <1>
----
<1> 새 줄에 키 version을 입력하고 바로 뒤에 콜론과 공백(: )을 입력합니다. 그런 다음 값 ~를 입력합니다.

Antora는 명명된 버전이나 의미 있는 버전을 가진 컴포넌트 버전에 적용하는 것과 동일한 동작과 출력 규칙을 버전이 없는 컴포넌트 버전에 적용하지 않습니다. 예를 들어, Antora는 버전이 없는 컴포넌트 버전의 게시 가능한 리소스 URL(예: __/component-name/module-name/page-name.html__)에 버전 세그먼트를 포함하지 않습니다.

=== 동작 및 출력

버전 관리는 Antora의 작동 방식의 중심이기 때문에 컴포넌트 버전에는 version 키가 필요합니다. 버전에 의해 영향을 받는 동작과 출력 규칙은 Antora가 버전을 사용하는 방법에 설명되어 있습니다. 그러나 Antora는 일부 컴포넌트에 버전이 지정되지 않거나 실제 버전과 함께 위치한 버전이 없는 버전이 있다는 사실을 고려합니다. version 키에 ~가 할당되어 컴포넌트 버전을 버전이 없는 것으로 정의하면 Antora는 다음과 같이 동작합니다:

- 버전이 없는 컴포넌트 버전을 동일한 컴포넌트에 속하는 다른 버전보다 위에 정렬합니다.
- 컴포넌트의 최신 버전 또는 prerelease 키가 설정된 경우 컴포넌트의 최신 사전 릴리스 버전으로 식별합니다.
- UI 메뉴에서 표시 목적으로 런타임에 대체 값 default를 display_version 키에 할당합니다. 다음의 경우는 예외입니다:
  ** __antora.yml__에서 display_version 키에 값이 할당된 경우, 또는
  ** prerelease 키에 식별자가 할당되고 __antora.yml__에 display_version 키가 설정되지 않은 경우, 런타임에 Antora는 식별자를 display_version 키에 할당합니다.
- latest_version_segment_strategy가 ``redirect:from``이 아닌 한, 플레이북에 ``latest_version_segment`` 키 또는 ``latest_prerelease_version_segment`` 키가 설정되어 있더라도 버전이 없는 컴포넌트 버전의 게시 가능한 리소스 URL에 버전 세그먼트를 추가하지 않습니다.

[TIP]
====
**__UI 및 확장 개발자__**

컴포넌트 버전이 버전이 없는 것으로 정의되면:

  - 예약된 버전 값 ~ 또는 null이 강제로 내부적으로 빈 문자열로 저장됩니다.
  - 버전 세그먼트가 pub.url 또는 out.path에 추가되지 않습니다.
====

=== 버전이 없는 리소스 참조

버전이 없는 컴포넌트 버전은 종종 유일한 버전이거나 항상 컴포넌트의 최신 버전이기 때문에 Antora는 버전 좌표를 지정하지 않는 다른 컴포넌트에서 발생하는 모든 들어오는 참조를 자동으로 라우팅합니다. 그러나 드물게 다른 컴포넌트 버전에서 버전이 없는 사전 릴리스를 참조하는 경우와 같이 리소스 ID(예: pass:[xref:_@component:module:file.adoc[]])의 버전 좌표로 예약된 키워드 _(밑줄)를 사용하여 버전이 없는 컴포넌트 버전을 참조할 수 있습니다.