= 컴포넌트 버전 정의

이 페이지에서는 다음을 배웁니다:

* [x] __antora.yml__ 파일이 충족해야 하는 요구 사항.
* [x] name 키에 유효한 값을 할당하는 방법.
* [x] version 키에 유효한 값을 할당하는 방법.
* [x] __antora.yml__ 파일에서 추가 키와 값을 정의하는 방법.

ASSUMPTIONS: 컴포넌트 버전이 무엇인지, __antora.yml__의 목적이 무엇인지 이해합니다.

== antora.yml 요구 사항

컴포넌트 버전 디스크립터 파일은 다음 요구 사항을 충족해야 합니다:

- __antora.yml__이라는 이름이어야 합니다.
- 유효한 YAML로 작성되어야 합니다.
- 유효한 값을 가진 name 키를 포함해야 합니다.
- 유효한 값을 가진 version 키(플레이북의 콘텐츠 소스에서 상속되지 않는 한)를 포함해야 합니다.
- modules 디렉터리와 동일한 디렉터리 수준에 저장되어야 합니다.

다음 섹션에서는 __antora.yml__ 파일을 만들고 name 및 version 키에 값을 할당하여 컴포넌트 버전을 정의하는 방법에 대한 지침을 제공합니다. name과 version의 목적, Antora가 이를 사용하는 방법, 특정 요구 사항 및 더 많은 사용 예에 대한 자세한 정보는 Name Key와 Version Key를 참조하세요.

== 컴포넌트 버전에 이름과 버전 할당

Silver Leaf 프로젝트의 컴포넌트 버전을 정의하는 antora.yml 파일을 만들어 봅시다. 이 예제에서는 Silver Leaf 프로젝트의 컴포넌트 버전을 만들 것입니다. 컴포넌트 이름은 silver-leaf가 되고 버전은 7.1이 됩니다.

. 텍스트 편집기 또는 IDE에서 새 파일을 엽니다.

. 첫 번째 줄에 name을 입력하고 바로 뒤에 콜론(:)을 입력합니다.

. 콜론 뒤에 kbd:[Spacebar]를 눌러 공백을 삽입한 다음 name에 할당하려는 값을 입력합니다. name 키는 값에 특정 문자나 공백을 허용하지 않습니다. 자세한 내용은 name 요구 사항을 참조하세요.
+
[source,yaml]
----
name: silver-leaf
----

. 값 끝에서 kbd:[Enter]를 눌러 다음 줄로 이동합니다.

. version을 입력하고 바로 뒤에 콜론(:)을 입력한 다음 kbd:[Spacebar]를 눌러 공백을 삽입합니다.

. version에 할당하려는 값을 입력합니다. 이 예제에서는 값이 숫자로 해석되지 않도록 작은따옴표(') 세트로 묶여 있습니다.
+
[source,yaml]
----
name: silver-leaf
version: '7.1'
----
+
version 키는 값에 특정 문자나 공백을 허용하지 않습니다. 자세한 내용은 version 요구 사항을 참조하세요.

. 파일을 __antora.yml__로 콘텐츠 소스 루트에 저장합니다. __antora.yml__ 파일은 컴포넌트 버전의 콘텐츠 파일이 포함된 __modules__ 디렉터리와 인접해야 합니다.

이제 일련의 소스 파일을 컴포넌트 버전과 연결했습니다! Antora가 실행되면 표준 디렉터리 세트에 저장된 모든 소스 파일에 컴포넌트 이름 silver-leaf와 버전 7.1이 할당됩니다. 이러한 값은 컴포넌트 버전의 소스 파일에서 생성된 게시 가능한 리소스의 리소스 ID 좌표와 URL에 사용됩니다.

TIP: 컴포넌트의 여러 버전을 정의하는 경우 컴포넌트 이름을 선언할 때 항상 동일한 대소문자를 사용해야 합니다. 대소문자가 다른 경우(예: Silver-Leaf 대 silver-leaf) Antora는 이를 다른 컴포넌트로 처리합니다. 더 많은 예제와 값 요구 사항은 Name Key와 Version Key를 참조하세요.

== 선택적 antora.yml 키

컴포넌트 버전 디스크립터를 사용하여 추가 메타데이터를 할당하고, 컴포넌트 버전을 사전 릴리스로 지정하고, AsciiDoc 속성을 적용하고, 컴포넌트 버전의 탐색 목록과 시작 페이지를 등록할 수 있습니다.

[cols="1,6"]
|===
|선택적 키 |설명
|asciidoc.attributes
|asciidoc 키는 attributes 키와 중첩된 키-값 쌍 목록을 허용합니다. attributes 아래에 나열된 키-값 쌍은 내장 및 사용자 정의 AsciiDoc 속성(예: idseparator: '-')과 페이지 속성을 나타냅니다. __antora.yml__의 속성은 컴포넌트 버전에 속하는 모든 페이지와 리소스(해당되는 경우)에 적용됩니다.

|display_version
|참조 UI의 컴포넌트 버전 선택기와 페이지 버전 선택기에서 프레젠테이션 목적으로만 사용되는 버전 식별자입니다. display_version은 빈 공백, 대문자 및 대부분의 문자(예: 3.0 Beta, RED WREN!)를 허용합니다.

|nav
|탐색 파일 목록을 허용합니다. nav 키 아래에 등록된 탐색 파일(예: nav.adoc)은 컴포넌트 버전의 페이지 메뉴에 사용됩니다.

|prerelease
|컴포넌트 버전을 사전 릴리스 버전으로 지정하고 기본 라우팅 규칙을 비활성화합니다. 키는 버전 좌표나 버전 URL 세그먼트에 영향을 주지 않고 version에 사전 릴리스 식별자(예: -alpha.2)를 추가할 수 있습니다.

|start_page
|컴포넌트 버전의 홈 페이지로 페이지를 지정합니다. 기본적으로 Antora는 컴포넌트 버전의 ROOT 모듈에 있는 index.adoc를 사용합니다.

|title
|참조 UI의 컴포넌트 버전 페이지 메뉴, 컴포넌트 버전 선택기 및 페이지 브레드크럼에서 정렬 및 프레젠테이션 목적으로만 사용되는 컴포넌트 이름입니다. 빈 공백, 대문자 및 광범위한 문자(예: API Manager)를 허용합니다.

|===

version 키의 기능에 대해 자세히 알아보고 Antora가 제공하는 다른 버전 패싯(사전 릴리스 버전, 표시 버전 및 기호 버전)과 비교하려면 Version Facets를 참조하세요.