= Configure Component Versions - Distributed Component Versions

컴포넌트 버전의 모든 소스 파일은 종종 단일 저장소에 저장되지만 필수는 아닙니다. Antora는 동일한 컴포넌트 버전에 속하는 소스 파일을 여러 저장소에서 수집할 수 있습니다.

== 분산 컴포넌트 버전이란?

컴포넌트 버전의 소스 파일이 여러 콘텐츠 루트(즉, 여러 저장소, 여러 시작 페이지 등)에 저장되는 경우 **분산 컴포넌트 버전**이라고 합니다.

분산 컴포넌트 버전의 일반적인 사용 사례는 대부분의 소스 파일이 한 저장소에 저장되지만 교육 팀에서 관리하는 다른 저장소에 여러 예제(__examples__ 패밀리 디렉터리)와 튜토리얼(__pages__ 패밀리 디렉터리)이 저장되는 경우입니다. Antora는 두 저장 위치의 소스 파일을 단일 컴포넌트 버전으로 결합하는 데 문제가 없습니다. 이 기능은 단순하지만 강력한 컴포넌트 버전 디스크립터 파일인 __antora.yml__에 의해 제공됩니다.

== antora.yml 파일 및 키 관리

__antora.yml__ 파일은 컴포넌트 버전의 컴포넌트 이름과 버전을 지정한다는 점을 기억하세요. Antora가 동일한 컴포넌트 이름과 버전을 지정하는 두 개 이상의 __antora.yml__ 파일을 발견하면 소스 파일이 여러 위치에서 수집되었더라도 후속 표준 디렉터리 세트의 모든 파일이 동일한 컴포넌트 버전에 속한다고 간주합니다.

컴포넌트 버전의 소스 파일이 분산된 경우 __antora.yml__ 파일 중 하나만 필수 컴포넌트 ``name``과 ``version`` 외에 ``title``과 ``nav``와 같은 선택적 구성 키를 지정해야 합니다. 컴포넌트 버전의 소스 파일 위치를 표시하는 다른 모든 __antora.yml__ 파일에는 컴포넌트 ``name``과 ``version``만 지정해야 합니다. 충돌하거나 중복된 선택적 구성 키는 예측할 수 없는 결과를 초래할 수 있습니다.

== 충돌 파일

분산 컴포넌트 버전을 설정할 때 각 콘텐츠 소스 루트는 고유한 파일 세트(__antora.yml__ 제외)를 제공해야 합니다. 즉, 콘텐츠 소스 루트는 결합될 때 겹칠 수 없습니다.

Antora는 동일한 리소스 ID를 가진 두 개 이상의 소스 파일을 찾으면 오류와 함께 실패합니다. 이는 분산 컴포넌트 버전에서 동일한 패밀리 및 모듈에 속하는 동일한 파일 이름입니다. Antora가 동일한 파일 이름을 가진 두 개 이상의 탐색 파일이 있는 모듈을 발견하면 이 오류도 발생합니다. 이 상황에 대한 자세한 내용은 중복 리소스를 참조하세요.
