= 컴포넌트 버전 정렬 방법

이 페이지에서는 다음을 배웁니다:

* [*] Antora가 컴포넌트와 컴포넌트 버전을 정렬하는 방법.
* [*] Antora가 컴포넌트의 최신 버전을 선택하는 방법.

버전 지정 체계를 선택할 때 Antora가 컴포넌트 버전을 정렬하는 방식과 사이트 UI에서의 잠재적인 프레젠테이션 및 라우팅 결과를 이해하는 것이 중요합니다.

== 문서 컴포넌트 정렬 순서

Antora는 컴포넌트 버전을 문서 컴포넌트로 그룹화합니다. 콘텐츠 카탈로그의 컴포넌트 정렬 순서는 결정적이지 않습니다. 그러나 문서 컴포넌트가 UI 모델``(site.components``)을 통해 액세스되면 제목별로 알파벳 순서로 정렬됩니다. 컴포넌트의 제목은 각 컴포넌트 버전의 __antora.yml__ 파일에 정의된 ``title`` 키로 정의됩니다. ``title`` 키가 설정되지 않은 경우 Antora는 컴포넌트를 정렬할 때 ``name`` 키로 대체합니다. 각 컴포넌트에서 버전은 컴포넌트 버전 정렬 규칙에 따라 정렬됩니다.

이렇게 정렬된 컴포넌트 목록은 일반적으로 UI에서 사용되어 읽는 사람이 다른 컴포넌트와 버전 사이를 탐색하는 데 사용할 수 있는 메뉴 위젯을 제공합니다. Antora의 기본 UI는 이러한 위젯을 제공합니다. 기본 UI에서는 주어진 컴포넌트의 버전 목록이 각 컴포넌트의 제목 아래에 표시됩니다.

Antora는 컴포넌트와 버전이 이 순서로 표시될 필요가 없습니다. 다른 순서로 표시하려면 이 목록을 생성하는 UI 템플릿을 사용자 정의해야 합니다. Antora의 기본 UI를 사용자 정의할 때는 UI 프로젝트의 __src/partials/nav-explore.hbs__에 있는 ``nav-explore``라는 부분을 편집해야 합니다. 해당 템플릿의 핵심 부분은 ``site.components``에 대한 반복입니다:

[source,hbs]
----
{{#each site.components}}
...
{{/each}}
----

Antora의 기본 UI는 컴포넌트가 UI 모델에 저장되는 순서를 사용합니다. 컴포넌트 목록을 직접 제공해야 하는 사용자 정의 도우미 함수에 전달하여 이 순서를 수정할 수 있습니다:

[source,hbs]
----
{{#each (rearrange site.components 'component-b,component-a'}}
...
{{/each}}
----

또한 표시할 각 컴포넌트에 대해 수동으로 메뉴 항목을 만들 수도 있습니다. 이 전략을 사용하면 특정 컴포넌트를 제외할 수도 있습니다.

== 버전 지정 체계

Antora는 문서 컴포넌트의 컴포넌트 버전을 정렬할 때 version 키의 값만 고려합니다. version 키에 할당된 값은 컴포넌트 버전 선택기 메뉴에서 컴포넌트 제목 또는 이름 아래에 컴포넌트 버전이 배치되는 버전 지정 체계와 순서를 결정합니다. 예약된 값 ~와 null은 컴포넌트 버전을 버전이 없는 것으로 정의합니다.

[cols="1,5,1"]
|===
|체계 |유효한 식별자 |예

// Semantic
|의미론적
|정수 +
숫자로 시작하고 하나 이상의 점(.) 문자를 포함하는 문자열 +
v로 시작하고 숫자가 뒤따르며 하나 이상의 점(.) 문자를 포함하는 문자열
|30 +
2.4 +
v90.3

// Named
|명명된
|의미론적 체계 또는 예약된 버전 값(~, null)과 일치하지 않는 모든 값
|edge +
z4

// Unversioned
|버전이 없는
|~ +
null
|~
|===

== 컴포넌트 버전 정렬 규칙

Antora는 컴포넌트의 컴포넌트 버전을 정렬할 때 다음 규칙을 적용합니다:

. 버전이 없는 컴포넌트 버전은 둘 다 있는 경우 명명된 버전 앞에 컴포넌트 버전 선택기 메뉴에 표시됩니다.
. 컴포넌트의 명명된 버전은 둘 다 있는 경우 의미론적 버전 앞에 컴포넌트 버전 선택기 메뉴에 표시됩니다.
. 컴포넌트의 명명된 버전은 역순 알파벳 순서로 정렬됩니다(예: z4, wish, lester).
  .. URL에는 대문자를 사용하는 것이 권장되지 않으며 웹 서버 간 이식성을 방해할 수 있습니다. 대문자를 사용하는 경우 소문자 앞에 옵니다(예: A, a).
. 컴포넌트의 의미론적 버전은 둘 다 있는 경우 명명된 버전 뒤에 컴포넌트 버전 선택기 메뉴에 표시됩니다.
. 컴포넌트의 의미론적 버전은 내림차순으로 정렬됩니다.
  .. 의미론적 식별자의 선행 v는 무시되며 버전은 v 다음의 첫 번째 숫자에 따라 정렬됩니다.
  .. 의미론적 버전 지정 정렬 규칙이 적용됩니다.

=== 컴포넌트의 버전 순서 결정

__RoseyDB__ 컴포넌트에 여러 컴포넌트 버전이 포함되어 있다고 가정해 보겠습니다. 일부 버전은 의미론적 체계를 사용합니다: ``v2.5``, ``4.0`` 및 ``3.9``. 일부는 명명되었습니다: ``utopia``와 ``vivid``. Antora의 정렬 규칙에 따르면 __RoseyDB__ 컴포넌트 버전은 아래 나열된 순서로 참조 UI에 표시됩니다.

.정렬된 RoseyDB 컴포넌트 버전
[source]
----
vivid
utopia
4.0
3.9
v2.5
----

컴포넌트 버전의 __antora.yml__ 파일에 ``display_version`` 키가 정의되어 있으면 ``version`` 키의 값 대신 ``display_version``의 값이 표시된다는 점에 유의하세요. ``display_version``이 설정되었는지 여부에 관계없이 컴포넌트 버전은 항상 ``version`` 키에 할당된 값에 따라 정렬됩니다. 따라서 독자의 눈에는 버전이 설명된 순서대로 정렬되어 보이지 않을 수 있습니다.

예를 들어, __RoseyDB__의 ``utopia`` 버전에 ``display_version`` 값으로 ``3.0``이 할당된 경우 __RoseyDB__ 버전은 여전히 동일한 순서로 정렬됩니다. utopia 버전은 참조 UI에서 3.0으로 레이블이 지정될 뿐입니다.

[source]
----
vivid
3.0
4.0
3.9
v2.5
----

Antora는 또한 각 컴포넌트의 최신 컴포넌트 버전을 결정합니다. RoseyDB의 최신 버전은 정렬된 목록의 첫 번째 버전이고 사전 릴리스로 정의되지 않았기 때문에 vivid가 될 것입니다.

== 최신 컴포넌트 버전

컴포넌트 버전을 정렬하는 것 외에도 Antora는 각 컴포넌트의 가장 최근의 안정된 컴포넌트 버전을 식별합니다. **최신 컴포넌트 버전**(**최신 버전**이라고도 함)은 사전 릴리스가 아닌 정렬된 목록의 첫 번째 버전입니다. 모든 버전이 사전 릴리스인 경우 목록의 첫 번째 사전 릴리스 버전이 선택됩니다. 버전이 없는 컴포넌트 버전은 항상 최신 버전 또는 최신 사전 릴리스 버전(prerelease가 설정된 경우)으로 간주됩니다.

Antora는 버전 좌표가 지정되지 않았거나 달리 결정할 수 없는 경우 다른 컴포넌트에서 들어오는 리소스 ID 참조를 검증할 때 컴포넌트의 최신 버전을 사용합니다.

TIP: 최신 버전은 UI 모델에서 latest 속성으로 사용할 수 있습니다.