= 사전 릴리스 버전 식별

prerelease 키는 컴포넌트 버전을 사전 릴리스로 식별합니다.

== prerelease 키

prerelease 키는 선택 사항입니다. prerelease 키에 -beta.2와 같은 사용자 정의 식별자 또는 부울 값 true가 할당되면 컴포넌트 버전이 사전 릴리스로 식별됩니다. Antora는 해당 문서 컴포넌트의 모든 버전이 사전 릴리스가 아닌 한 사전 릴리스로 지정된 컴포넌트 버전에 기본 라우팅 규칙을 적용하지 않습니다. 컴포넌트 버전이 사전 릴리스에서 안정 릴리스로 승격될 준비가 되면 prerelease 키의 값을 false로 변경하거나 __antora.yml__ 파일에서 키와 값을 삭제하세요.

TIP: prerelease 키가 제공하는 기능에 대해 자세히 알아보고 다른 버전 패싯(실제 버전, 표시 버전 및 기호 버전)과 비교하려면 버전 패싯을 참조하세요.

=== prerelease에 식별자 할당

prerelease 키가 __antora.yml__에 설정되고 식별자가 할당되면 컴포넌트 버전이 사전 릴리스가 됩니다. 식별자는 .alpha.2, -M1, SNAPSHOT 및 -rc.5와 같은 사용자 정의 비어 있지 않은 문자열입니다. 대문자와 광범위한 문자를 포함할 수 있습니다. 예제 1에 정의된 컴포넌트 버전은 사전 릴리스입니다.

.예제 1.식별자 -rc.3이 할당된 prerelease가 있는 antora.yml
[source,yaml]
----
name: colorado
title: Colorado ∆
version: '6.0.0'
prerelease: -rc.3 <1>
----
<1> 컴포넌트 버전을 사전 릴리스로 지정하려면 prerelease에 식별자를 할당하세요.

prerelease에 식별자가 할당되면 Antora는 UI 정렬용 내부 사전 릴리스 버전 값과 display_version이 설정되지 않은 경우 표시 목적으로 계산합니다. 이 계산된 사전 릴리스 버전은 사전 릴리스 식별자의 첫 번째 문자에 따라 달라집니다.

__하이픈(-) 또는 점(.)으로 시작하는 식별자__::
계산된 사전 릴리스 버전은 version-identifier 또는 version.identifier 형식을 취합니다. Antora는 사전 릴리스 식별자를 version 키의 값에 직접 추가하여 사전 릴리스 버전을 계산합니다. 예를 들어, 예제 1을 사용하면 계산된 사전 릴리스 버전은 6.0.0-rc.3이 됩니다.

__다른 유효한 문자로 시작하는 식별자__::
계산된 사전 릴리스 버전은 version identifier 형식을 취합니다. Antora는 사전 릴리스 버전을 계산하기 위해 식별자를 version 키의 값과 하나의 공백으로 구분합니다.
+
.예제 2. prerelease에 식별자 Beta가 할당된 antora.yml
[source,yaml]
----
name: colorado
title: Colorado ∆
version: '4.0'
prerelease: Beta
----
+
예제 2를 사용하면 계산된 사전 릴리스 버전은 4.0 Beta가 됩니다.

display_version 키가 __antora.yml__에 설정되지 않은 경우 Antora는 런타임에 계산된 사전 릴리스 버전을 display_version에 할당합니다. display_version이 __antora.yml__에 정의되어 있으면 해당 값이 UI에 표시됩니다. 그러나 컴포넌트 버전은 여전히 내부적으로 계산된 사전 릴리스 버전 값에 따라 정렬됩니다.

=== prerelease에 true 할당

prerelease 키가 __antora.yml__에 설정되고 값 true가 할당되면 컴포넌트 버전이 사전 릴리스가 됩니다.

.예제 3. prerelease가 true로 정의된 antora.yml
[source,yaml]
----
name: colorado
title: Colorado ∆
version: '6.5.0-snapshot'
prerelease: true
----

prerelease가 true이면 컴포넌트 버전은 version의 값으로 정렬되지만 해당 문서 컴포넌트의 최신 버전이더라도 기본 라우팅 규칙이 적용되지 않습니다.

== 사전 릴리스 정렬 및 라우팅

모든 컴포넌트 버전이 사전 릴리스가 아닌 한 Antora가 문서 컴포넌트의 최신 버전을 선택할 때 사전 릴리스 버전은 건너뜁니다. 이 경우 기본 규칙이 적용됩니다. 계산된 사전 릴리스 버전이 충족하는 버전 관리 체계 기준에 따라 정렬됩니다.

== 사전 릴리스를 안정 버전으로 승격

컴포넌트 버전이 사전 릴리스에서 안정 릴리스로 승격될 준비가 되면 prerelease 키의 값을 false로 변경하세요.

.예제 4. prerelease가 false로 정의된 antora.yml
[source,yaml]
----
name: colorado
title: Colorado ∆
version: '6.0.0'
prerelease: false <1>
----
<1> 컴포넌트 버전을 안정 릴리스로 승격하려면 이전 값을 제거하고 false로 바꾸세요.

prerelease가 false로 설정되면 기본 라우팅 및 정렬 규칙이 컴포넌트 버전에 적용됩니다. 또는 안정화되면 __antora.yml__에서 키와 값을 삭제할 수 있습니다.