= 이름 키

구성 요소 이름은 name 키에 값을 할당하여 정의됩니다.

== 컴포넌트 이름이란?

**컴포넌트 이름**은 컴포넌트 버전 디스크립터 파일(__antora.yml__)의 name 키에 할당된 값으로, name이라고도 합니다. 컴포넌트 이름은 일반적으로 fauna, rudder, nrepl 등과 같은 프로젝트, 라이브러리, 서비스 등의 이름을 나타냅니다. name 키의 값은 version 키의 값과 결합하여 컴포넌트 버전을 정의합니다.

=== Antora가 name을 사용하는 방법

컴포넌트 이름은 Antora의 많은 작업에 기본적입니다. Antora는 name을 다음과 같이 사용합니다:

- 컴포넌트의 이름이 ROOT가 아닌 한 페이지 및 자산 URL의 컴포넌트 세그먼트로 사용합니다.

또한 컴포넌트 title 키가 설정되지 않은 경우 Antora는 name을 다음과 같이 사용합니다:

- 컴포넌트 버전 정렬에 사용합니다.
- 참조 UI에서 표시 목적으로 사용하며, 여기에는 컴포넌트 버전 페이지 메뉴, 컴포넌트 버전 선택기 메뉴 및 컴포넌트 버전 페이지의 첫 번째 브레드크럼 위치가 포함됩니다.

컴포넌트 이름은 대소문자를 구분합니다. 이는 대소문자만 다른 동일한 이름의 두 컴포넌트가 있는 경우 Antora가 이를 다른 컴포넌트로 처리함을 의미합니다.

콘텐츠 작성자는 다른 문서 컴포넌트의 리소스를 참조할 때 리소스 ID의 컴포넌트 좌표로 name을 사용합니다.

== name 키

name 키는 필수입니다. 이는 컴포넌트 버전 디스크립터 파일(__antora.yml__)에서 설정되고 값이 할당됩니다.

.예제 1. antora.yml에 정의된 컴포넌트 이름
[source,yaml]
----
name: colorado <1>
----
<1> 새 줄의 시작 부분에 name을 입력하고 바로 뒤에 콜론과 공백(: )을 입력합니다. 그런 다음 name에 할당할 값을 입력합니다.

=== name 요구 사항

name 키에 할당된 값에는 문자, 숫자, 밑줄(_), 하이픈(-) 및 마침표(.)가 포함될 수 있습니다. 호스트 플랫폼 간의 이식성을 보장하기 위해 name 값에 사용되는 문자는 소문자여야 합니다.

IMPORTANT: 소문자 문자로만 구성된 이름을 선택하는 것이 좋습니다. 특수 ROOT 값을 제외한 컴포넌트 이름은 사이트의 URL에 사용되므로 일관된 대소문자 사용은 컴포넌트 이름과 사이트를 더 이식 가능하게 만듭니다. 일부 파일 시스템과 그 위에서 실행되는 웹 서버는 대문자와 소문자를 구분할 수 없기 때문입니다.

값에는 공백, 슬래시(/) 또는 HTML 특수 문자(&, <, >)를 포함할 수 없습니다. 값은 비워둘 수 없습니다.

사이트의 UI에 공백, 대문자 및 기타 문자가 포함된 이름을 표시하는 방법을 알아보려면 제목 사용자 지정을 참조하세요.

=== ROOT 컴포넌트

컴포넌트의 이름이 __ROOT__로 설정되고 __antora.yml__에서 버전이 ~로 설정된 경우 해당 컴포넌트는 사이트의 루트에 직접 배치됩니다. ROOT라는 폴더 안에 배치되지 않습니다. 이는 __ROOT__라는 이름의 모듈이 해당 컴포넌트의 루트에 배치되는 방식과 유사합니다.

다른 컴포넌트와 마찬가지로 ROOT 컴포넌트에는 __antora.yml__ 파일과 modules 폴더가 있어야 합니다. 페이지 URL의 모듈 세그먼트에서 예제를 다시 사용해 보겠습니다:

[source]
----
📒 repository
  📄 antora.yml # name: ROOT and version: ~
  📂 modules
    📂 admin
      📂 pages
        📄 user-management.adoc
      📄 nav.adoc
    📂 ROOT
      📁 images
      📂 pages
        📄 deploy.adoc
        📄 index.adoc
      📄 nav.adoc
----

하지만 이제 이 컴포넌트의 이름이 hyperlemur 대신 __ROOT__로 지정되고 버전이 ~로 설정되었다고 가정해 보겠습니다. 페이지의 URL은 다음과 같습니다(플레이북에서 html_extension_style이 default로 설정되어 있다고 가정):

__repository/modules/ROOT/pages/index.adoc__::
pass:[https://my-company.com/index.html] (pass:[https://my-company.com]에서도 찾을 수 있음을 의미)

__repository/modules/ROOT/pages/deploy.adoc__::
pass:[https://my-company.com/deploy.html]

__repository/modules/admin/pages/user-management.adoc__::
pass:[https://my-company.com/admin/user-management.html]

컴포넌트 이름 __ROOT__와 모듈 이름 __ROOT__가 모두 URL에서 제외되므로 __ROOT__ 컴포넌트의 __ROOT__ 모듈에 있는 페이지는 사이트의 루트에 직접 위치하며, __root_component/modules/ROOT/pages/index.adoc__가 사이트의 홈 페이지 역할을 합니다. 즉, ROOT 컴포넌트의 ROOT 모듈에 있는 __index.adoc__ 페이지는 추가 구성 없이 사이트 시작 페이지 역할을 합니다.

__ROOT__ 컴포넌트에 버전이 지정된 경우(즉, 버전이 비어 있지 않은 경우) 해당 컴포넌트 버전의 파일은 사이트 루트의 버전 폴더 안에 배치됩니다.

CAUTION: ROOT 컴포넌트의 이름이 URL에 나타나지 않기 때문에 해당 모듈은 사이트 루트 아래에서 효과적으로 범위가 지정됩니다. 이는 __ROOT__ 컴포넌트의 페이지가 이름이 지정된 컴포넌트의 페이지와 충돌할 수 있음을 의미합니다. 예를 들어, (버전이 지정되지 않은) ROOT 컴포넌트의 __modules/xyz/pages/index.adoc__ 파일과 (버전이 지정되지 않은) xyz 컴포넌트의 __modules/ROOT/pages/index.adoc__ 파일은 모두 pass:[https://my-company.com/xyz/index.html] URL로 해석되며, 이는 유효하지 않습니다. 따라서 ROOT 컴포넌트에서 모듈을 사용할 때는 이러한 상황에 주의해야 합니다.

ROOT는 사용자 친화적인 컴포넌트 제목이 아니므로 Customize the Title에 설명된 대로 __antora.yml__에 제목을 설정해야 합니다.