= 버전 속성

== 실제 버전

**실제 버전**은 컴포넌트 이름과 결합되어 서로 직접 관련된 콘텐츠 및 소스 파일 모음에 대한 고유한 ID를 생성하는 식별자입니다. 이 소스 파일 모음은 컴포넌트 버전입니다. 컴포넌트 버전에는 항상 실제 버전이 있습니다. 버전이 없는 컴포넌트 버전에도 내부 정렬 및 라우팅 목적으로 빈 문자열로 정의된 실제 버전이 있습니다.

컴포넌트 버전의 실제 버전은 컴포넌트 버전 디스크립터(__antora.yml__)의 version 키에 할당됩니다. 또는 실제 버전은 __antora.yml__의 version 키 또는 플레이북의 콘텐츠 소스에 할당된 패턴에 따라 Antora가 git refname에서 추출합니다.

콘텐츠 작성자는 실제 버전을 사용하여 다른 컴포넌트 버전의 페이지와 리소스를 참조합니다. Antora는 실제 버전을 다음과 같이 사용합니다:

- 컴포넌트 버전을 정렬하는 데 사용
- 컴포넌트의 최신 버전을 식별하는 데 사용
- 라우팅 규칙을 적용하는 데 사용
- 컴포넌트 버전이 버전이 없는 경우를 제외하고 UI에서 표시 목적으로 사용
- 컴포넌트 버전이 버전이 없는 경우를 제외하고 게시된 URL의 버전 세그먼트로 사용

다음 섹션에서 설명하는 각 버전 속성(사전 릴리스, 표시 및 기호)은 Antora가 실제 버전을 사용하는 기본 동작을 재정의합니다.

== 사전 릴리스 버전

최종 릴리스 전에 제공되는 프로젝트 또는 제품 버전을 종종 **사전 릴리스 버전**이라고 합니다. 조직에서는 ``-alpha.1``과 같은 의미 있는 버전 식별자 또는 ``M1``이나 ``Snapshot``과 같은 특수 이름을 사용하여 버전이 최종 사용자에게 사전 릴리스임을 알립니다. 프로젝트의 사전 릴리스 버전을 보완하기 위해 ``prerelease`` 키를 사용하여 컴포넌트 버전을 사전 릴리스로 지정할 수 있습니다.

컴포넌트 버전은 __antora.yml__ 파일에서 ``prerelease`` 키에 식별자 또는 예약된 값 true가 할당되면 사전 릴리스로 지정됩니다. ``prerelease`` 키를 사용하면 다음과 같은 이점이 있습니다:

* 컴포넌트 버전이 사전 릴리스인 동안 버전 좌표가 지정되지 않았거나 결정할 수 없는 경우 Antora는 다른 컴포넌트 버전에서 들어오는 페이지 및 리소스 ID 참조를 사전 릴리스 버전으로 라우팅하지 않습니다. 대신 Antora는 이러한 참조를 컴포넌트의 최신 안정 버전으로 라우팅합니다.
* prerelease 키를 사용하면 컴포넌트 버전의 실제 버전(version)이 컴포넌트 버전 시작부터 안정 버전을 나타낼 수 있습니다. 즉, 사전 릴리스는 실제 버전을 변경하지 않습니다. Antora가 안정 버전으로 분류하지 않도록 의미만 수정합니다. 따라서 컴포넌트 버전이 사전 릴리스에서 안정 릴리스로 전환될 때 컴포넌트 버전의 게시된 URL과 컴포넌트 버전을 특별히 대상으로 하는 다른 컴포넌트 버전의 인바운드 참조는 영향을 받지 않습니다.
* ``display_version`` 키에 값이 할당되거나 ``prerelease``에 ``true``가 할당되지 않는 한 사전 릴리스 식별자는 실제 버전에 추가되어 UI 메뉴에 표시되므로 최종 사용자에게 컴포넌트 버전이 사전 릴리스임을 보여줍니다.
  ** 컴포넌트 버전이 버전이 없는 경우 사전 릴리스 식별자만 UI 메뉴에 표시됩니다.

== 표시 버전

실제 버전에는 처리 또는 이식성 오류를 일으키는 공백, 대문자 또는 특정 문자를 포함할 수 없습니다. 그러나 UI 메뉴에 표시될 때 실제 버전이 최종 사용자가 버전을 공백, 대문자 또는 기타 기호로 표시할 것으로 예상하는 경우 적절한 경험을 제공하지 않을 수 있습니다. 이러한 상황에서는 컴포넌트 버전에 표시 버전을 할당해야 합니다.

**표시 버전**은 UI 메뉴에서 보여줄 목적으로만 사용되는 식별자입니다. 실제 버전과 달리 표시 버전에는 공백, 대문자 및 기타 기호나 문자가 포함될 수 있습니다. 표시 버전은 컴포넌트 버전의 __antora.yml__ 파일에서 display_version 키를 사용하여 지정됩니다. 표시 버전은 컴포넌트 버전 선택기와 페이지 버전 선택기를 포함하여 버전이 표시되는 UI에서 사용됩니다. 표시 버전은 페이지 또는 리소스 ID에서 컴포넌트 버전 라우팅 및 정렬이나 URL의 버전 세그먼트에서 절대 사용되지 않습니다.

== 기호 버전 및 기호 사전 릴리스 버전

**기호 버전** 또는 **기호 사전 릴리스 버전**은 URL의 버전 세그먼트에서 실제 버전을 대체하는 값입니다. 기호 버전 또는 사전 릴리스 버전은 각각 최신 컴포넌트 버전 또는 최신 사전 릴리스의 URL에만 적용됩니다. 기호 버전 또는 사전 릴리스 버전은 버전이 없는 컴포넌트 버전에는 적용되지 않습니다. 기호 버전 및 기호 사전 릴리스 버전은 사이트의 모든 최신 컴포넌트 버전 또는 사전 릴리스 버전에 적용되므로 이러한 값은 개별 컴포넌트 버전의 __antora.yml__ 파일이 아닌 플레이북에 할당됩니다. 기호 버전은 플레이북의 ``latest_version_segment`` 키에 할당됩니다. 기호 사전 릴리스 버전은 플레이북의 ``latest_prerelease_version_segment`` 키에 할당됩니다.

=== 버전 속성 요약
[%header,cols="h,1,2,2,1"]
|===
|속성 |페이지 및 리소스 ID |정렬 순서 및 라우팅 |참조 UI의 메뉴 |URL의 버전 세그먼트

// Actual
|실제
|예
|예
|예

_예외_:

``display_version``에 값이 할당된 경우 실제 버전 대신 표시 버전이 표시됩니다.
prerelease에 식별자가 할당되고 ``display_version``이 설정되지 않은 경우 Antora는 식별자를 실제 버전에 추가하여 ``display_version`` 값을 자동으로 계산합니다. 이 계산된 값은 실제 버전 대신 표시됩니다.

컴포넌트 버전이 버전이 없는 경우 실제 버전은 표시되지 않습니다. 대신 __antora.yml__ 파일에 지정된 버전 속성에 따라 표시 버전, 사전 릴리스 식별자 또는 폴백 기본 레이블이 표시됩니다.
|예

_예외_:

컴포넌트 버전이 버전이 없는 경우 페이지 및 에셋 URL에 버전 세그먼트가 포함되지 않습니다.

latest_version_segment에 값이 할당된 경우 실제 버전은 기호 버전으로 대체됩니다. 이 동작은 버전이 없거나 사전 릴리스로 표시되지 않은 최신 컴포넌트 버전의 URL에만 적용됩니다.

// Prerelease
|사전 릴리스
|아니요
|예
|예

_예외_:

``display_version``에 값이 할당된 경우 계산된 사전 릴리스 버전 또는 폴백 값 대신 표시 버전이 표시됩니다.

``prerelease``에 ``true``가 할당되고 ``display_version``이 설정되지 않은 경우 실제 버전 또는 컴포넌트 버전이 버전이 없는 경우 폴백 레이블 __default__가 표시됩니다.

|아니요

_예외_:

``latest_prerelease_version_segment``에 값이 할당된 경우 실제 버전은 기호 사전 릴리스 버전으로 대체됩니다. 이 동작은 버전이 없는 것으로 정의되지 않은 컴포넌트의 최신 사전 릴리스 버전의 URL에만 적용됩니다.

// Display
|표시
|아니요
|아니요
|예
|아니요

// Symbolic
|기호
|아니요
|아니요
|아니요
|컴포넌트의 최신 버전에만 적용됩니다. 버전이 없는 컴포넌트 버전에는 적용되지 않습니다.

// Symbolic prerelease
|기호 사전 릴리스
|아니요
|아니요
|아니요
|컴포넌트의 최신 사전 릴리스 버전에만 적용됩니다. 사전 릴리스로 표시된 버전이 없는 컴포넌트 버전에는 적용되지 않습니다.
|===
