= 버전 키

버전은 version 키에 값을 할당하여 정의됩니다. 버전 체계를 커밋하기 전에 Antora가 버전과 관련 패싯을 사용하는 방법을 이해하는 것이 중요합니다.

== 버전이란?

Antora에서 **버전**은 컴포넌트 버전 디스크립터 파일(__antora.yml__)의 version 키 또는 플레이북의 콘텐츠 소스에서 상속된 값에서 해석된 값입니다. 버전은 프로젝트 문서의 고유한 릴리스 또는 인스턴스를 나타내는 의미 있는 식별자 또는 명명된 식별자입니다. version 키의 해석된 값은 name 키의 값과 결합하여 컴포넌트 버전을 정의합니다.

버전은 일반적으로 리터럴 값이지만 해석될 수도 있습니다. 버전은 version 키에 물결표(~)를 할당하여 버전이 없는 것으로 정의할 수 있습니다. 버전은 version 키에 true를 할당하여 상주하는 refname으로 구성할 수 있습니다. 버전은 version 키에 refname 프로젝션의 맵을 할당하여 refname에서 파생될 수도 있습니다.

때때로 version 키에 할당된 값은 버전과 다른 버전 패싯(사전 릴리스, 표시 및 기호) 사이의 구별이 설명이나 예제에서 이루어져야 할 때 이 문서에서 실제 버전이라고 합니다.

=== Antora가 버전을 사용하는 방법

버전은 Antora의 많은 작업에 기본적입니다. Antora는 버전을 다음과 같이 사용합니다:

- 컴포넌트 버전을 정렬하는 데 사용합니다.
- 컴포넌트의 최신 버전을 식별하는 데 사용합니다.
- 라우팅 규칙을 적용하는 데 사용합니다.
- 게시 가능한 리소스 URL의 버전 세그먼트로 사용합니다. 다음의 경우는 예외입니다:
  ** 할당된 값이 버전이 없는 컴포넌트 버전을 정의하는 물결표(~)인 경우
  ** 컴포넌트 버전이 최신 안정 버전 또는 최신 사전 릴리스 버전으로 식별되고 플레이북에 latest_version_segment 키 또는 latest_prerelease_version_segment 키가 설정된 경우
- 참조 UI 컴포넌트 버전 선택기 및 페이지 버전 선택기 메뉴에서 표시 목적으로 사용합니다. 다음의 경우는 예외입니다:
  ** display_version 키가 설정되고 컴포넌트 버전의 __antora.yml__ 파일에 값이 할당된 경우
  ** prerelease 키에 식별자가 할당되어 런타임에 Antora에 의해 display_version 키가 설정된 경우

콘텐츠 작성자는 다른 컴포넌트 버전의 리소스를 참조할 때 리소스 ID의 버전 좌표로 버전을 사용합니다.

== version 키

version 키는 jesse와 같은 명명된 식별자, '1.5.0'과 같은 의미 있는 식별자, 예약된 값 true, v/(?<version>*): $<version>와 같은 refname 프로젝션의 맵 또는 예약된 값 ~를 허용합니다. ~ 값은 컴포넌트 버전을 버전이 없는 것으로 정의합니다. 버전이 없는 컴포넌트 버전을 지정하는 방법을 알아보려면 버전이 없는 컴포넌트 정의를 참조하세요.

version 키가 컴포넌트 버전의 컴포넌트 버전 디스크립터 파일에 정의된 경우 플레이북의 콘텐츠 소스에 정의된 값보다 우선합니다. 플레이북이 version 키의 값을 제어하는 것을 선호하는 경우 컴포넌트 버전 디스크립터 파일에 version 키를 설정하지 마세요.

=== 버전으로서의 명명된 식별자

다음 예제는 version 키에 명명된 식별자를 할당하는 방법을 보여줍니다.

.예제 1. version에 할당된 명명된 식별자가 있는 antora.yml
[source,yaml]
----
name: star
version: rigel <1>
----
<1> 새 줄에 version을 입력하고 바로 뒤에 콜론과 공백(: )을 입력합니다. 그런 다음 version에 할당할 값을 입력합니다.

=== 버전으로서의 의미 있는 식별자

의미 있는 식별자는 정수이거나 정수로 시작하고 하나 이상의 점(.)을 포함합니다. 10, 1.0.0, 5.1은 모두 의미 있는 식별자의 예입니다. 의미 있는 식별자는 숫자처럼 보이지만 실제로는 문자열입니다. 의미 있는 식별자가 예제 2에 표시된 것과 같이 숫자(정수 또는 소수)의 구문과 일치하는 경우 값을 작은따옴표(') 쌍으로 묶어야 합니다. 이렇게 하면 문자열로 강제 변환됩니다.

다음 예제는 version 키에 의미 있는 식별자를 할당하는 방법을 보여줍니다.

.예제 2. version에 할당된 의미 있는 식별자가 있는 antora.yml
[source,yaml]
----
name: colorado
version: '5.6.0' <1>
----
<1> 숫자의 구문과 일치하는 값을 작은따옴표(') 쌍으로 묶습니다.

Antora는 의미 있는 버전 지정 규칙에 따라 의미 있는 식별자를 인식합니다. 의미 있는 버전 지정은 semver라고도 합니다. Antora는 의미 있는 식별자가 v로 시작하는 것을 허용합니다. 이 접두사는 값에 보존되지만 Antora는 버전 정렬 시 이를 무시합니다. 예를 들어 v9.0.2는 값이 9.0.2인 것처럼 정렬됩니다.

=== 버전으로서의 refname

Antora의 콘텐츠는 git 저장소에서 검색되므로 컴포넌트 버전 디스크립터가 저장된 git refname(브랜치 또는 태그 이름)을 버전으로 사용할 수 있습니다. 이렇게 하려면 예제 3과 같이 version에 예약된 값 true를 할당합니다.

.예제 3. version에 true가 할당된 antora.yml
[source,yaml]
----
name: colorado
version: true <1>
----
<1> 값 true는 Antora에게 refname을 값으로 사용하라고 지시합니다.

Antora는 값 true를 refname으로 자동 대체합니다. Antora가 사용하는 값은 항상 전체 refname(예: refs/heads/v1.0)이 아닌 짧은 refname(예: v1.0)입니다.

=== 버전으로서의 refname 프로젝션

refname은 버전으로 사용하기에 충분히 세분화되지 않을 수 있습니다. 게다가 동일한 git 트리가 기능 브랜치와 같이 서로 다른 명명 체계를 가진 git 참조를 통과할 수 있습니다. 이러한 경우에는 값을 그대로 사용하는 것이 아니라 버전을 refname에서 추출하거나 파생시키려고 합니다. 그럴 때는 refname 프로젝션을 사용하여 버전을 정의하면 됩니다.

refname 프로젝션은 패턴(키)과 대체(값)의 맵으로 표현됩니다. refname 프로젝션을 사용하면 패턴을 사용하여 refname과 일치시킨 다음 해당 일치를 기반으로 버전을 빌드할 수 있습니다. 패턴은 Antora에게 사용할 항목과 추출할 부분을 알려줍니다. 대체는 Antora에게 일치하는 refname에서 버전을 파생시키는 방법을 알려줍니다.

다음 예제는 refname 프로젝션을 사용하여 version 키의 값을 계산하는 방법을 보여줍니다.

.예제 4. refname 프로젝션에서 계산된 버전이 있는 antora.yml
[source,yaml]
----
name: colorado
version:
  v(?<version>+({0..9}).+({0..9})).x: $<version> <1>
  feature/(*)/*: $1 <2>
----
<1> v2.0.x와 같은 refname에서 의미 있는 식별자와 일치하고 이를 추출합니다.
<2> feature/로 시작하는 refname에 대해 첫 번째 슬래시와 두 번째 슬래시 사이의 값을 추출합니다.

프로젝션의 키는 글로브 패턴(extglob, 범위 및 일부 정규식 구성의 조합)입니다. 패턴은 플레이북의 콘텐츠 소스에 대한 브랜치 또는 태그를 일치시키는 데 사용되는 패턴과 동일한 일치 기능을 가지고 있습니다.

패턴의 괄호(즉, 원형 괄호) 사이의 문자는 일치 그룹을 정의합니다. 여는 중괄호가 ?<name>으로 시작하면 해당 그룹은 꺾쇠 괄호 사이에 지정된 이름에 할당됩니다. 그렇지 않으면 그룹은 패턴에서 그룹의 위치에 따라 1부터 시작하는 인덱스에 할당됩니다.

일치 그룹은 대체에서 참조할 수 있습니다. 일치 그룹 참조 앞에는 달러 기호($)가 옵니다. 명명된 그룹은 $<name>을 사용하여 참조할 수 있으며, 여기서 name은 꺾쇠 괄호 사이에 다시 지정됩니다. 인덱싱된 그룹은 $1과 같이 해당 번호로 참조할 수 있습니다. $&를 사용하여 전체 refname을 참조할 수 있습니다.

일치 그룹에 슬래시가 포함된 경우 Antora는 각 슬래시를 하이픈으로 대체합니다.

Antora는 일치하는 첫 번째 패턴의 값을 사용합니다. 패턴이 refname과 일치하지 않으면 Antora는 refname을 버전으로 사용하는 것으로 대체합니다.

== 값 요구 사항

version 키에 할당된 리터럴 값에는 문자, 숫자, 점(.), 밑줄(_) 및 하이픈(-)이 포함될 수 있습니다. 호스트 플랫폼 간의 이식성을 보장하기 위해 버전 값에 사용되는 문자는 소문자여야 합니다.

값에는 공백, 슬래시(/) 또는 HTML 특수 문자(&, <, >)를 포함할 수 없습니다. UI 메뉴에서 공백, 대문자 및 기타 문자를 포함하는 버전을 표시하는 방법을 알아보려면 표시 버전 사용자 지정을 참조하세요.


