= antora.yml이란?

__antora.yml__은 두 가지 중요한 기능을 수행하는 구성 파일입니다.

. 콘텐츠 소스 루트에 __antora.yml__ 파일이 있으면 Antora에 컴포넌트 버전에 속하는 소스 파일이 포함된 형제 __modules__ 디렉터리를 찾아야 한다는 신호를 보냅니다.

. 콘텐츠 소스 루트의 __antora.yml__ 파일은 Antora가 __modules__ 폴더에 있는 표준 디렉터리에서 수집한 소스 파일에 할당하는 필수 및 선택적 컴포넌트 버전 메타데이터를 제공합니다.

== antora.yml이 콘텐츠 소스 루트에 저장되는 이유는 무엇인가요?

각 콘텐츠 소스 루트에서 시작하여 Antora는 __antora.yml__ 파일을 찾습니다. __antora.yml__을 찾으면 형제 __modules__ 디렉터리를 검색하고 모든 하위 디렉터리와 파일을 컴포넌트 버전의 일부로 간주합니다.

Antora가 콘텐츠 소스 루트에서 __antora.yml__을 찾지 못하면 __modules__ 디렉터리를 찾거나 해당 위치에서 파일을 수집하지 않습니다. 이렇게 하면 Antora가 문서 사이트의 일부가 아닌 소스 파일을 처리하기 위해 메모리와 CPU 시간을 낭비할 가능성이 최소화됩니다.

__antora.yml__ 파일은 콘텐츠 소스 파일을 디렉터리 계층 구조의 어느 곳에나 저장할 수 있는 기능을 제공합니다. 콘텐츠 소스 루트에 __antora.yml__ 파일이 포함되어 있는 한 애플리케이션 코드, 테스트 및 기타 자료를 저장하는 저장소에서 콘텐츠 소스 파일을 유지 관리하고 관리할 수 있습니다.

== antora.yml은 어떤 정보를 제공하나요?

__antora.yml__ 파일은 컴포넌트 버전을 식별, 설명 및 구성하는 필수 및 선택적 정보를 제공하므로 컴포넌트 버전 디스크립터라고 합니다. 차례로 이 메타데이터와 구성은 컴포넌트 버전에 속하는 모든 소스 파일에 적용됩니다.

이것이 바로 Antora가 여러 저장소, 디렉터리, 분기 및 태그에서 파일을 수집하여 단일 컴포넌트 버전으로 컴파일할 수 있는 이유입니다. Antora는 파일 시스템이나 저장소 위치에 따라 파일을 처리하는 대신 컴포넌트 버전 디스크립터 파일에 의해 소스 파일에 할당된 정보에 따라 파일을 변환합니다.

_antora.yml_ 파일에는 다음과 같은 필수 키가 포함되어 있습니다:

[cols="1,7", options="header"]
|===
|필수 키 |설명

|name
|버전과 함께 사용되는 컴포넌트 이름으로 컴포넌트 버전을 식별합니다. 리소스 ID의 컴포넌트 좌표와 컴포넌트 버전의 게시된 리소스에 대한 컴포넌트 URL 세그먼트로 사용됩니다.

|version
|이름과 함께 사용되는 버전으로 컴포넌트 버전을 식별합니다. 리소스 ID의 버전 좌표와 컴포넌트 버전이 버전이 없는 것으로 정의되지 않는 한 컴포넌트 버전의 게시된 리소스 URL에 대한 버전 세그먼트로 사용됩니다.

컴포넌트 버전 디스크립터 파일에서 version 키를 지정하는 것은 키의 값이 플레이북의 콘텐츠 소스에서 상속되는 경우 선택 사항입니다. 값이 refname에서 자동으로 파생되거나 refname 매핑을 기반으로 하려는 경우 콘텐츠 소스에 version 키를 지정할 수 있습니다.
|===

__antora.yml__ 파일에는 다음과 같은 선택적 키가 포함될 수 있습니다:

[cols="1,7"]
|===
|선택적 키 |설명

|asciidoc.attributes
|asciidoc 키는 attributes 키와 중첩된 키-값 쌍 목록을 허용합니다. attributes 아래에 나열된 키-값 쌍은 내장 및 사용자 정의 AsciiDoc 속성(예: idseparator: '-')과 페이지 속성을 나타냅니다. __antora.yml__의 속성은 컴포넌트 버전에 속하는 모든 페이지와 리소스(해당되는 경우)에 적용됩니다.

|display_version
|참조 UI의 컴포넌트 버전 선택기와 페이지 버전 선택기에서 프레젠테이션 목적으로만 사용되는 버전 식별자입니다. display_version은 빈 공백, 대문자 및 대부분의 문자(예: 3.0 Beta, RED WREN!)를 허용합니다.

|nav
|탐색 파일 목록을 허용합니다. nav 키 아래에 등록된 탐색 파일(예: __nav.adoc__)은 컴포넌트 버전의 페이지 메뉴에 사용됩니다.

|prerelease
|컴포넌트 버전을 사전 릴리스 버전으로 지정하고 기본 라우팅 규칙을 비활성화합니다. 키는 버전 좌표나 버전 URL 세그먼트에 영향을 주지 않고 version에 사전 릴리스 식별자(예: -alpha.2)를 추가할 수 있습니다.

|start_page
|컴포넌트 버전의 홈 페이지로 페이지를 지정합니다. 기본적으로 Antora는 컴포넌트 버전의 ROOT 모듈에 있는 __index.adoc__를 사용합니다.

|title
|참조 UI의 컴포넌트 버전 페이지 메뉴, 컴포넌트 버전 선택기 및 페이지 브레드크럼에서 정렬 및 프레젠테이션 목적으로만 사용되는 컴포넌트 이름입니다. 빈 공백, 대문자 및 광범위한 문자(예: API Manager)를 허용합니다.
|===
