= 사이트 키

``site`` 아래에 구성된 플레이북 키는 사이트의 게시된 정체성과 게시 후 특정 애플리케이션과의 상호 작용을 관리합니다.

[#site-key]
== site 키

전역 생성 사이트 파일, 서비스 계정 및 기타 공통 속성은 플레이북 파일의 ``site`` 키 아래에 정의됩니다.
이러한 설정은 사이트가 생성될 때 전체 사이트에 적용됩니다.

[,yaml]
----
site: # <.>
  title: Docs Site # <.>
  url: https://docs.example.org # <.>
  start_page: component-b::index.adoc # <.>
  robots: allow # <.>
  keys: # <.>
    google_analytics: XX-123456 # <.>
----
<.> 필수 ``site`` 키
<.> 필수 ``title`` 키
<.> 선택적 ``url`` 키
<.> 선택적 ``start_page`` 키
<.> 선택적 ``robots`` 키
<.> 선택적 ``keys`` 키
<.> ``google_analytics`` 키 예시

``site`` 카테고리의 ``title`` 키는 필수입니다.
``url`` 키는 선택사항이지만 권장됩니다.
자세한 내용은 xref:site-url.adoc#when-should-the-site-url-be-set[사이트 URL을 언제 설정해야 하나요?]를 참조하세요.
다른 키들은 선택사항입니다; 지정되지 않은 경우 Antora는 기본값을 사용합니다.
``title``, ``start_page``, ``keys``는 xref:cli:options.adoc[CLI에서도 할당]할 수 있습니다.
``url`` 키는 xref:cli:options.adoc#site-url[CLI]에서 할당하거나 xref:environment-variables.adoc[환경 변수]를 사용하여 할당할 수 있습니다.

[#site-reference]
== 사용 가능한 사이트 키

[cols="3,6,1"]
|===
|사이트 키
|설명
|필수 +
여부

|xref:site-keys.adoc[keys]
|UI 템플릿이나 확장에서 참조할 계정 및 API 키.
Google Analytics와 같은 서비스 통합을 위한 계정 식별자를 지정하는 이름-값 쌍의 맵을 받습니다.
|아니오

|xref:site-robots.adoc[robots]
|Antora가 _robots.txt_ 파일을 생성할지 여부를 지정합니다.
``allow``, ``disallow``, 그리고 사용자 정의 다중 라인 문자열 값을 받습니다.
형제 ``url`` 키가 설정되지 않은 경우 무시됩니다.
|아니오

|xref:site-start-page.adoc[start_page]
|사이트의 시작 페이지를 지정하는 페이지의 리소스 ID를 받습니다.
|아니오

|xref:site-title.adoc[title]
|사이트의 제목을 지정합니다.
|예

|xref:site-url.adoc[url]
|사이트의 기본 URL을 지정합니다.
|아니오
|===