= Get Antora - Windows Requirements

Antora는 모든 Node.js 설치에서 실행되는 휴대용 애플리케이션입니다. Node.js는 Windows용으로 배포되고 Windows에서 실행되므로 Antora는 추가 요구 사항 없이 Windows에서 실행됩니다.

이 페이지에서 다음을 배울 수 있습니다:

- Windows 패키지 관리자인 Chocolatey를 설치하는 방법.
- Node.js를 설치하는 방법.

이전에 Antora를 설치한 적이 없다면 Antora를 설치하고 문서 사이트를 생성하는 데 사용하기 전에 이 페이지의 단계를 완료해야 합니다. Antora는 Node.js를 기반으로 하므로 Antora를 설치하고 실행하려면 컴퓨터에 Node.js(명령: node, npm 및 npx)가 설치되어 있어야 합니다.

== Node.js

Antora에는 Node.js의 모든 활성 LTS 또는 유지 관리 LTS 버전을 사용할 수 있지만, 최신 성능 및 보안 향상의 이점을 누리려면 가장 최근의 활성 LTS 버전을 사용하는 것이 좋습니다. Node.js 릴리스 일정에는 활성 Node.js LTS 버전이 표시됩니다.

Node.js가 설치되어 있는지, 어떤 버전인지 확인하려면 PowerShell을 열고 다음을 입력하세요:

[source]
----
$ node --version
----

다음과 같은 버전 문자열이 표시되어야 합니다:

[source]
----
v16.20.2
----

**명령이 오류와 함께 실패하면** Node.js가 설치되어 있지 않은 것입니다. Windows에서 Node.js를 설치하는 가장 좋은 방법은 Chocolatey를 사용하는 것입니다. 컴퓨터에 Chocolatey가 없는 경우 Chocolatey 설치로 이동하여 설정하세요. 그렇지 않으면 nvm 및 Node 설치로 바로 건너뛰세요.

**명령이 활성 LTS 버전이 아닌 버전을 반환하는 경우** nvm을 사용하여 활성 Node.js LTS 버전으로 업그레이드하세요.

**명령이 활성 Node.js LTS 버전을 반환하면** Antora를 설치할 준비가 된 것입니다.

== Chocolatey 설치

Node Version Manager(nvm) 및 Node.js를 설치하는 가장 좋은 방법은 Windows용 패키지 관리자인 Chocolatey를 사용하는 것입니다.

. PowerShell 터미널을 열고 PowerShell 아이콘을 마우스 오른쪽 버튼으로 클릭하고 관리자 권한으로 실행을 선택하여 관리자로 실행합니다.

. 터미널에 다음 명령을 입력하세요:
+
[source]
----
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
----

이제 nvm 및 Node.js를 설치할 준비가 되었습니다.

== nvm 및 Node.js 설치

. PowerShell 터미널을 열고 PowerShell 아이콘을 마우스 오른쪽 버튼으로 클릭한 다음 **관리자 권한으로 실행**을 선택합니다.
+
[TIP]
====
앞 섹션의 지침을 사용하여 Chocolatey를 설치한 경우 이미 열려 있는 동일한 터미널(관리자로 실행 중)을 사용하세요.
====

. Windows용 Node Version Manager(nvm)를 설치하려면 터미널에 다음 명령을 입력하세요:
+
[source,console]
----
$ choco install -y nvm
----

. 터미널을 닫습니다.

. 새 일반 PowerShell 터미널을 열고 nvm을 사용하여 Node.js를 설치합니다.
+
[source,console]
----
$ nvm install 16.20.2
----
+
[IMPORTANT]
====
nvm-windows#214가 해결될 때까지 nvm for Windows를 사용할 때는 Node.js의 정확한 버전(예: 16.20.2)을 입력해야 합니다.
====

이제 Node.js가 설치되었으므로 Antora를 설치할 준비가 되었습니다.

.nvm 및 CI 환경
[sidebar]
--
관리자 PowerShell에 다음 명령을 입력하여 nvm을 설치하지 않고 Node.js의 LTS 릴리스를 직접 설치할 수 있습니다:

[source,console]
----
$ choco install -y nodejs-lts
----

그러나 많은 CI 환경에서는 빌드 작업에 사용되는 Node.js 버전을 설치하기 위해 nvm을 사용합니다. nvm을 사용하면 프로덕션 사이트를 생성하고 게시하는 데 사용되는 환경과 설정을 긴밀하게 정렬할 수 있습니다.
--

== nvm을 사용하여 Node.js 업그레이드

nvm이 설치되어 있지만 Node.js 버전이 활성 LTS 릴리스가 아닌 경우 터미널에 다음 명령을 입력하세요:

[source,console]
----
$ nvm install 16.20.2
----

[IMPORTANT]
====
nvm for Windows를 사용할 때는 Node.js의 전체 버전(즉, nvm install 16.20.2)을 입력해야 합니다.
====

== 더 알아보기

Node.js를 설치했으면 Antora를 설치할 준비가 된 것입니다.
