= 인라인 Image 추가

이 페이지에서 다음을 배웁니다:

* [*] AsciiDoc 인라인 이미지 매크로의 구조.
* [*] 리소스 ID를 사용하여 인라인 이미지를 삽입하는 방법.

== AsciiDoc 인라인 이미지 매크로

AsciiDoc 인라인 이미지 매크로는 이미지의 소스 파일을 부분 또는 페이지에 포함하는 데 사용됩니다. 인라인 이미지 매크로는 PNG, JPG, SVG 및 GIF(정적 및 애니메이션) 이미지 파일의 Antora 리소스 ID를 값으로 받아들입니다.

Antora가 실행되면 인라인 이미지 매크로에 의해 참조되는 이미지 파일이 사이드바 블록과 같은 다른 요소의 흐름에 포함되어 게시된 페이지에 표시됩니다. 예를 들어, 이것은 인라인 이미지 매크로를 사용하여 이 단락에 포함된 SVG 이미지 image:img/blue-dot.svg[]입니다.

=== 인라인 이미지 매크로 구조

예제 1은 인라인 이미지 매크로의 구조를 보여줍니다.

.예제 1. 인라인 이미지 매크로
[source,asciidoc]
----
This sentence contains an inline image:resource-id-of-target-image.ext[optional attribute,optional attribute] image. <1>
----
<1> 인라인 이미지는 내용의 흐름에 삽입됩니다. 매크로 이름 뒤에 하나의 콜론(:)으로 지정됩니다.

최소한 인라인 이미지 매크로는 매크로의 접두사(pass:[image:]), 대상 이미지의 리소스 ID 및 대괄호([])로 구성됩니다. 대상 이미지는 현재 페이지에서 참조하는 이미지 소스 파일입니다. 대상 이미지는 현재 페이지의 내용에서 인라인 또는 블록 이미지 매크로에 리소스 ID를 할당하여 참조됩니다. 현재 페이지는 대상 이미지를 참조하는 이미지 매크로를 포함하는 페이지 소스 파일입니다.

예제 1에 표시된 인라인 이미지 매크로의 각 부분은 아래에서 더 자세히 설명합니다.

pass:[image:]::
인라인 이미지 매크로는 매크로의 이름 image와 하나의 콜론(:)으로 시작합니다.

대상 이미지의 리소스 ID::
이미지 매크로는 이미지 소스 파일의 리소스 ID를 값으로 받아들입니다. 값은 매크로 이름(image:) 뒤의 콜론 바로 뒤에 입력됩니다. 현재 페이지와 관련하여 대상 이미지의 컴포넌트 버전 및 모듈에 따라 대상 이미지의 리소스 ID 좌표를 얼마나 많이 지정해야 하는지가 결정됩니다. 이미지 매크로에서 이미지를 참조할 때는 대상 이미지의 리소스 ID에 image$ 패밀리 좌표를 포함할 필요가 없습니다. 런타임에 자동으로 적용됩니다.

[optional attribute,optional attribute]::
인라인 이미지 매크로는 대상 이미지의 리소스 ID 끝에 대괄호([])로 완성됩니다. 대괄호를 비워 둘 수 있으며, 선택적 속성을 하나 이상 쉼표로 구분된 목록으로 대괄호 안에 할당할 수 있습니다.

다음 섹션인 인라인 이미지 포함에서는 인라인 이미지 매크로를 단계별로 설정하는 방법을 설명합니다.

== 인라인 이미지 포함

인라인 이미지 매크로를 사용하여 페이지(현재 페이지)에 이미지(대상 이미지)를 삽입하는 데 필요한 인라인 이미지 매크로와 리소스 ID 좌표를 분석해 보겠습니다.

. IDE 또는 텍스트 편집기에서 이미지를 삽입할 페이지를 엽니다. 이 연습에서는 __satellites.adoc__ 파일을 열었습니다. __satellites.adoc__는 현재 페이지입니다.

. __satellites.adoc__에서 인라인 이미지 __blue-dot.svg__를 포함해 보겠습니다. 대상 이미지를 표시할 현재 페이지 내용 흐름의 위치를 선택합니다. 매크로의 이름 다음에 하나의 콜론을 입력합니다(``image:``).
+
.예제 2. satellites.adoc (현재 페이지)
[source,asciidoc]
----
Look for the image:
----

. 콜론 바로 뒤에 대상 이미지 파일의 리소스 ID를 입력합니다. 이 예제에서는 __blue-dot.svg__와 __satellites.adoc__ 모두 동일한 컴포넌트 버전과 모듈에 속하며 대상 이미지가 image 패밀리 디렉토리의 루트에 저장되어 있습니다. 따라서 __blue-dot.svg__의 파일 이름과 확장자만 인라인 이미지 매크로의 값으로 할당하면 됩니다.
+
.예제 3. satellites.adoc (현재 페이지)
[source,asciidoc]
----
Look for the image:blue-dot.svg
----
+
__blue-dot.svg__의 리소스 ID에 패밀리 좌표가 포함되어 있지 않다는 점에 주목하세요. Antora는 이미지 매크로에 할당된 리소스 ID에 자동으로 image$ 패밀리 좌표를 적용합니다.

. 대상 이미지의 리소스 ID 바로 뒤에 왼쪽 대괄호([)를 입력한 다음 오른쪽 대괄호(])를 입력합니다.
+
.예제 4. satellites.adoc (현재 페이지)
[source,asciidoc]
----
Look for the image:blue-dot.svg[]
----
+
이 예제에서는 인라인 이미지 매크로에 선택적 속성을 적용하지 않았습니다. 그러나 대괄호 안에 쉼표로 구분된 목록으로 하나 이상의 속성을 지정할 수 있습니다.

. 마지막 대괄호(]) 뒤에 kbd:[SPACE] 바를 한 번 눌러 매크로 뒤에 공백을 삽입한 다음 내용을 계속 입력합니다.
+
.예제 5. satellites.adoc (현재 페이지)
[source,asciidoc]
----
Look for the image:blue-dot.svg[] on the console.
----

이것으로 끝입니다! AsciiDoc 인라인 이미지 매크로를 사용하여 대상 이미지(__blue-dot.svg__)를 현재 페이지(__satellites.adoc__)에 삽입했습니다.

== 더 알아보기

다른 모듈, 문서 컴포넌트 및 버전에 속하는 이미지를 포함하는 방법을 알아보려면  Image resource ID examples를 참조하세요.
