= CLI 시작하기

명령줄 인터페이스에 익숙하지 않은 경우 다음 섹션에서는 이 설명서에 사용된 명령줄 및 터미널 개념에 대한 몇 가지 기본 정보를 제공합니다.

== 명령 입력 및 구조

Antora CLI는 기본 호출, 명령(프로그램용), 옵션 및 인수 형태의 명령 입력을 허용합니다. 터미널에 입력되면 지정된 입력을 사용하여 명령이 실행됩니다.

[source,console]
----
$ antora <command> [options] <arguments>
----

기본 호출::
Antora CLI 명령은 프로그램 이름(즉, antora)인 기본 호출로 시작합니다. 이것은 명령 인터프리터에게 Antora CLI를 실행하라고 지시합니다. 시스템이 프로그램 이름 자체를 찾을 수 없는 경우 대신 antora 바이너리 스크립트의 경로를 지정해야 합니다(예: npx antora).

명령 (command)::
명령은 Antora에게 수행할 작업을 알려줍니다. 한 번에 하나의 명령만 지정할 수 있습니다.

옵션 (options)::
+
하나 이상의 옵션을 명령 뒤에 지정할 수 있습니다. 옵션의 전체 이름 앞에는 두 개의 하이픈(--)이 붙고, 약식 이름 앞에는 하나의 하이픈(-)이 붙습니다.
+
일부 옵션은 동작을 켜거나 끄고 다른 옵션은 값을 허용합니다. 값을 허용하는 옵션은 옵션의 이름과 값 사이에 공백을 두고(--option value) 또는 이름과 값 사이에 등호를 사용하여(--option=value) 작성할 수 있습니다.

인수 (arguments)::
인수는 기본 호출 및 모든 옵션 뒤에 입력됩니다. 인수를 익명 옵션으로 생각할 수 있습니다. generate 명령은 플레이북 파일의 경로인 단일 인수만 허용합니다.

환경 변수::
(명령 자체에 없는) 환경 변수는 터미널의 상태에서 읽습니다. 환경 변수는 플레이북 파일의 해당 키를 재정의하지만 해당 CLI 옵션에 의해 자체적으로 재정의됩니다.

== 터미널 규칙

터미널 애플리케이션을 처음 사용하는 경우 이 설명서에 사용된 일반적인 규칙은 터미널을 나타내며 터미널과 상호 작용하는 방법을 설명합니다.

프롬프트($)::
터미널 명령 프롬프트는 이 설명서 전체의 예제에서 달러 기호($)로 표시됩니다. 터미널을 열 때 표시되는 프롬프트는 사용하는 터미널 애플리케이션에 따라 다릅니다. 명령을 입력하거나 복사할 때 $ 프롬프트를 포함하지 마십시오.

작업 디렉터리::
+
모든 명령은 현재 작업 디렉터리에서 실행됩니다. 명령 입력과 관련된 프로세스는 작업 디렉터리를 기준으로 해석됩니다. 현재 작업 디렉터리는 터미널의 명령 프롬프트($) 바로 왼쪽에 표시되는 경우가 많지만, 이는 사용 중인 터미널 애플리케이션과 구성 방식에 따라 다릅니다.
+
이 설명서의 몇 가지 예제는 프롬프트 앞에 작업 디렉터리의 이름을 도움말 힌트로 표시합니다.

[source]
----
name-of-working-directory $ antora antora-playbook
----

명령을 복사할 때 이 텍스트나 프롬프트를 포함하지 마십시오.

대체 가능한 입력::

많은 옵션은 콘텐츠, 환경 및 사이트 요구 사항에 따라 정의됩니다. 이 설명서의 일부 명령줄 예제는 꺾쇠 괄호(< >)로 정의하는 입력을 호출합니다. 괄호 안의 텍스트는 입력을 설명하거나 일반적인 입력 형식을 나타냅니다(예: --require <path/to/library-script>, --title '<Title of Your Site>'). 터미널에서 명령을 작성할 때 대표 텍스트를 입력으로 바꾸고 꺾쇠 괄호(< >)로 묶지 마십시오.

명령 출력::

명령이 정보를 반환하면 실행된 명령 아래 줄에 터미널에 출력이 표시됩니다. 출력 줄에는 명령 프롬프트($)가 표시되지 않습니다.

