= 사이트 미리보기

이 페이지에서는 다음을 배웁니다:

* [x] 로컬에서 사이트를 미리 보는 방법.
* [x] 로컬에서 사이트를 미리 보기 위해 선택적으로 로컬 서버를 실행하는 방법.

== 로컬 사이트 미리보기

Antora는 정적 사이트를 생성하므로 **사이트를 보기 위해 웹 서버에 사이트를 게시할 필요가 없습니다**. Antora에서 생성된 사이트는 브라우저의 로컬 file: 프로토콜을 사용해도 잘 작동합니다. Antora 사이트의 이러한 특성은 작업을 미리 보는 데 필수적인 도구입니다.

사이트를 로컬에서 보려면 브라우저의 대상 폴더 내에 있는 HTML 페이지로 이동하십시오. 데모를 따라하고 있다면 프로젝트에서 __build/site/index.html__ 파일을 찾으십시오. 위치 표시줄에서 볼 수 있는 브라우저의 file: 프로토콜을 통해 HTML 페이지를 볼 것입니다.

== 로컬 서버 실행 (선택 사항)

웹 서버 없이도 사이트를 볼 수 있지만 색인화된 URL, 캐싱 또는 file: 프로토콜에서 작동하지 않는 스크립트와 같은 특정 기능을 테스트하려면 웹 서버를 통해 사이트를 봐야 할 수도 있습니다. 이러한 목적으로 http-server 패키지를 사용할 수 있습니다. http-server는 Node.js용 간단한 정적 웹 서버입니다.

http-server를 사용하는 가장 간단한 방법은 npx를 사용하여 호출하는 것입니다:
[source]
----
demo-site $ npx http-server -v
----

원하는 경우 대신 npm을 사용하여 패키지를 전역으로 설치할 수 있습니다.

[source]
----
demo-site $ npm i -g http-server
----

그러면 PATH에 같은 이름의 명령이 배치되므로 npx 접두사를 붙일 필요가 없습니다. 이 튜토리얼에서는 npx를 사용하여 http-server를 호출한다고 가정하겠습니다.

이제 생성된 사이트의 위치로 웹 서버를 가리켜 시작하십시오. 터미널에서 명령 이름 npx http-server를 입력한 다음 생성된 사이트의 위치(즉, 출력 디렉터리)를 입력합니다. 캐싱을 비활성화하려면 -c-1 플래그를 추가하는 것이 좋습니다.

[source]
----
demo-site $ npx http-server build/site -c-1
----

명령을 실행하면 웹 서버의 로컬 주소가 터미널에 표시됩니다. 터미널에 다음 출력이 표시되어야 합니다:

[source]
----
Starting up http-server, serving build/site
Available on:
  http://127.0.0.1:8080
  http://192.168.1.8:8080
Hit CTRL-C to stop the server
----


제공된 첫 번째 URL을 브라우저의 위치 표시줄에 붙여넣어 로컬 웹 서버를 통해 사이트를 봅니다.

서버를 중지하려면 kbd:[Ctrl,C]를 누르십시오.

TIP: 서버를 시작할 때 포트 충돌이 발생하면(즉, listen EADDRINUSE: address already in use), -p <port> 옵션을 사용하여 다른 포트로 변경할 수 있습니다. 예를 들어 명령에 -p 5000을 추가하여 포트 5000으로 전환합니다.

[source]
----
demo-site $ npx http-server build/site -c-1 -p 5000
----
