

== Generate Your Site - Run Antora in a Container

=== Antora 프로젝트는 컨테이너 내부에서 antora 명령을 실행하는 데 사용할 수 있는 Docker 이미지를 제공합니다(이를 컨테이너화라고 합니다). 이 접근 방식의 이점은 Antora를 설치하지 않고 바로 실행할 수 있다는 것입니다. 필요한 것은 Docker 또는 Podman뿐입니다.
가정:

Docker(명령: docker) 또는 Podman(명령: podman)이 시스템에 설치되어 있습니다.
Docker 데몬이 시스템에서 실행 중입니다(Podman을 사용할 때는 필요하지 않음).
자신의 플레이북을 구성했거나 Demo 플레이북을 사용하고 있습니다.

이 페이지에서는 다음을 배웁니다:

Antora의 공식 Docker 이미지를 사용하여 컨테이너 내부에서 Antora를 실행하는 방법.
컨테이너에 로컬 디렉터리에 대한 액세스 권한을 부여하는 방법.
자신의 이미지를 만들기 위해 Antora용 Docker 이미지를 확장하는 방법.

=== Antora용 Docker 이미지
Docker는 컨테이너 이미지(공식적으로 OCI 이미지)를 실행하기 위한 도구입니다. 컨테이너 이미지를 상자 안의 애플리케이션으로 생각할 수 있습니다. 해당 상자 내부에는 코드, 런타임, 설정 및 운영 체제 자체를 포함하여 애플리케이션을 실행하는 데 필요한 모든 것이 있습니다. 컨테이너는 소프트웨어를 호스트 환경에서 격리할 뿐만 아니라 신속하게 실행할 수 있게 만듭니다. 그리고 그것은 Antora를 발견하고 탐색하는 완벽한 방법입니다!
Antora 프로젝트는 컨테이너 내부에서 Antora를 실행하기 위한 antora/antora라는 공식 Docker(OCI) 이미지를 제공합니다. 이 이미지는 Docker Hub의 antora/antora 프로젝트에 게시됩니다.
이 이미지는 antora 명령을 대체할 수 있습니다. 자신의 컴퓨터 또는 CI 환경에 antora 명령을 설치하는 대신 컨테이너를 실행하여 명령을 실행하기만 하면 됩니다. 실제로 Antora 문서 사이트의 CI 작업은 이 이미지를 사용하여 현재 읽고 있는 문서를 생성합니다.
실행 방법을 알아보겠습니다.
=== Antora 이미지 실행
이 이미지 사용 방법을 시연하기 위해 Antora 데모 사이트를 사용할 것입니다. 데모 사이트의 플레이북 저장소를 복제한 다음 새로 생성된 폴더로 전환하십시오:
[source,console]
~ $ git clone https://gitlab.com/antora/demo/docs-site.git && cd "$(basename $_. git)"
그런 다음 Docker 클라이언트를 사용하여 이 이미지의 진입점 명령(즉, antora)을 호출하려면 docker run 명령을 실행하십시오:
[source,console]
docs-site $ docker run -u $(id -u) -v $PWD:/antora:Z --rm -t antora/antora antora-playbook.yml
이 명령은 이미지에서 새 컨테이너를 회전시키고, 현재 디렉터리를 컨테이너 내부의 /antora 경로로 마운트하고, (현재 사용자로) antora 명령을 실행한 다음, 컨테이너를 중지하고 제거합니다. 로컬에 설치된 antora 명령을 실행하는 것과 정확히 같지만, 컨테이너의 강력한 기능을 사용하여 이를 수행하는 것입니다!
=== /.cache에 액세스할 때 권한 거부 오류 수정
로컬 uid(즉, $(id -u))가 1000이 아닌 경우 컨테이너에서 Antora를 실행할 때 다음과 같은 오류가 발생할 수 있습니다:
[source]
error: EACCES: permission denied, mkdir '/.cache'
이는 기본 캐시 디렉터리가 사용자의 홈 디렉터리에 상대적으로 확인되고 매핑되지 않은 사용자의 홈 디렉터리가 /이기 때문에 발생합니다. 따라서 메시지에 /.cache 경로가 표시되며, 이는 쓰기 가능한 위치가 아닙니다.
이 문제에 대한 해결책은 캐시 디렉터리의 위치를 수정하는 것입니다.
또는 Podman을 사용하여 이 이미지의 진입점 명령을 호출하려면 podman run 명령을 실행할 수 있습니다:
[source,console]
docs-site $ podman run -v $PWD:/antora:Z --rm -t antora/antora antora-playbook.yml
Podman의 장점은 보안이 더 강화된다는 것입니다. 사용자 공간에서 실행되며 데몬에 의존하지 않습니다. Podman을 계속 사용하려면 아래 명령에서 docker를 podman으로 바꾸고(-u 옵션 삭제) 사용하십시오.
=== 로컬 경로와 정렬
볼륨 매핑 $PWD:/antora:Z를 사용하는 경우 Antora에서 보고하는 로컬 경로가 시스템에 다시 매핑되지 않는 것을 알 수 있습니다. 이는 Antora가 /antora를 현재 작업 디렉터리로 간주하기 때문입니다. 이 문제를 해결하려면 현재 작업 디렉터리를 컨테이너에 매핑한 다음 Antora를 실행하기 전에 해당 디렉터리로 전환해야 합니다. 이를 위해 다음 볼륨 마운트를 대신 사용하십시오:
[source]
-v $PWD:$PWD:Z -w $PWD
-w 옵션이 추가된 것을 주목하십시오. 이 옵션은 Antora에게 /antora에서 매핑한 디렉터리로 전환하도록 지시합니다. 이제 Antora가 로컬 경로를 보고할 때 호스트 시스템의 경로와 일치합니다.
=== 옵션 플래그
실행 명령에 사용되는 일부 옵션 플래그에 대한 설명은 다음과 같습니다:

-t
이 플래그는 pseudo-TTY를 할당하며, Git 작업에 대한 진행 표시줄을 보려면 이 플래그가 필요합니다. 이러한 진행 표시줄을 볼 필요가 없다면 이 플래그를 생략할 수 있습니다.
-u $(id -u)
이 옵션은 Docker에게 현재 사용자로 진입점 명령(즉, antora)을 실행하도록 지시합니다. 이 옵션을 지정하지 않고 볼륨 마운트에 :Z 수정자를 사용하면 생성된 파일이 (대부분) root 사용자로 작성되어(삭제하기가 상당히 까다로워짐) 작성됩니다. 이 옵션은 Podman을 사용할 때는 필요하지 않습니다.
-v
로컬 시스템의 현재 디렉터리($PWD로 표시됨)를 컨테이너 내부의 /antora 디렉터리에 매핑하는 볼륨 마운트입니다. 이를 통해 컨테이너에서 작성한 파일이 로컬 시스템에서 볼 수 있으며, 이는 컨테이너를 사용하는 전체 요점입니다.
:Z(볼륨 마운트에)
이 플래그는 Fedora와 같이 SELinux가 활성화된 Linux 배포판을 실행하는 경우에만 필요합니다. 이 옵션을 사용하면 SELinux를 실행할 때 볼륨 마운트를 사용할 수 있습니다.
-w
이 옵션은 Docker에게 진입점 명령을 호출하기 전에 지정된 디렉터리(즉, $PWD)로 전환하도록 지시합니다. 컨테이너 내부의 /antora가 아닌 다른 디렉터리에서 antora 명령을 실행하려는 경우 이 옵션을 사용합니다.

--privileged 플래그는 유혹적이지만 필요하지 않습니다. SELinux에서 볼륨 마운트 사용에 대해 자세히 알아보려면 블로그 게시물 "Using Volumes with Docker can Cause Problems with SELinux"를 참조하십시오.
=== 캐시 디렉터리 위치
Antora가 기본 캐시 디렉터리에 쓸 수 없거나 캐시 디렉터리가 마운트된 디렉터리 내에 있기를 원하는 경우 --cache-dir 옵션을 사용하여 플레이북 기준 디렉터리를 지정하십시오:
[source,console]
docs-site $ docker run -u $(id -u) -v $PWD:/antora:Z --rm -t antora/antora --cache-dir=./.cache/antora antora-playbook.yml
다른 방법은 컨테이너 사용자의 HOME 디렉터리를 재정의하는 것입니다:
[source,console]
docs-site $ docker run -u $(id -u) -e HOME=/antora -v $PWD:/antora:Z --rm -t antora/antora antora-playbook.yml
두 경우 모두 Antora에 의해 캐시되거나 생성된 모든 파일은 마운트된 디렉터리 내에 깔끔하게 포함되며 현재 사용자가 소유합니다. 이 구성은 또한 실행 간에 캐시가 유지된다는 이점이 있으므로 상관없이 사용하는 것이 좋습니다.
=== 컨테이너 입력
antora 명령을 실행하는 대신 컨테이너에 쉘을 입력하려면 컨테이너 실행 명령에 쉘(ash) 이름을 추가하십시오:
[source,console]
docs-site $ docker run -u $(id -u) -v $PWD:/antora:Z --rm -it antora/antora ash
이제 실행 중인 컨테이너 내부 어디에서나 antora 명령을 실행할 수 있습니다. 이 모드는 편집하는 동안 사용하면 유용합니다. 컨테이너가 계속 실행되므로 antora 명령을 신속하게 실행할 수 있습니다.
기본 Antora 이미지에 사이트에 필요한 모든 것이 포함되어 있지 않은 경우 이를 확장할 수 있습니다.
=== Antora 이미지 확장
이 이미지를 자신의 Docker 이미지의 기반으로 사용할 수 있습니다. 이 이미지에는 Yarn이 사전 구성되어 있으므로 AsciiDoc에 다이어그램 지원을 추가하기 위한 Asciidoctor Kroki(asciidoctor-kroki)와 같은 추가 확장 라이브러리를 설치할 수 있습니다.
docker-antora 저장소를 복제하고 해당 저장소로 전환하십시오:
[source,console]
~ $ git clone https://gitlab.com/antora/docker-antora.git && cd "$(basename $_.git)"
Dockerfile.custom이라는 사용자 정의 Dockerfile 파일을 만듭니다.
파일에 다음 내용을 채웁니다:
.예제 1. Dockerfile.custom
[source]
FROM antora/antora
RUN yarn global add asciidoctor-kroki <1>
<1> 기본 이미지에 사용자 정의 확장을 추가합니다.
다음 명령을 사용하여 이미지를 빌드하십시오:
[source,console]
docker-antora $ docker build -t local/antora:custom -f Dockerfile.custom .

빌드가 완료되면 시스템에 local/antora:custom이라는 새 이미지를 사용할 수 있습니다. 모든 이미지 목록을 보려면 다음 명령을 실행하십시오:
[source,console]
docker images
이 이미지를 실행하려면 플레이북 프로젝트로 다시 전환하고 다음과 같이 컨테이너를 실행하십시오:
[source,console]
docs-site $ docker run -u $(id -u) -v $PWD:/antora:Z --rm -t local/antora:custom antora-playbook.yml
이 이미지를 다른 사람과 공유하려면 게시해야 합니다. 방법을 알아보려면 Docker 문서를 참조하십시오.
