= 리소스 ID 좌표

== 좌표 구문과 순서

리소스 ID에는 버전, 컴포넌트, 모듈, 패밀리 및 파일의 다섯 가지 좌표가 포함됩니다. Antora는 파일, 표준 디렉터리 세트 및 컴포넌트 버전 디스크립터의 정보를 기반으로 이러한 좌표에 값을 할당하여 소스 파일에 대한 리소스 ID를 구성합니다. 리소스에 할당된 리소스 ID 좌표의 시퀀스를 사용하여 리소스가 속한 컴포넌트 버전에 관계없이 다른 리소스에서 리소스를 참조할 수 있습니다.

그림 1은 완전히 한정된 리소스 ID의 좌표 유형과 순서를 보여줍니다.

.완전히 한정된 Antora 리소스 ID의 다이어그램
image::full-resource-id.svg[align=center]

**완전히 한정된 리소스 ID**는 모든 좌표가 지정된 리소스 ID입니다. 리소스의 완전히 한정된 리소스 ID를 자주 사용할 필요는 없을 것입니다. 리소스를 참조할 때 지정하는 리소스 ID 좌표의 수는 다음에 따라 다릅니다:

- 대상 리소스와 관련하여 현재 페이지의 컴포넌트 버전 및 모듈,
- 대상 리소스의 패밀리,
- 대상 리소스를 참조하는 데 사용되는 AsciiDoc 구문.

**대상 리소스**는 AsciiDoc 매크로, include 지시문 또는 기타 구문에서 해당 리소스 ID를 지정하여 참조되는 리소스 소스 파일입니다. 현재 페이지는 대상 리소스를 참조하는 AsciiDoc 구문을 포함하는 페이지 파일입니다.

.현재 페이지에서 대상 리소스를 참조하는 xref의 예
[.text-center]
image::target-resource.svg[]

figure 2에서 __satellites.adoc__는 현재 페이지이고 파일 이름이 __modes.adoc__인 리소스는 xref 매크로에 의해 참조되는 대상 리소스입니다. 다음 섹션에서는 대상 리소스의 각 좌표 값을 결정하는 방법과 각 좌표를 사용하는 시기에 대해 설명합니다.

== 버전 좌표

버전 좌표는 대상 리소스가 속한 컴포넌트의 버전과 동일한 값입니다. 버전의 값은 version 키에 할당됩니다. version 키는 리소스의 컴포넌트 버전을 정의하는 __antora.yml__ 파일 또는 플레이북의 콘텐츠 소스에 지정됩니다. 이 콘텐츠 소스는 Antora가 컴포넌트 버전의 파일을 수집한 위치를 지정합니다.

버전 좌표는 동일한 컴포넌트의 다른 버전 또는 다른 컴포넌트의 특정 버전에 있는 리소스를 참조하는 데 사용해야 합니다. 리소스 ID에 버전 좌표를 입력할 때는 항상 첫 번째 좌표여야 하며 at 기호(@)로 끝나야 합니다. 컴포넌트 좌표가 지정되지 않은 경우 현재 컴포넌트가 사용됩니다. 버전 좌표를 지정하지 않고 컴포넌트 좌표를 지정하면 해당 컴포넌트의 최신 버전이 선택됩니다.

== 컴포넌트 좌표

컴포넌트 좌표는 대상 리소스가 속한 컴포넌트의 이름입니다. 컴포넌트 이름은 리소스의 컴포넌트 버전을 정의하는 __antora.yml__ 파일의 name 키로 지정됩니다.

대상 리소스와 현재 페이지가 서로 다른 문서 컴포넌트에 속할 때는 컴포넌트 좌표를 사용해야 합니다. 컴포넌트 이름은 리소스 ID의 모듈 좌표 앞에 입력되며 바로 뒤에 콜론(:) 하나가 옵니다. 버전 좌표를 지정하지 않고 컴포넌트 좌표를 지정하면 해당 컴포넌트의 최신 버전이 선택됩니다.

== 모듈 좌표

모듈 좌표는 대상 리소스가 속한 모듈의 이름입니다. 모듈 이름은 리소스가 저장된 모듈 디렉터리에서 파생됩니다.

대상 리소스와 현재 페이지가 서로 다른 모듈에 속할 때는 모듈 좌표를 사용해야 합니다. 모듈 이름은 패밀리 좌표가 있는 경우 패밀리 좌표 앞에, 패밀리 좌표가 없는 경우 파일 좌표 앞에 입력됩니다. 모듈 이름 바로 뒤에는 콜론(:) 하나가 옵니다.

모듈 좌표가 link, kbd, menu 등과 같은 내장 AsciiDoc 매크로의 이름으로 끝나는 경우 백슬래시를 접두사로 사용하여 좌표의 해당 부분을 이스케이프해야 할 수 있습니다. 예를 들어 monolink 및 redmenu와 같은 모듈 좌표는 리소스 ID에서 mono\link 및 red\menu로 입력해야 할 수 있습니다.

== 패밀리 좌표

패밀리 좌표는 대상 리소스가 속한 패밀리의 이름을 식별합니다. 패밀리는 리소스가 저장된 패밀리 디렉터리에서 파생됩니다. 리소스 ID를 구성할 때 패밀리 이름 끝에 있는 "s"를 제거하고 달러 기호($)로 바꿉니다. 유효한 패밀리 좌표는 page$, image$, partial$, example$ 및 attachment$입니다.

패밀리 좌표를 리소스 ID에 입력해야 하는지 여부는 다음에 따라 다릅니다:

- 대상 리소스의 패밀리,
- 대상 리소스를 참조하는 데 사용되는 AsciiDoc 구문.

예를 들어 xref 매크로를 사용하여 페이지를 참조하는 경우 패밀리 좌표를 지정하지 않으면 xref 매크로가 기본적으로 page$ 패밀리 좌표를 적용하므로 page$ 패밀리 좌표는 필요하지 않습니다. 다음 표는 참조되는 리소스와 리소스를 참조하는 구문에 따라 패밀리 좌표가 필요한 경우를 나열합니다.

[cols="2,2,4"]
|===
|참조되는 리소스 |리소스를 참조하는 구문 |패밀리 좌표 필요 여부?

// Attachment
|Attachment
|Xref 매크로
|예, attachment$ 좌표가 필요합니다. 첨부 파일을 참조하세요.

// Example
|Example
|Include 지시문
|예, example$ 좌표가 필요합니다. 예제 포함을 참조하세요.

// Image
.3+|Image |블록 이미지 매크로
|아니요, 패밀리 좌표는 필요하지 않습니다. 블록 이미지 추가 및 이미지 리소스 ID 예제를 참조하세요.
|인라인 이미지 매크로
|아니요, 패밀리 좌표는 필요하지 않습니다. 인라인 이미지 추가 및 이미지 리소스 ID 예제를 참조하세요.
|Xref 매크로
|예, image$ 좌표가 필요합니다.

// Page
.2+|Page
|Xref 매크로
|아니요, 패밀리 좌표는 필요하지 않습니다. Xref 매크로 및 페이지 링크를 참조하세요.
|Include 지시문
|아니요, 패밀리 좌표는 필요하지 않습니다. 페이지 포함을 참조하세요.

// Partial
|Partial
|Include 지시문
|예, partial$ 좌표가 필요합니다. 부분 포함을 참조하세요.
|===

== 파일 좌표

파일 좌표는 대상 리소스의 소스 파일에 대한 패밀리 디렉터리 기준 상대 경로를 지정합니다. 파일 좌표는 다음 경우를 제외하고 리소스의 파일 확장자를 지정해야 합니다:

- 대상 리소스에 Dockerfile과 같은 파일 확장자가 없는 경우,
- 대상 리소스가 부분 또는 예제인 경우.

패밀리 디렉터리의 루트에 저장된 리소스의 파일 좌표는 리소스의 소스 파일 이름과 파일 확장자입니다.

.예제 1. 패밀리 디렉터리의 루트에 저장된 리소스
[source]
----
📂 modules 
  📂 admin
    📂 pages <1>
      📄 modes.adoc <2>
----
<1> 페이지 패밀리 디렉토리
<2> 페이지 디렉토리의 루트에 저장된 페이지

예를 들어 예제 1에 표시된 __modes.adoc__의 파일 좌표는 __pages__ 패밀리 디렉터리의 루트에 저장되어 있으므로 __modes.adoc__입니다.

대상 리소스가 패밀리 디렉터리의 하위 디렉터리에 있는 경우 파일 좌표는 대상 리소스에 대한 패밀리 상대 디렉터리 경로를 지정해야 합니다.

.예제 2. 패밀리 디렉터리의 하위 디렉터리에 저장된 리소스
[source]
----
📂 modules
  📂 admin
    📂 pages
      📄 modes.adoc <1>
      📂 fields <2>
        📂 level <3>
          📄 routes.adoc <4>
          📄 terrain.adoc <5>
----
<1> 페이지 디렉토리의 루트에 저장된 페이지
<2> 페이지 디렉토리 내의 서브 디렉토리
<3> fields 서브디렉토리 내의 서브 디렉토리
<4> level 서브디렉토리에 저장된 페이지
<5> level 서브디렉토리에 저장된 페이지

예제 2에 표시된 페이지 __terrain.adoc__ 는 __level__ 하위 디렉터리에 저장됩니다. __terrain.adoc__의 파일 좌표는 __fields/level/terrain.adoc__입니다. __modes.adoc__(현재 페이지)이 __terrain.adoc__(대상 리소스)을 참조하는 경우 대상 리소스의 리소스 ID에 지정된 파일 좌표는 __fields/level/terrain.adoc__입니다. __terrain.adoc__(현재 페이지)가 __modes.adoc__(대상 리소스)를 참조하는 경우 대상 리소스의 리소스 ID에 지정된 파일 좌표는 __modes.adoc__입니다. **대상 리소스의 파일 좌표는 항상 패밀리 디렉터리에서 계산된다는 점을 기억하세요**.

대상 리소스와 현재 페이지가 모두 패밀리 디렉터리의 동일한 하위 디렉터리에 있는 경우 상대 경로 토큰 ./를 사용하여 대상 리소스의 파일 좌표에 대한 패밀리 상대 디렉터리 경로를 축약할 수 있습니다.

.예제 3. 동일한 하위 디렉터리에 저장된 리소스
[source]
----
📂 modules
  📂 admin
    📂 pages
      📂 fields
        📂 level
          📄 routes.adoc <1>
          📄 terrain.adoc <2>
----
<1> level 서브디렉토리에 저장된 페이지
<2> level 서브디렉토리에 저장된 페이지

예제 3에 표시된 페이지 __routes.adoc__와 __terrain.adoc__는 모두 __level__ 하위 디렉터리에 저장됩니다. __routes.adoc__(현재 페이지)가 __terrain.adoc__(대상 리소스)를 참조하는 경우 대상 리소스의 리소스 ID에 지정된 파일 좌표는 __fields/level/terrain.adoc__ 대신 __./terrain.adoc__로 지정할 수 있습니다.



