= 리소스 및 리소스 ID

== 리소스란?

**리소스**는 pages, images, partials, examples 또는 attachments 패밀리에 속하는 소스 파일입니다. Antora는 각 리소스에 Antora 리소스 ID라는 고유한 식별자를 할당합니다.

=== 게시 가능한 리소스란?

**게시 가능한 리소스**는 pages, attachments 또는 images 패밀리에 속하는 소스 파일입니다. Antora는 다른 리소스에서 참조되지 않더라도 페이지, 첨부 파일 및 이미지 파일을 사이트에 자동으로 게시합니다. 이는 partial 및 example 파일과 대조적입니다. partial 또는 example의 내용은 게시 가능한 리소스에서 직접 또는 결국 참조되는 다른 partial 또는 example을 통해 참조되는 경우에만 게시됩니다.

=== 리소스 ID란?

**Antora 리소스 ID** 또는 줄여서 **리소스 ID**는 각 리소스의 소스 파일에 할당된 속성에서 Antora가 자동으로 구성하는 표준 시퀀스로 구성된 고유하고 신뢰할 수 있는 식별 좌표 세트입니다. 다른 리소스에서 리소스를 참조하기 위해 리소스의 리소스 ID를 사용하는 경우가 많습니다. 리소스는 해당 리소스 ID를 AsciiDoc xref 매크로, include 지시문, 이미지 매크로 또는 리소스 ID를 값으로 허용하는 몇 가지 키, 속성 또는 옵션에 할당하여 참조됩니다. 그런 다음 Antora는 할당된 리소스 ID를 사용하여 가상 파일 시스템에서 해당 리소스를 조회합니다. 리소스 ID 좌표는 리소스 ID의 좌표, 리소스의 좌표를 찾는 위치 및 각 좌표를 사용하는 시기를 설명합니다.

== 리소스 ID가 중요한 이유는 무엇인가요?

리소스 ID는 소스 대 소스 참조이기 때문에 **게시된 URL에 연결되지 않습니다**. 페이지 좌표가 AsciiDoc 소스 파일의 파일 확장자인 __.adoc__로 끝나는 점에 주목하세요. 사이트를 로컬로 배포하든, 스테이징 또는 프로덕션 환경에 배포하든, URL 전략을 변경하든 상관없이 리소스 ID는 항상 동일하게 유지됩니다. xref는 대상 페이지에 잠기고 게시된 위치에 관계없이 해당 페이지를 가리키는 URL을 생성합니다.

리소스 ID는 Antora의 가상 컴포넌트 버전 분류 시스템을 기반으로 하는 식별자를 사용하여 **파일 시스템과 최소한으로 결합됩니다**.

리소스를 패밀리 상대 디렉터리 경로로 지정하여 **상대 경로(../../) 문제를 제거했습니다**. 참조하는 리소스가 패밀리 디렉터리의 하위 디렉터리에 있는 경우에도 경로는 항상 패밀리 디렉터리에서 시작합니다.

**이 사용자 친화적인 참조 시스템은 작성하는 동안 머릿속으로 계산할 필요가 없도록 해줍니다**. 참조하려는 페이지의 좌표만 지정하면 됩니다. 소스 파일의 물리적 디스크 위치나 게시된 URL에 대해 걱정할 필요가 없습니다. 이 정보를 입력할 수 있도록 컴포넌트, 버전, 모듈 및 페이지의 이름만 알면 됩니다.

== 중복 리소스

Antora는 두 개의 리소스(즉, 소스 파일)가 동일한 리소스 ID를 공유하는 것을 허용하지 않습니다. 이 상황은 다음 조건에서 발생할 수 있습니다:

. 둘 이상의 콘텐츠 소스 루트에 있는 __antora.yml__ 파일이 동일한 이름과 버전을 선언하는 경우
. 두 콘텐츠 소스 루트에 (시작 경로에서 시작하는) 동일한 상대 경로에 위치한 파일이 하나 이상 있는 경우
. 충돌하는 파일이 Antora에 의해 모두 수집되고 분류되는 경우

이러한 상황이 발생하면 Antora는 치명적인 오류를 기록하고 즉시 사이트 빌드를 중지하여 충돌하는 파일을 보고합니다.

어떤 오류가 표시되는지는 파일이 발견되는 순서에 따라 다릅니다. 두 컴포넌트 버전 모두 탐색 파일을 선언하면 중복 탐색 파일 오류가 표시될 가능성이 높습니다:

[source]
----
Duplicate nav in 1.0@name-of-component: modules/ROOT/nav.adoc
    1: modules/ROOT/nav.adoc in https://git-host/repo-name.git (branch: v1.0.x)\n' +
    2: modules/ROOT/nav.adoc in https://git-host/repo-name.git (tag: v1.0.0)'
----

그렇지 않으면 중복 페이지 또는 기타 리소스에 대한 오류가 표시됩니다:

[source]
----
Duplicate page: modules/ROOT/index.adoc in 1.0@name-of-component
    1: modules/ROOT/nav.adoc in https://git-host/repo-name.git (branch: v1.0.x)\n' +
    2: modules/ROOT/nav.adoc in https://git-host/repo-name.git (tag: v1.0.0)'
----

이 오류는 두 개의 파일이 동일한 리소스 ID를 가지려고 한다는 것을 알려줍니다. 이는 플레이북에 중복된 콘텐츠 소스 루트가 구성되어 있거나 __antora.yml__ 파일 중 하나에서 version 키를 업데이트하는 것을 잊었음을 나타낼 수 있습니다. Antora가 언급하는 git 참조를 연구하여 원인을 발견하세요.

__antora.yml__이 동일한 이름과 버전을 선언하는 분산 컴포넌트 버전을 정의하려는 경우 두 루트 중 하나에서 충돌하는 파일을 제거하여 겹치지 않도록 해야 합니다.