= content 키

``content`` 및 ``sources`` 아래에 구성된 플레이북 키는 콘텐츠 소스 저장소의 위치와 처리 방법을 정의합니다.

== content 키

``content`` 카테고리 키는 ``Antora`` 사이트의 콘텐츠 소스(즉, git 저장소) 목록을 캡슐화합니다. 콘텐츠 소스는 ``sources`` 키를 사용하여 정의됩니다. ``branches``, ``tags`` 및 ``edit_url`` 키는 모든 콘텐츠 소스에 대한 기본값을 정의하는 데 사용할 수 있습니다. 이러한 키는 콘텐츠 소스별로 다른 키와 함께 재정의할 수 있습니다.

[source, yaml]
----
content: <1>
  branches: [v2.0, v2.5, v3.0] <2> 
  tags: [release/*, '!release/*-patch'] <3> 
  edit_url: '{web_url}/blob/{refname}/{path}' <4> 
  sources: <5>
  - url: https://git-service.com/org/repo-z.git <6> 
    start_path: path-to/content-source-root <7>
  - url: https://git-service.com/org/repo-y.git <8> 
----
<1> 필수 content 키
<2> 선택적 branches 키
<3> 선택적 tags 키
<4> 선택적 edit_url 키
<5> 필수 sources 키
<6> 필수 url 키
<7> 선택적 start_path 키
<8> 다른 url 키

``content`` 및 ``sources`` 키는 필수입니다. ``sources`` 키에는 ``url`` 키가 정의된 항목이 하나 이상 포함되어야 합니다. 다른 모든 키는 선택 사항입니다. ``branches`` 및 ``edit_url`` 키에는 플레이북에서 명시적으로 설정되지 않은 경우 Antora가 런타임에 자동으로 적용하는 내장 값이 있습니다.

``content`` 바로 아래에 지정된 키-값 쌍은 키가 특정 ``url``에도 지정되지 않는 한 ``sources`` 아래의 모든 ``url`` 키 항목에 적용됩니다.

== sources 키

``sources`` 키는 필수이며 ``content`` 키 아래에 중첩됩니다. ``sources`` 키에는 소스 항목 목록이 포함됩니다. 하이픈으로 지정된 각 항목은 git 저장소 위치(URL 또는 파일 시스템 경로), 브랜치 및/또는 태그와 일치하는 패턴, 선택적 시작 경로 또는 경로 및 Antora가 사이트 콘텐츠를 집계할 때 사용하는 기타 저장소 속성으로 구성됩니다.

[source,yaml]
----
content: <1>
  sources: <2>
  - url: https://git-service.com/org/repo-z.git <3>
    branches: [v1.*, v2.*, \!v1.2] <4>
    start_paths: path-to/content-source-root-{item..item} <5> 
  - url: https://git-service.com/org/repo-y.git  <6>
    branches: [] <7>
    tags: [release/*, '!release/*-patch'] <8> 
    start_path: path-to/content-source-root <9>
    edit_url: '{web_url}/blob/{refname}/{path}' <10> 
  - url: https://git-service.com/org/repo-x.git <11>
    branches: v* <12>
    version: true <13>
----
<1> 필수 content 키
<2> 필수 sources 키
<3> 필수 url 키
<4> 선택적 branches 키
<5> 선택적 start_paths 키
<6> 다른 url 키
<7> 선택적 branches 키
<8> 선택적 tags 키
<9> 선택적 start_path 키
<10> 선택적 edit_url 키
<11> 다른 url 키
<12> 선택적 branches 키
<13> 선택적 version 키

``sources`` 키에는 ``url`` 키가 정의된 항목이 하나 이상 포함되어야 합니다. 다른 모든 키는 선택 사항입니다. ``branches`` 및 ``edit_url`` 키에는 플레이북에서 명시적으로 정의되지 않은 경우 Antora가 런타임에 자동으로 적용하는 내장 값이 있습니다.

NOTE: 콘텐츠 소스 항목에 대해 일치하는 git 참조(브랜치 또는 태그)가 없으면 Antora는 정보 수준에서 메시지를 기록합니다. 이 메시지를 보려면 로그 심각도 수준을 적어도 정보로 설정해야 합니다. 디버깅에 도움이 되도록 Antora의 로거를 적절하게 구성하는 것이 좋습니다.

``version`` 키는 구성 요소 버전 설명자(__antora.yml__)의 ``version`` 키에 대한 대체 값을 제공합니다. 단일 참조를 일치시키거나 값이 refname에서 파생되기를 원하는 경우에만 사용해야 합니다.

== 사용 가능한 content 키

다음 키는 content 키 아래에 정의할 수 있습니다. 소스 항목 자체를 포함하는 sources 키를 제외하고 이러한 키는 각 소스 항목에 대한 기본값을 제공하는 데 사용됩니다.

[cols="3,6,1"]
|===
| 콘텐츠 키 | 설명 | 필수
// branches
| branches
| 콘텐츠 소스에 지정된 저장소에서 사용할 정확한 브랜치 이름 및 이름 패턴 목록을 받아들입니다.
| 아니오
// edit_url
| edit_url
| 현재 페이지의 소스 보기에 매핑되는 URL을 작성하기 위한 URL 패턴을 받아들입니다. 다음 플레이스홀더 세그먼트를 수용합니다: {web_url}, {refname}, {refhash} 및 {path}.
| 아니오
// sources
| sources
| 콘텐츠로 사용할 저장소와 저장소 참조를 지정하는 콘텐츠 소스 항목 목록을 받아들입니다.
| 예
// tags
| tags
| 콘텐츠 소스에 지정된 저장소에서 사용할 정확한 태그 이름 및 이름 패턴 목록을 받아들입니다.
| 아니오
|===

== 사용 가능한 콘텐츠 소스 키

[cols="3,6,1"]
|===
| 콘텐츠 키 | 설명 | 필수
// branches
| branches
| 콘텐츠 소스에 지정된 저장소에서 사용할 정확한 브랜치 이름 및 이름 패턴 목록을 받아들입니다. 지정되지 않은 경우 ``content`` 키에 정의된 ``branches`` 키의 값으로 기본 설정됩니다.
| 아니오
// edit_url
| edit_url
| URL 패턴을 사용하여 현재 페이지의 소스 뷰로 매핑되는 URL을 생성할 수 있습니다. 이 패턴은 다음과 같은 자리 표시자 세그먼트를 포함할 수 있습니다: ``{web_url}``, ``{refname}``, ``{refhash}`` 및 ``{path}``.
| 아니오
// start_path
| start_path
| 콘텐츠 소스 루트의 위치에 대한 저장소의 상대 경로를 지정합니다.
| 아니오
// start_paths
| start_paths
| 정확한 경로 또는 셸 글로브 패턴으로 콘텐츠 소스 루트 위치에 대한 저장소 상대 경로 패턴 목록을 받아들입니다. 단일 값은 배열로 변환됩니다.
| 아니오
// tags
| tags
| 콘텐츠 소스에 지정된 저장소에서 사용할 정확한 태그 이름 및 이름 패턴 목록을 받아들입니다.
| 아니오
// url
| url
| HTTPS URL 또는 로컬 파일 시스템 경로일 수 있는 git 저장소의 URL을 받아들입니다.
| 예
// version
| version
| 일치하는 모든 참조에 대한 구성 요소 버전 설명자의 ``version`` 키에 대한 대체 값을 제공합니다.
| 아니오
// worktrees
| worktrees
| Antora가 사용해야 하는 해당 작업 트리를 제어하기 위해 키워드 또는 정확한 브랜치 이름 또는 이름 패턴 목록을 받아들입니다.
| 아니오
|===