= 사이트 시작 페이지

플레이북의 start_page 키에 페이지의 유효한 리소스 ID를 할당하면 사이트 방문자는 사이트 URL의 사이트 인덱스 페이지에서 시작 페이지의 URL로 리디렉션됩니다.

== start_page 키

``start_page`` 키는 선택 사항입니다. 플레이북의 ``site`` 키 아래에 구성됩니다.

.예제 1. antora-playbook.yml
[source,yaml]
----
site:
  title: Site Title
  url: https://example.org
  start_page: component:module:file-coordinate-of-page.adoc
----

구성 요소 버전에 속하는 모든 페이지를 사이트의 인덱스 페이지로 사용할 수 있습니다. ``start_page`` 키는 페이지의 리소스 ID를 값으로 받아들입니다. **리소스 ID에는 구성 요소, 모듈 및 파일 좌표가 포함되어야 합니다**. 최신 버전 대신 특정 버전의 페이지를 사용하려면 버전 좌표를 지정할 수 있습니다. 또는 CLI에서 ``start_page``를 할당할 수 있습니다.

사이트에 버전 없는 ROOT라는 이름의 구성 요소(즉, ``name: ROOT, version: ~``)가 있는 경우 해당 구성 요소는 사이트의 루트에 게시됩니다. 구성 요소 이름은 해당 페이지의 URL에 나타나지 않습니다. 즉, 버전 없는 ROOT 구성 요소의 __ROOT__ 모듈(즉, __modules/ROOT/pages/index.adoc__)의 __index.adoc__ 페이지는 플레이북에서 지정하지 않아도 암시적으로 사이트 시작 페이지 역할을 합니다. 즉, 사이트 시작 페이지는 ROOT::index.adoc입니다. 이 경우 다른 사이트 시작 페이지를 지정하면 사이트에 이미 시작 페이지가 있으므로 무시됩니다.

== 페이지의 최신 버전 사용

``start_page`` 키가 항상 지정된 페이지의 최신 버전을 가리키게 하려면 페이지의 리소스 ID에 버전 좌표를 입력하지 마세요.

.예제 2. antora-playbook.yml
[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  start_page: component-b::index.adoc
----

이 예에서는 버전 2.0이 구성 요소 B의 최신 버전이라고 가정해 보겠습니다. 이 경우 __pass:[https://demo.antora.org/index.html]__은 __pass:[https://demo.antora.org/component-b/2.0/index.html]__로 리디렉션됩니다.

== 페이지의 특정 버전 사용

사이트의 시작 페이지를 지정된 페이지의 특정 버전으로 만들려면 리소스 ID에 버전 좌표를 포함하세요.

.예제 3. antora-playbook.yml
[source,yaml]
----
site:
  title: Demo Docs Site
  url: https://demo.antora.org
  start_page: 1.0@component-b::index.adoc
----
이 예에서 __pass:[https://demo.antora.org/index.html]__은 __pass:[https://demo.antora.org/component-b/1.0/index.html]__로 리디렉션됩니다.

NOTE: 구성 요소 버전의 시작 페이지를 구성하려면 Choose a Start Page을 참조하세요.
