= 사이트 URL

== url 키

플레이북의 ``site`` 키 아래에 정의된 사이트의 ``url`` 키는 선택 사항이지만 권장됩니다. 이 키가 설정되지 않으면 사이트 URL이 필요한 사이트의 특정 기능이 자동으로 비활성화됩니다. 자세한 내용은 사이트 URL을 설정해야 하는 경우를 참조하세요.

.예제 1. antora-playbook.yml
[source,yaml]
----
site:
  title: Site Title
  url: https://docs.example.com
----

url 키는 사이트가 게시된 후 액세스할 수 있는 위치를 정의합니다. url 키의 값은 절대 URL(pass:[https://docs.example.com, https://example.com/docs]) 또는 루트 상대 URL(/products)일 수 있습니다. 값이 단일 슬래시(/)가 아닌 한 **url 값의 끝에 후행 슬래시를 포함하지 마세요**.

사이트 URL은 절대 URL 또는 루트 상대 URL이 필요한 생성된 사이트의 모든 곳에 나타납니다. 자세한 내용은 How Antora Builds URLs을 참조하세요.

또는 --url 옵션을 사용하거나 URL 환경 변수를 사용하여 CLI에서 ``url`` 키를 할당할 수 있습니다.

== 절대 사이트 URL 구성

절대 URL 값은 URL 체계 다음에 콜론과 두 개의 슬래시(pass:[https://])와 도메인(docs.example.org)이 바로 따라옵니다. URL 끝에 후행 슬래시를 넣지 마세요.

.예제 2. antora-playbook.yml
[source,yaml]
----
site:
  title: Docs for Example Site
  url: https://docs.example.com
----

절대 사이트 URL에는 하위 경로(예: pass:[https://example.com/docs, https://example.com/path/to/subfolder])가 포함될 수 있습니다. **경로 세그먼트** 또는 **경로 이름**이라고도 하는 **하위 경로**는 Antora에서 관리하는 사이트가 게시되는 도메인 루트에서의 위치를 나타냅니다. 사이트가 도메인의 하위 폴더에 게시되는 경우 절대 사이트 URL에는 이 경로가 포함되어야 합니다. 하위 경로는 루트 상대 URL과 동일한 구문을 갖습니다.

.예제 3. antora-playbook.yml
[source,yaml]
----
site:
  title: Docs for Example Site
  url: https://example.com/docs
----

절대 사이트 URL에 하위 경로가 있는 경우 Antora는 하위 경로를 추출하여 도메인 상대 URL이 필요한 모든 곳에서 사용할 수 있도록 사이트 경로 이름(__/docs__, __/path/to/subfolder__)에 할당합니다.

사이트를 도메인 하위 폴더에 게시하는 것에 대한 자세한 내용은 사이트 URL에 하위 경로를 포함해야 하는 경우를 참조하세요.

== 루트 상대 사이트 URL 구성

루트 상대 URL은 도메인 자체를 지정하지 않고도 도메인을 기준으로 하는 URL입니다. 루트 상대 URL은 슬래시(__/products__)로 시작해야 합니다.

.예제 4. antora-playbook.yml
[source,yaml]
----
site:
  title: Docs Hosted Somewhere
  url: /products
----

동일한 사이트를 여러 도메인에 게시하거나 여러 도메인을 통해 액세스할 수 있어야 하는 경우 절대 URL 대신 루트 상대 URL을 사용할 수 있습니다. 루트 상대 URL을 사용하면 사이트 URL 할당의 많은 이점을 활용할 수 있습니다. 그러나 ``url``에 할당된 값이 절대값이 아닌 경우 Antora는 절대 사이트 URL에 의존하는 모든 기능을 비활성화합니다.

Antora는 루트 상대 URL을 도메인 상대 URL을 계산하기 위한 사이트 경로 이름에 직접 할당합니다. url을 루트 상대 URL로 설정하되 사이트 경로 이름을 비워 두려면 값을 단일 슬래시로 설정하세요.

.예제 5. antora-playbook.yml
[source,yaml]
----
site:
  title: The Docs
  url: /
----

== 사이트 URL을 설정해야 하는 경우

Antora 사이트는 오프라인에서 로컬 파일 시스템에서 볼 수 있도록 설계되었습니다. 이러한 이유로 사이트를 구축하는 데 사이트 URL이 필요하지 않습니다.

그러나 사이트 URL, 심지어 절대 URL까지도 필요로 하는 게시와 관련된 특정 기능들이 있습니다. 사이트 URL이 설정되지 않으면 이러한 기능은 알림 없이 자동으로 비활성화됩니다. 이 섹션에서는 이러한 기능과 필요한 사이트 URL의 종류를 식별합니다.

=== 사이트 URL에 의존하는 기능

사이트 URL이 허용 가능한 값으로 설정되면 다음 기능이 활성화됩니다:

- ``site-url`` 속성이 모든 AsciiDoc 문서에 설정됩니다.
- ``site.url`` 속성이 UI 모델에 설정됩니다(플레이북의 ``site.url`` 키 값 사용).
- 사이트 경로 이름 속성 site.path가 UI 모델에 설정됩니다(플레이북의 ``site.url`` 키에서 파생).
- 404 페이지가 생성됩니다.
- ``site.robots``가 플레이북에도 정의된 경우 __robots.txt__ 파일이 생성됩니다.
- 리디렉션에는 사이트 경로 이름(``site.path``)이 포함됩니다(비어 있지 않은 경우). 이는 - 상대 URL을 사용하는 정적 리디렉션 기능에는 영향을 미치지 않습니다.
- 탐색 막대의 왼쪽 상단 모서리에 있는 링크는 상대 경로 대신 사이트 URL을 가리킵니다(기본 UI에 특정한 동작).

사이트 URL이 절대 URL로 설정되면 다음과 같은 추가 기능이 활성화됩니다:

- 사이트맵 파일이 생성됩니다.
- ``page.canonicalUrl``이 UI 모델에 설정되며, 이는 참조 UI에서 헤드에 정식 링크 태그를 생성하는 데 사용됩니다.

사이트 URL이 설정되지 않으면 앞서 언급한 모든 기능이 비활성화됩니다.

=== 사이트 URL에 하위 경로를 포함해야 하는 경우

사이트 URL의 하위 경로는 Antora에서 관리하는 사이트가 위치한 도메인의 루트에서의 위치를 나타냅니다. 즉, 사이트 URL은 방문자를 사이트 시작 페이지에 대한 리디렉션이 위치한 URL로 안내합니다. 사이트가 도메인의 하위 폴더에 게시되는 경우 사이트 URL에는 이 경로(__/path/to/subfolder__)가 포함되어야 합니다.

필요한 경우 Antora는 사이트 URL을 사용하여 사이트의 페이지에 대한 절대 및 도메인 상대 URL을 구성하며, 이는 항상 지정된 경우 하위 경로를 포함합니다. 여기에는 사이트맵(절대 URL)의 URL과 재작성 규칙(도메인 상대 URL)이 포함됩니다.

서버 리디렉션 규칙을 만들 때 하위 경로가 사용되는 방법의 예를 살펴보겠습니다. 다음 조건이 참이라고 가정해 보겠습니다:

- 사이트가 example.com 도메인의 __docs__ 하위 폴더에 게시됩니다.
- 버전 없는 __component-a__ 구성 요소의 ROOT 모듈에 있는 __new-page.adoc__ 페이지는 페이지 별칭 __old-page.adoc__을 정의합니다(즉, __old-page.adoc__의 이름이 __new-page.adoc__으로 변경되었음).
- 리디렉션 기능이 nginx로 설정됩니다.
- 플레이북에서 사이트 ``url`` 키를 pass:[https://example.com(잘못된 값)]으로 설정합니다.

Antora를 실행하면 다음과 같은 리디렉션 규칙이 생성됩니다:

.예제 6. 하위 경로를 포함하지 않는 리디렉션 항목
[source]
----
/component-a/old-page.html /component-a/new-page.html 301!
----

리디렉션 규칙의 도메인 상대 URL에 /docs 세그먼트가 포함되어 있지 않습니다. 즉, pass:[https://example.com/docs/component-a/old-page.html]을 방문하면 규칙이 일치하지 않으므로 새 페이지로 리디렉션되지 않습니다. 이를 수정해 보겠습니다.
플레이북을 편집하고 url 키를 pass:[https://example.com/docs]로 설정합니다. 이제 Antora를 실행하면 올바른 리디렉션 규칙이 생성됩니다:

.예제 7. 하위 경로를 포함하는 리디렉션 항목
[source]
----
/docs/component-a/old-page.html /docs/component-a/new-page.html 301!
----

도메인 상대 URL에 /docs 세그먼트가 포함되어 있습니다. 이제 pass:[https://example.com/docs/component-a/old-page.html]을 방문하면 새 페이지로 리디렉션됩니다.

사이트를 도메인의 하위 폴더에 게시하는 경우 절대 사이트 URL에 경로를 포함하는 것이 중요합니다. 사이트를 특정 도메인에 연결하지 않으려면 루트 상대 사이트 URL을 대신 할당하세요. 어느 쪽이든 사이트를 도메인의 하위 폴더에 게시하는 경우 사이트의 url 키에 할당하는 값에 하위 경로를 포함해야 합니다.

== 정식 URL (Canonical URL)

Antora는 정식 URL에 대한 기본 지원을 제공합니다. **정식 URL**은 페이지의 선호 버전에 대한 절대 URL입니다. 검색 엔진이 색인하기를 원하는 페이지입니다.

사이트 URL에 절대 URL을 할당하면 Antora는 정식 URL을 계산하여 해당 페이지에 대한 UI 모델의 ``page.canonicalUrl`` 속성에 할당합니다. 해당 페이지는 적어도 하나의 사전 릴리스가 아닌 버전이 있는 구성 요소의 모든 게시 가능한 페이지입니다. 사이트 URL이 절대 URL로 설정되지 않았거나 페이지가 적어도 하나의 사전 릴리스가 아닌 버전이 있는 구성 요소에 없는 경우 Antora는 정식 URL을 채우지 않습니다.

정식 URL은 페이지의 최신 사전 릴리스가 아닌 버전의 절대 URL입니다. 정식 URL은 사이트 URL(하위 경로 포함)을 해당 페이지의 (루트 상대) URL 앞에 추가하여 계산됩니다.
정식 URL은 현재 페이지가 최신 사전 릴리스가 아닌 버전인 경우에만 현재 페이지를 가리킵니다. 그렇지 않으면 정식 URL은 현재 페이지의 최신 사전 릴리스가 아닌 버전을 가리킵니다.

CAUTION: 페이지가 삭제된 경우 페이지의 최신 버전이 구성 요소의 최신 버전에 없을 수 있습니다.

=== 정식 URL 링크 태그

정식 URL이 검색 크롤러에 의해 선택되려면 UI 템플릿에 페이지에 포함되어야 합니다. 정식 URL은 페이지의 ``<head>`` 태그 내에 있는 ``<link rel="canonical">`` 태그의 ``href`` 속성 값으로 선언되어야 합니다. Antora의 기본 UI는 이를 자동으로 처리합니다. 다음은 이 <link> 태그를 생성하는 Antora의 기본 UI에서 가져온 템플릿 로직입니다:

[source,hbs]
----
{{#with page.canonicalUrl}}
<link rel="canonical" href="{{{this}}}">
{{/with}}
----

생성된 페이지에서 정식 URL은 다음과 같이 나타납니다:

[source,html]
----
<link ref="canonical" href="https://docs.example.org/component-name/2.0/page-name.html">
----

정식 URL이 참조하는 페이지가 구성 요소의 모든 버전에 존재한다고 가정하면, 페이지의 모든 버전에 동일한 <link> 태그가 포함됩니다. 페이지가 사전 릴리스 버전에 있는 경우 최신(사전 릴리스가 아닌) 버전의 페이지를 참조합니다.

사용자 정의 UI의 작성자가 페이지 템플릿에 정식 URL을 포함할지 여부를 결정합니다. Antora는 단순히 UI 페이지 모델을 통해 정보를 사용할 수 있게 합니다. Antora의 기본 UI는 페이지 템플릿에 필요한 태그를 포함합니다.

=== 정식 URL(Canonical URL)의 작동 방식

정식 URL의 목적은 검색 엔진이 동일한 페이지의 버전을 상호 연관시키고 페이지의 선호 버전(즉, 색인할 버전)을 제안하는 데 도움을 주는 것입니다. 검색 엔진이 현재 URL과 다른 정식 URL이 있는 페이지를 발견하면 해당 페이지를 색인하지 않고 정식 URL이 가리키는 페이지를 색인해야 합니다. 정식 URL을 정의함으로써 페이지의 이전 버전이 검색 결과에 표시되지 않도록 해야 합니다.

한 가지 주의할 점은, 페이지가 구성 요소의 이전 버전에는 존재하지만 최신 버전에는 없는 경우, 정식 URL(canonical URL)이 이전 버전의 페이지를 가리키게 되어 그 페이지가 색인될 수 있다는 것입니다. 이를 방지하려면, 구성 요소의 최신 버전에서 다른 페이지가 해당 페이지를 페이지 별칭(page alias)을 사용하여 대신 참조하도록 해야 합니다. 이렇게 하면 Antora가 정식 URL이 최신 버전의 해당 페이지를 가리키도록 구성하여, 이전 버전의 페이지가 색인되는 것을 방지할 수 있습니다.

URL 검사 도구를 사용하여 Google이 페이지에 대해 감지한 정식 URL을 확인하고 페이지가 색인되었는지 확인하세요. 중복 URL 통합 및 정식 URL을 참조하여 정식 URL에 대해 자세히 알아보고 Google과 같은 검색 엔진이 이를 어떻게 해석하는지 확인하세요.
