= 사이트 키

site 아래에 구성된 플레이북 키는 사이트가 게시된 후 사이트의 게시된 ID와 특정 애플리케이션과의 상호 작용 방식을 관리합니다.

== site 키

전역적으로 생성된 사이트 파일, 서비스 계정 및 기타 공통 속성은 플레이북 파일의 site 키 아래에 정의됩니다. 이러한 설정은 사이트가 생성될 때 전체 사이트에 적용됩니다.

[source,yaml]
----
site: <1>
  title: Docs Site <2> 
  url: https://docs.example.org <3> 
  start_page: component-b::index.adoc <4> 
  robots: allow <5>
  keys: <6>
    google_analytics: XX-123456 <7>
----
<1> 필수 site 키
<2> 필수 title 키
<3> 선택적 url 키
<4> 선택적 start_page 키
<5> 선택적 robots 키
<6> 선택적 keys 키
<7> 예제 google_analytics 키

``site`` 범주의 ``title`` 키는 필수입니다. ``url`` 키는 선택 사항이지만 권장됩니다. 자세한 내용은 사이트 URL을 설정해야 하는 경우를 참조하세요. 다른 키는 선택 사항입니다. 지정하지 않으면 Antora는 기본값을 사용합니다. 또는 ``title``, ``start_page`` 및 ``keys``를 CLI에서 할당할 수 있습니다. url 키는 CLI 또는 환경 변수를 사용하여 할당할 수 있습니다.

== 사용 가능한 사이트 키
[cols="3,6,1"]
|===
| 사이트 키 | 설명 | 필수 여부

| keys
| UI 템플릿 또는 확장에서 참조할 계정 및 API 키. Google Analytics와 같은 서비스 통합을 위한 계정 식별자를 지정하는 이름-값 쌍의 맵을 받아들입니다.
| 아니오

| robots
| Antora가 __robots.txt__ 파일을 생성할지 여부를 지정합니다. ``allow``, ``disallow`` 값과 사용자 정의 다중 행 문자열을 받아들입니다. 형제 ``url`` 키가 설정되지 않은 경우 무시됩니다.
| 아니오

| start_page
| 사이트의 시작 페이지를 지정하는 페이지의 리소스 ID를 받아들입니다.
| 아니오

| title
| 사이트의 제목을 지정합니다.
| 예

| url
| 사이트의 기본 URL을 지정합니다.
| 아니오
|===
