= Antora 플레이북

이 페이지에서 다음을 배울 수 있습니다:

* [*] Antora 플레이북의 목적.
* [*] 플레이북 파일의 위치.
* [*] Antora가 허용하는 플레이북 파일 형식.

== Antora 플레이북이란?

Antora 플레이북을 사용하면 기술 작가가 플레이북 파일을 사용하여 사이트에 포함된 콘텐츠, 적용된 사용자 인터페이스(UI) 및 사이트가 게시되는 위치를 쉽게 제어할 수 있습니다. 플레이북 파일의 설정은 CLI 옵션 및 환경 변수와 결합하여 Antora에 작동 방법을 알려줍니다.

특히, 플레이북은 Antora에 다음을 알려줍니다:

* [*] 제목 및 URL과 같이 사이트에 전체적으로 적용해야 하는 정보.
* [*] 사이트의 루트에 있는 페이지(예: 홈 또는 랜딩 페이지 콘텐츠).
* [*] Antora에 공급할 콘텐츠 리포지토리, 브랜치 및 태그.
* [*] 사이트 전체에 적용해야 하는 AsciiDoc 속성 및 Asciidoctor 확장.
* [*] 페이지의 시각적 레이아웃, 스타일 및 동작을 제어하는 데 사용할 UI 번들.
* [*] 사이트를 게시해야 하는 위치와 출력 형식.
* [*] Antora가 소스 리포지토리 업데이트, 아티팩트 업데이트 및 캐시를 처리하는 방법과 시기.

또한 플레이북 파일의 특정 설정은 CLI 옵션 또는 환경 변수를 사용하여 재정의할 수 있으므로 운영 팀이 프로덕션과 같은 특정 환경에 맞게 동작을 조정할 수 있습니다.

== 플레이북은 어디에 저장되나요?

플레이북은 일반적으로 플레이북 프로젝트에 있습니다. 플레이북 프로젝트 리포지토리는 문서 사이트 생성을 담당합니다. 이것은 엄격히 코드로서의 구성 리포지토리입니다. 콘텐츠를 포함하지 않습니다. 대신 플레이북 파일과 특정 상황에서 추가 UI 파일 및 확장 코드를 포함합니다.

== 플레이북 파일 형식

플레이북은 YAML, JSON 및 TOML로 작성할 수 있습니다. YAML은 자동화된 작업을 정의하는 데 일반적으로 사용되는 구성 언어이며 이 문서의 대부분의 플레이북 예제는 YAML을 사용합니다. 하지만 이러한 형식 중 어떤 것이든 자유롭게 사용할 수 있습니다.

형식에 관계없이 플레이북에는 일반 사이트 속성, 콘텐츠 및 UI 입력 소스, 게시된 출력 대상 및 제공자를 지정하기 위한 구조화된 키-값 쌍이 포함되어 있습니다.

== 플레이북의 상대 경로

기본적으로 Antora는 현재 작업 디렉터리에서 플레이북의 상대 경로를 해석합니다. 예를 들어 경로 __public__은 실제로 __$PWD/public__입니다. 대신 Antora가 플레이북 파일이 있는 디렉터리에서 상대 경로를 해석하려면 경로 앞에 ``./``를 붙이세요(예: __./public__).

상대 경로를 ``./``로 시작하면 플레이북을 더 이식 가능하게 만들 수 있습니다. 파일 시스템의 어떤 디렉터리에서든 antora 명령을 실행할 수 있으며 동작은 동일합니다.

상대 경로를 ``./``로 시작하지 않으면 Antora가 해석하는 경로는 현재 작업 디렉터리에 따라 달라집니다. 이식 가능한 동작을 얻으려면 antora 명령을 실행하기 전에 플레이북 파일이 있는 디렉터리로 전환해야 합니다.

경로를 현재 작업 디렉터리에 연결하려는 경우에만 일반 상대 경로를 사용하세요.